### ISSUE TITLE
Spike Formatting

### ISSUE THREAD

**Issue by eschuma** [csn-le/wave_clus#10]
Hi,

I am interested in using your spike clustering software for my research on weekly electric fish, but I am having a difficult time formatting my data in a way the program can read. I have spikes already in MATLAB, but I keep getting an error stating that fewer than 15 spikes have been detected when I try to load the data into the gui interface. I have 214 spikes. I saw in the powerpoint that there was an example file (test1_spikes.mat) to format the data, but I could not find this file.  Could you please tell me how I can format my data to be read by the program?

Thanks!

**Comment by ferchaure** [comment]
The file should have at least 2 variables:

**spikes**  with: size(spikes,1) == _number of spikes_  and size(spikes,2) == _samples of each spike_

**index** a vector thit the detection times in ms

**Comment by ferchaure** [comment]
If you want to use wave_clus to realign the spikes be careful with the par.alignment_window parameter  because the spikes should have at least: par.w_pre + w_posls + (2*align_window)+4.

If the spikes are already alignment, the spike's file should be called FILENAME_spikes.mat

**Comment by ferchaure** [comment]
If you are making "_spikes" files, remember to interpolate the spikes to improve the alignment.
Otherwise make files without the "_spikes" with extra samples at the beginning and the end of the spike.
size(spikes,2) == extra samples+samples of each spike + extra samples

extra samples > 4

**Comment by eschuma** [comment]
The spikes are prealigned. Thank you for the help! It is working now.
