### ISSUE TITLE
Error loading a .mat file

### ISSUE THREAD

**Issue by koro30** [csn-le/wave_clus#100]
Hi!
I am a new wave_clus user and I am having some troubles when I tried to load the data.
The data is a continuos Data set, saved as Data.mat into the wave_clus folder, with an sr=20000Hz.
Everytime I tried to load the file different error appears, mainly:

**Error using wave_clus>load_data_button_Callback (line 230)
Less than 15 spikes detected

Error in gui_mainfcn (line 95)
        feval(varargin{:});

Error in wave_clus (line 63)
    gui_mainfcn(gui_State, varargin{:});
 
Error while evaluating UIControl Callback.**

I already tried to change the different paramters you recommended like std.detection and the par.detection=both but the results is the same.
I do the spiking sorting with other software and normally it works, I know that I have many spikes in my file so is not true that I have less than 15.
Could you please help me with this issue?

Thanks!

**Comment by ferchaure** [comment]
Can you try with:
par.stdmin = 3.5; 
par.stdmax = 100;                     % it's odd butmaybe you have an amazing SNR
par.detection = 'both';

Could you load in some place a segment of the signal?

**Comment by koro30** [comment]
Hi Fernando, 
I tried again changing all this parameters and nothing happened, just a new error. Here you have a link to a small segment of the raw signal: 
 https://www.dropbox.com/s/sa0cv7h9qbo1pqb/Data1.mat?dl=0
I am using MATLAB2018a now, I tried first with 2008b version with similar results. 
Many thanks for the help!

**Comment by ferchaure** [comment]
Remember that inside the file, the sample rate have to be stored in a variable called _sr_ and the raw signal in a variable called _data_. I forgot to tell you before but you don't need to put the file inside the wave_clus folder.

**Comment by koro30** [comment]
Hi again! I saved a new file just with this 2 variables and now is working perfectly, thank you very much

________________________________
De: Fernando J. Chaure <notifications@github.com>
Enviado: miércoles, 17 de octubre de 2018 15:12
Para: csn-le/wave_clus
Cc: koro30; Author
Asunto: Re: [csn-le/wave_clus] Error loading a .mat file (#100)


Remember that inside the file, the sample rate have to be stored in a variable called sr and the raw signal in a variable called data. I forgot to tell you before but you don't need to put the file inside the wave_clus folder.
