### ISSUE TITLE
About a fixed noise

### ISSUE THREAD

**Issue by koro30** [csn-le/wave_clus#105]
Hi Fernando, 
I have some human intracraneal recordings (from midbrain) and there is a constant noise that appears every 20ms. Fortunately most of the time waveclus isolates it as a different cluster, and is ok because all the noise is isolated in one. But many times this 20ms contaminates the other cluster and I don't know how to get rid of it. 
It looks like a tonic firing but is too clean to be it. 
Do you know if there is a way to do it?
Thanks!

**Comment by ferchaure** [comment]
Hi, I don't have a perfect solution. You could:
- Manually select and clean the clusters using the gui.
- using a smaller value for the max distance in the template matching step (if the unforced cluster doesn't mix noise and spike)
- if the noise is more or less always the same , maybe you can code a comparator to remove all the spikes that have a small euclidean distance to the noise after the detection in the _spikes.mat file
