### ISSUE TITLE
loading simulated data

### ISSUE THREAD

**Issue by KermaniMojtaba** [csn-le/wave_clus#11]
Hi,
when I load any of simulated data, Matlab gives me this error:
Unable to read file 'data_wc.dg_01.lab': no such file or directory.
and I can't do further processing, any suggestion?
thanks

**Comment by ferchaure** [comment]
Sorry, Could you tell me which simulated files are you trying to open? 
Are you using Linux?

**Comment by KermaniMojtaba** [comment]
Hi,
I'm using Wave_clus on Mac machine and want to load any of simulated data from a folder inside the wave_cluse toolbox package called "simulator".

**Comment by KermaniMojtaba** [comment]
cluster_maci.exe exist in the folder, but apparently doesn't work

**Comment by ferchaure** [comment]
And its privileges ? 
Could you run this Matlab line in the data folder:
fileattrib('cluster_maci.exe','+x')

**Comment by ferchaure** [comment]
This part of the code has been changed
