### ISSUE TITLE
crash during wave_features.m when variable all_above1 has less than 2 elements

### ISSUE THREAD

**Issue by rebrowski** [csn-le/wave_clus#114]
Hi Fernando, 

Thanks a lot for wave_clus3! It works great so far - only on some rather noisy channels I get an error when clustering, namely:

<img width="839" alt="grafik" src="https://user-images.githubusercontent.com/15016252/50723167-45b64980-10da-11e9-815e-d83a129262fa.png">

The problem seems to arise when the variable `all_above1` in `wave_features.m` has less than 2 entries. 

An immediate solution for me was to add some lines of code in `wave_features.m` around line 70 from initially:
``` 
aux2 = diff(all_above1);
```
to 
```
if numel(all_above1 == 1)
   aux2 = all_above1;
elseif isempty(all_above1)
   aux2 = 1;
else    
   aux2 = diff(all_above1);
end
```

The channel in the example above looks like this in the GUI when using this fix:

<img width="1221" alt="grafik" src="https://user-images.githubusercontent.com/15016252/50723289-de999480-10db-11e9-84d0-5087586c967a.png">

An exmample, where `all_above1` had 1 entry lookes like this after the fix:

<img width="1213" alt="grafik" src="https://user-images.githubusercontent.com/15016252/50723315-52d43800-10dc-11e9-8688-e0e79ed91feb.png">

I would probably like to exclude such channels from furhter analyses anyway, but would like `Do_clustering.m` to run through on all channels without errors for the purpose of quick, automated analyses such as screening session and the like. What do you think?

cheers, 
Thomas

**Comment by ferchaure** [comment]
Hi Thomas, that is an interesting observation. I will add a few lines like you suggested.

**Comment by rebrowski** [comment]
Thanks!
