### ISSUE TITLE
The raw data is already fully loaded

### ISSUE THREAD

**Issue by Lisandro79** [csn-le/wave_clus#115]
Hi Fernando,

I was able to load a data segment from a file and plot the spike detection, but after that first time each time I try to load the same segment of data (or any other) I get the following error:

> Segment read only for plotting
> Error using readInData/get_segment (line 224)
> The raw data is already fully loaded
> 
> Error in readInData/get_signal_sample (line 260)
>                     obj.get_segment();
> 
> Error in Get_spikes>get_spikes_single (line 195)
>         [psegment, sr_psegment] = data_handler.get_signal_sample();
> 
> Error in Get_spikes (line 130)
>         get_spikes_single(filename, par_input);

Even if I shut down and restart Matlab, I see the error "The raw data is already fully loaded". I am using Matlab 2017a.

Any suggestions on how to deal with this?

Thanks a lot

Best

**Comment by ferchaure** [comment]
Hi. What type of data file? Did you edit some file from the Raw_data_readers folder?

**Comment by Lisandro79** [comment]
Hi,

Here is the .mat file I am using (with 'data' and  'sr' as variables)

[id_mes_1_id_sig_3.mat.zip](https://github.com/csn-le/wave_clus/files/2756579/id_mes_1_id_sig_3.mat.zip)

I did not edit any file from the Raw_data_readers folder

Thanks  a lot

Cheers

**Comment by ferchaure** [comment]
For now, make sr a double (I will fix that condition in the next commit) and tell me if that fix your the issue

**Comment by Lisandro79** [comment]
Yes, that fixed the issue. 

Thanks a lot

Cheers
