### ISSUE TITLE
License?

### ISSUE THREAD

**Issue by galenlynch** [csn-le/wave_clus#118]
Does this project have a license?

**Comment by ferchaure** [comment]
Hi, I added in the readme.m the closest thing to a license that Quian Quiroga put in the original documentation.

**Comment by ferchaure** [comment]
Yes, of course. Let me know if you need some help.

**Comment by galenlynch** [comment]
The issue is simply that I like using this great library (thank you!), but without some sort of open source license, it's unclear if I'm allowed to make modifications to the source code. For details, see the discussion here: https://opensource.stackexchange.com/questions/1720/what-can-i-assume-if-a-publicly-published-project-has-no-license

Adding some sort of open source license for non-commercial applications would be a great help if you ever get around to it! Either, way, thanks for the great software.
