### ISSUE TITLE
Batch processing, file extension missing

### ISSUE THREAD

**Issue by YveKr** [csn-le/wave_clus#120]
I just have a minor point about the batch processing routine, it does not work until you add '.mat' extensions to the '_spikes' files and to the 'times_' files saved during batch processing.
One needs to add these during the saving stage in both batch-files to get correct output and figures. Thanks for the new version.

**Comment by ferchaure** [comment]
that is odd, Matlab adds its extension automatically to the files, which Matlab version are you using?

**Comment by YveKr** [comment]
R2016b

**Comment by YveKr** [comment]
it resulted in something similar to this post, subplots not showing up for the figures because not able to open 'times_' :
https://github.com/csn-le/wave_clus/issues/51#issuecomment-333220060

only a minor issue though

**Comment by ferchaure** [comment]
Does the raw data files a dot in the name?

**Comment by YveKr** [comment]
Yes, indeed this might be the issue. But after adding '.mat' to force it, everything works fine.

**Comment by ferchaure** [comment]
I would recommend remove the dot in the filenames, it can be annoying for a lot of applications.

**Comment by YveKr** [comment]
I know... it's just that I got many short files (a few 100s) from different people and they all have info such as recording coordinates, durations, etc. in the file names. it's certainly not ideal, but once sorted, I won't use the RAW data files anymore. Thanks
