### ISSUE TITLE
Dissociating spike detection threshold from SPC_spike sorting threshold

### ISSUE THREAD

**Issue by aboharbf** [csn-le/wave_clus#121]
The issue I have right now is I want to capture as much spiking as possible while not creating unbelievable units. A low threshold for spike detection (lets say 3 SD above noise) leads to "Units" with average activities around 100 Hz (for a 3 second window), which seems to be clearly MUA. Thresholds at 5 SD are missing lots of MUA. 

My plan is to disassociate the threshold used for clustering vs the threshold used for detection. My current approach is to change what is taking place in the "do_clustering_single" function of "do_clustering".

Once spikes are loaded, **naux** is used to cap the spikes going into the SPC, and spike features are calculated and placed in **inspk**. Following that, a random sampling are taken (depending on parameters) and saved as **inspk_aux**, which is saved to the par variable, which is then saved somewhere the SPC script finds it. What I did to add this "filtering step" was add the following, after inspk is created (since I'd like these spikes to be added to clusters, just not used to find them).  

```
spikePeaks = max(abs(spikes),[],2);
spikeMask = spikePeaks > 100; %Get this variable from parameters or spikes, whichever we can add it to most easily.

inspk = inspk(spikeMask,:);
```

the threshold is choosen arbitrarily, once I get this working I'd get the right value passed here. 

This seems to work more or less. As far as indexing goes, this step takes place before **ipermut** is constructed, so it doesn't seem to interfere with appropriate indexing of spikes or their classes. However, when i run this, I get something like the following:

![image](https://user-images.githubusercontent.com/25850560/52578705-c6abe380-2df2-11e9-8097-513d1926bea5.png)

Which confuses me mainly because I would expect the mean cluster waveform would end up reliably above or near the threshold set by the mask (100, in this case). Cluster 2 has its peak at -87, which is reasonable but somewhat low, and Cluster 1 has it at -57. My question is, given what I changed, is the forcing algorithm acting over-aggressively and putting many waveforms far away from the original clusters into them, or is something else going on? any insight would be great.

**Comment by aboharbf** [comment]
My code for reference - https://github.com/aboharbf/wave_clus

**Comment by ferchaure** [comment]
Hi. I didn't check the code (probably is easy  define ipermut as a subgroup of the spikes with a high peak, and then everything should work) 
S you said, probably the issue is that the forcing algorithm doesn't have a MU template and the

**Comment by aboharbf** [comment]
Hey Ferchaure,

I've attempted to go that route, but ipermut only gets used in cases where permut is set to on, and I'd like this approach to be the default in the case of either permutations or no permutations. Am I correct in believing the only approach is to filter and correctly sort inspk?

**Comment by ferchaure** [comment]
Hi aboharbf:
You only have to choose which spikes you want for the clustering and then select inspk from that subset (in order or randomly)
