### ISSUE TITLE
Trouble loading data from a .rhs format

### ISSUE THREAD

**Issue by amyjwegener** [csn-le/wave_clus#122]
Hello!

I am new to spike sorting and using MEAs to record activity. I have an Intan amplifier and my data is saved in a .rhs format. I have used the intan reader to create .mat files and I saved the amplifier data as variable "data." I can use the Get_spikes code to generate a new spikes file. However, when I attempt to use the GUI, for the original file or the new spikes file, I receive the following error. 

>> wave_clus
Access is denied.

Error using load
Unable to read file 'data_wc.dg_01.lab'. No such file or directory.

Error in run_cluster (line 121)
clu = load([fname '.dg_01.lab']);

Error in wave_clus>load_data_button_Callback (line 260)
    [clu,tree] = run_cluster(handles.par);

Error in gui_mainfcn (line 95)
        feval(varargin{:});

Error in wave_clus (line 63)
    gui_mainfcn(gui_State, varargin{:});
 
Error while evaluating UIControl Callback.

>> 

IF you have any guidance on troubleshooting this error, I would appreciate it!

Thank you,
Amy

**Comment by ferchaure** [comment]
It looks like a permission issue, try moving your data to a new folder

**Comment by amyjwegener** [comment]
I just noticed it the wave_clus intro PDF it says to copy a font file from the wave_clus directory into a Windows folder. Only problem is I don't have admin rights on my current computer. Do you know of a workaround?

Thanks,
Amy

**Comment by ferchaure** [comment]
The font file isn't the problem.
