### ISSUE TITLE
How do I know the absolute amplitude of my sorted spikes?

### ISSUE THREAD

**Issue by vaniacong** [csn-le/wave_clus#124]
Hi, I have used wave_clus to sort the spikes and it displays in the GUI. What does the Y-axis represent in each cluster? How do I get the absolute amplitude of the spikes from those numbers? Thanks!

**Comment by ferchaure** [comment]
The y axis represents the voltage of the filtered signal. If you save the result and open the mat file (check the wiki for more information about the variables)  you will can load the filtered spikes of each cluster and get any metric you want.
