### ISSUE TITLE
Loading TDT data

### ISSUE THREAD

**Issue by YawRay** [csn-le/wave_clus#125]
Hi, I don't have any programming experience.  I have some electorphysiological data recorded with Tucker Davies Technologies (TDT) system. It comprises 12 channels (3 tetrodes). Each file comprises 20 minute recordings sampled at 24KHz. I recorded frequencies between 0.5 and 10000 Hz. I tried opening it directly using wave clus but it seems wave clus does not recognize the format of the original data. So converted the data into a .mat format and tried opening it again but I keep getting this error message:

Error in wave_clus (line 63)
    gui_mainfcn(gui_State, varargin{:});
 
Error while evaluating UIControl Callback

Am I doing anything wrong and if I am, how can I correctly load my data into wave clus?

Any advice?

**Comment by ferchaure** [comment]
Did you add the wave_clus folder with subfolders to the matlab path?

**Comment by YawRay** [comment]
Yes, I did.

**Comment by YawRay** [comment]
Actually, it seems I did not see the complete error message. This is the complete message:

Wave_clus didn't find a sampling rate in file. It will use the input parameter or set_parameters.m
Error using double
Conversion to double from struct is not possible.

Error in readInData/get_segment (line 230)
                x = double(x);

Error in wave_clus>load_data_button_Callback (line 223)
            x = data_handler.get_segment();

Error in gui_mainfcn (line 95)
        feval(varargin{:});

Error in wave_clus (line 63)
    gui_mainfcn(gui_State, varargin{:});
 
Error while evaluating UIControl Callback

**Comment by ferchaure** [comment]
ok, this is after converting the data to a mat file? check that the .mat file has a variable called data with the  recorded signal as a vector

**Comment by YawRay** [comment]
Yes, it does have a variable called data. It contains 12 rows and 29450241 columns (12x29450241 single). How do I proceed?

**Comment by YawRay** [comment]
I saved just one row of the 12x29450241 single matrix data (representing one channel) and tried opening it by clicking "load data" on the wave_clus interface but I got this error message:

Wave_clus didn't find a sampling rate in file. It will use the input parameter or set_parameters.m
Error using wave_clus>load_data_button_Callback (line 233)
Less than 15 spikes detected

Error in gui_mainfcn (line 95)
        feval(varargin{:});

Error in wave_clus (line 63)
    gui_mainfcn(gui_State, varargin{:});
 
Error while evaluating UIControl Callback

I am not sure what to do now. I also tried loading the data using Get_spikes_pol(1), after pasting the name of the data file in a .txt file, but it did not work either. I have been working with the raw continuous data exported to .mat format all along. Can anyone please advice me on how to proceed?

Thank you!

**Comment by YawRay** [comment]
Hi,

I am able to load my data in wave_clus now. The issue I had was with the format of the data after exporting it into .mat. It was a structure.

I have another question. After detecting the spikes and clustering, I am getting very low numbers of clusters. It may be because the signal to noise ratio is a bit low but can you suggest any parameter I can change to increase the number of clusters, aside the "par.max_clus" parameter?

**Comment by ferchaure** [comment]
> I am getting very low numbers of clusters. It may be because the signal to noise ratio is a bit low but can you suggest any parameter I can change to increase the number of clusters, aside the "par.max_clus" parameter?

Try to reduce the value of min_clus to 10 (this may generate overclustering). If the signal to noise ratio is small, you could try to increase stdmin to detect less noise as spikes and do the clustering a bit easier for the algorithm.

**Comment by YawRay** [comment]
Thank you for your suggestions. I will try them out.
