### ISSUE TITLE
Batch files

### ISSUE THREAD

**Issue by YawRay** [csn-le/wave_clus#126]
Hi again,

I am trying to analyse data from a tetrode. I created a txt file called polytrode1.txt and within this file I have:

my_channel_1.mat
my_channel_2.mat
my_channel_3.mat
my_channel_4.mat

When I run Get_spikes_pol(1), I get the following error message:

Error using Get_spikes_pol>get_spikes_pol_single (line 107)
The file my_channel_1.mat doesn't have raw data

Error in Get_spikes_pol (line 62)
        get_spikes_pol_single(polytrodes(j), par_input);

Does anyone know how I can solve this issue?

Thank you.

**Comment by ferchaure** [comment]
I think that is the same issue as before, you had a structure in your mat files

**Comment by YawRay** [comment]
HI,

It is not the same issue. It is not a structure mat file. I created it the same way I created the mat files for loading into the wave_clus gui, which worked. In fact, I recreated the files again and I am still having the same issue.

**Comment by ferchaure** [comment]
check that all the files have a variable called **data** with the continuous recording

**Comment by YawRay** [comment]
Thank you for your response. It works now. My files contained a variable called "my_channel_1" instead of "data." After changing the name of the variable to "data" everything works now. Thank you very much!
