### ISSUE TITLE
Analysed spikes

### ISSUE THREAD

**Issue by YawRay** [csn-le/wave_clus#127]
Hi,

I have a question about the new wave_clus. You wrote that "A cross symbol (‘x’) will be shown on the clusters already analysed." What exactly does this mean? I am asking because, even after doing the clustering, clicking the force button in the GUI, and merging clusters, I only see one x symbol, which means that the other clusters have some of their spikes in one of the selected clusters at higher temperatures. How do I make sure that none of the spikes in the other clusters belong to other clusters? How do I analyse the remaining clusters or how do I get the 'x' symbol for all clusters in the temperature plot?

**Comment by ferchaure** [comment]
> What exactly does this mean?
The  cross symbol (‘x’) is related only to the automatic result. It's a way to tell you that that some peaks in the temperature map aren't selected automatically because some of their spikes are in clusters that the automatic clustering already selected. 

> How do I make sure that none of the spikes in the other clusters belong to other clusters?
That will never happen
