### ISSUE TITLE
Unpredictable Segmentation Fault

### ISSUE THREAD

**Issue by JGMcP** [csn-le/wave_clus#128]
Hello,

wave_clus 3 typically runs seamlessly on our multi-electrode array data using the batch scripts. However, from time to time, data from individual electrodes within the array will encounter a segmentation fault error during interaction with the SPC routine. When this occurs, Matlab yields the following message:

/cluster_maci.exe data_wc.run: Segmentation fault

SPC v2.1 (14/2/2000) -- efficient KNN and mstree
SPC v2.0.1 (1/12/2000) -- StopRunAtBreak option 
SPC v2.0 (1/11/1999) -- new param file + revised data structures 
---------------------------------------------------------------------

We have not been able to identify anything different about the data on these electrodes relative to other electrodes on the micro-electrode array (which do not cause a segmentation fault). This makes the error quite unpredictable and challenging to work around during batch processing. For what it's worth, Get_spikes() executes without incident even on electrodes that encounter this error during Do_clustering() and run_cluster. 

We are running wave_clus 3 (re-downloaded this week), but have also experienced the issue with previous versions. We use 64bit Macbook Pro's running OSX 10.14.5; the error persists with Matlab r2017a - r2018b. 

Any insights would be most appreciated! 

Thanks,
- Jacob

**Comment by ferchaure** [comment]
Hi Jacob, sorry about that, probably an incompatibility of the SPC executable file for mac. But we don't have the source code. If you can contact and ask Eytan Domany for the code, probably you could compile it and fix the issue.

**Comment by JGMcP** [comment]
Hi Fernando,

Thanks for the reply. I was also converging on it being a Mac and source code-related issue. I’ll reach out to them to see if they have any ideas/suggestions.

For what it’s worth, I have noticed that if I reduce the max number of spikes before template matching in set_parameters from the default 20K down to something < ~10K, I seem to avoid the error. But it remains enigmatic because the specific spike-number threshold required to avoid the error differs from electrode to electrode (For some it will run at 20K, others 10K, others not until 7K).

Best,
- Jacob


On Jun 21, 2019, at 8:59 AM, Fernando J. Chaure <notifications@github.com<mailto:notifications@github.com>> wrote:


Hi Jacob, sorry about that, probably an incompatibility of the SPC executable file for mac. But we don't have the source code. If you can contact and ask Eytan Domany for the code, probably you could compile it and fix the issue.
