### ISSUE TITLE
Need a help; how should I prepare my data for Wave_clus?

### ISSUE THREAD

**Issue by kouichi-c-nakamura** [csn-le/wave_clus#129]
Hi,

I'm very new to `wave_clus`, so it's highly likely that I'm missing something really basic, but it seems that I need help to get it to work.

Looking at [README.md](https://github.com/csn-le/wave_clus/blob/master/README.md) and [Input Files](https://github.com/csn-le/wave_clus/wiki/Input-Files), I prepared MATLAB files named `xxxx_spikes.mat`, each of which contains two variables, `data`, which holds the waveform data of the unit channel, and `sr`, which represents the sampling rate of that channel.

I wanted to use `Get_spikes('filename')` and then `Do_clustering('filename')`. But when I'm running `Get_spikes(matfilenames)`, where `matfilenames` is a cell array vector of those `xxxx_spikes.mat` file names, the `readInData` class constructor issues a warning that says `Warning: Coultn't find spikes variable in '_spikes' file`, and it fails (the program is essentially interrupted without issueing an error). 

But I think this is odd because the documetation says:

> It should have either a vector named **data** (the continuous signal) or a matrix named **spikes** (nr. of spikes x length of the spike shape) plus a vector **index** with the spike times (in ms).

My understanding is that the `spikes` variable is not mandatory. Because the task of `Get_spikes` is to detect spikes in the data, it is also odd that it assumes the existence of previously detected spikes in the `spikes` variable.

Can someone tell me exactly how I need to prepare my data to use `wave_clus`, please? 

Perhaos either `README.md` or the Wiki can be improved for clarity?

Best regards,
Kouichi

**Comment by ferchaure** [comment]
> Looking at README.md and Input Files, I prepared MATLAB files named xxxx_spikes.mat, each of which contains two variables, data, which holds the waveform data of the unit channel, and sr, which represents the sampling rate of that channel.

That is the issue the file name of the raw data is without the '_spikes.mat'. That is the problem, wave_clus take that name as a file already processed using Get_spikes

You are totally right about all the following

**Comment by kouichi-c-nakamura** [comment]
Oh, thanks!

Kouichi

**Comment by kouichi-c-nakamura** [comment]
Thanks to the help, I got Wave_clus working and now I'm inspecting the outcome.

I think that either the [README.md](https://github.com/csn-le/wave_clus/blob/master/README.md) may need more clarification.

The following works well for MATLAB files. But how does `Get_spikes` work for other file types such as Intan? It creates `filename_spikes.mat` anyway? Looking at the source code of `Do_clustering`, it seems that it only takes `filename_spikes.mat`

---

To open the GUI, type `wave_clus` in the MATLAB command prompt. 

To use the batch functions, type `Get_spikes('filename.ext')` (`.ext` is a file extention, eg. `.mat`) to do the spike detection; this will save a file `filename_spikes.mat` in the current directory. Then, run `Do_clustering('filename_spikes.mat')` to do the sorting.

As to the format of the input files, see [the Wiki page for Input Files](https://github.com/csn-le/wave_clus/wiki/Input-Files).

**Comment by ferchaure** [comment]
For intan you could see the file https://github.com/csn-le/wave_clus/blob/master/tools/parse_data_int.m to convert your intan file in raw single channel files that Get_spikes can load directly.

**Comment by kouichi-c-nakamura** [comment]
Because I have no Intan files or no plan to handle them, I'm just talking about the syntax written in the README.md or the comments in the `Get_spikes.m`, because I found them confusing.

1. The current README reads like you can do `Get_spikes('filename.ext')` for whatever data format that is supported. Is this true or false?

2. If yes, and if you run `Get_spikes('filename.ext')` for Intan files, for example, do you get the same `filename_spikes.mat` file anyway that can be processed by `Do_clustering`? YES or NO?

**Comment by ferchaure** [comment]
1. Yes, but some of them need to be parsed before using the codes in the tools folder
2 Yes

**Comment by kouichi-c-nakamura** [comment]
I made a Pull Request about this: https://github.com/csn-le/wave_clus/pull/130

**Comment by ferchaure** [comment]
nice!, thank you
