### ISSUE TITLE
implement Wave_Clus in SpikeInterface

### ISSUE THREAD

**Issue by alejoe91** [csn-le/wave_clus#133]
Hi Wave_Clus team!

We wanted to ask you if you can implement Wave_Clus in the SpikeInterface project (https://github.com/SpikeInterface), which is the engine behind SpikeForest.

With @magland we are merging the SpikeForest and SpikeInterface implementation, so that SpikeForest will call the SpikeInterface sorter wrappers, which will only be maintained in one place.

The sorter wrappers are in this repo: https://github.com/SpikeInterface/spikesorters and I made an issue for the Wave_Clus implementation where we can discuss the details (https://github.com/SpikeInterface/spikesorters/issues/13).

Please let us know how we can help for the implementation. There should be plenty of examples among the other implemented wrappers. The matlab ones are kilosort, kilosort2, and ironclust.

Cheers
Alessio & the SpikeInterface Team

**Comment by ferchaure** [comment]
Hi Alessio

Probably I will need a bit of time to code the wrapper, but we really like the SpikeForest/SpikeInterface projects and we are glad to help.

**Comment by magland** [comment]
Here's wrapper that James Jun wrote: https://github.com/flatironinstitute/spikeforest/blob/master/spikeforest/spikesorters/waveclus/waveclus.py

@alejoe91 ... do we just need to port this over like the others?

(not sure how complete it is)

**Comment by ferchaure** [comment]
James made a nice work. But he didn't add support for polytrodes (wave_clus can handle ones with a few channels). I don't know what is the best way to collaborate. Should I complete his wrapper and that will be easier to port for the spikeinterface team?

**Comment by magland** [comment]
@ferchaure. I think that would make the most sense. We're pretty quick at moving it over to spiketoolkit now.

**Comment by ferchaure** [comment]
I have been expanding the wrapper but I have a few questions:
- Detection polarity: James changed the polarity of the input signal, probably because he didn't want to change the default parameters. I guess that I should ask @magland  to change the parameters used for the datasets and leave the signal as it is.
- Geometry: waveclus doesn't have a proper way to handle MEAs but it can be used when the electrodes are separated in little groups. is it possible to input that type of metadata somewhere and check if it is available?
- Related to the previous question: Is there a type of flag or something to check is some algorithm can handle or not each type of data?

**Comment by alejoe91** [comment]
Hi @ferchaure 

> * Detection polarity: James changed the polarity of the input signal, probably because he didn't want to change the default parameters. I guess that I should ask @magland  to change the parameters used for the datasets and leave the signal as it is.

I agree it's better to change the default parameter instead. We could start porting the spikeforest wrapper to the spikesorters repo and make the changes there.

> * Geometry: waveclus doesn't have a proper way to handle MEAs but it can be used when the electrodes are separated in little groups. is it possible to input that type of metadata somewhere and check if it is available?

YES! `RecordingExtractor` can load the `group` property of each channel either from a probe file (.prb) or with the `set_channel_property()` function. This allow:

- to run spike sorting separately by group (handled by spiketoolkit) 
`sorting = st.sorters.run_mountainsort4(recording, grouping_property='group')`

- or to use the group information in the wrapper (see [here](https://github.com/SpikeInterface/spikesorters/blob/master/spikesorters/kilosort2/kilosort2.py#L156-L159) for example)

To retrieve all channel_groups you can use: `recording.get_channel_groups()`

> * Related to the previous question: Is there a type of flag or something to check is some algorithm can handle or not each type of data?

If you mean to check if a recording has a property, you can do:

```
if 'group' in recording.get_channel_property_names():
    do something
```

Let me know if you have other questions

**Comment by ferchaure** [comment]
> We could start porting the spikeforest wrapper to the spikesorters repo and make the changes there.

Probably is the simplest way, I don't know which functions of spikeforest will be changed. I improved a bit the wrapper and just did a pull request on spikeforest. I guess that my next pull request will be directly to spikeinterface.

> If you mean to check if a recording has a property, you can do:

Nice, and then the wrapper has a way to stop or at leas give a warning when the parameters/recording are sub-optimal ? (i.e. a lot of electrodes without grouping will be a mess for waveclus)

**Comment by magland** [comment]
@ferchaure. See my comment on your pull request: https://github.com/flatironinstitute/spikeforest/pull/64

I will test in spikeforest and then begin to port over to spikeinterface/spikesorters and then we can continue over here.
