### ISSUE TITLE
Wave_clus ingored the largest and cleanest unit in a file

### ISSUE THREAD

**Issue by kouichi-c-nakamura** [csn-le/wave_clus#134]
Hi,

I ran batch mode with the default parameters for my silicon probe data. But the results weren't satisfactory; in particular, for one channel, which has a unit with a great signal-to-noise ratio, ideal for manual spike sorting, Wave_clus somehow ignored the largest and clean unit entirely.

This is the result of Wave_clus automatic spike sorting shown in Spike2. The large amplitude unit in the bottom channel is completely missing in the top channel for sorted units; only much smaller ones were counted.

![Image012](https://user-images.githubusercontent.com/6400352/60351976-cafe2500-99be-11e9-8939-df763768c4aa.png)

Now I'm trying to get better results by using GUI and changing parameters. But so far I haven't managed to see the large unit as a cluster in the GUI. Maybe I'm overlooking some very basic parameters. My best bet was `par.stdmax`, but even with 20-times bigger value, the large unit was still ignored.

```
par.stdmax = 1000;                     % maximum threshold for detection                                                                     
```

Can someone give me an advice?

Best,
Kouichi

**Comment by ferchaure** [comment]
Remember that you have to do the detection again if you change the par.stdmax. It could be really odd but maybe they are overlapping spikes and Wave_clus cant handle them. 
Can yo upload a few seconds to check the data? 

It looks like the yellow and green lines are aligned to the clear spikes.

**Comment by kouichi-c-nakamura** [comment]
Well spotted! Looks like the high-pass (300 Hz) filtering-derived artifacts (small ripples) before and after the large spikes are treated as units and because of the close proximity, the large spikes were ignored.

I have to say I'm not good at degital filtering, but this kind of artefacts are inevitable to some extent, right?

![Image002](https://user-images.githubusercontent.com/6400352/60355730-03096600-99c7-11e9-8d4d-568ca4e9d431.png)

**Comment by ferchaure** [comment]
well done, that was a tricky one. You could reduce the order of the detection filter. The usual parameter is quite useful when we have a lot of noise but in your case I think it will be fine use _par.detect_order = 2_

**Comment by kouichi-c-nakamura** [comment]
In case you still want to have a go:

10 seconds of data
https://unioxfordnexus-my.sharepoint.com/:u:/g/personal/phar0528_ox_ac_uk/EeUeaB4LLIdJmwmOsMgxswkB4q9kZKsoJ2aM1UF-prhVOQ?e=jaH5aW

I'll try the parameter suggested soon. Thanks. Have a good weekend.

Best,
Kouichi

**Comment by kouichi-c-nakamura** [comment]
`par.detect_order = 2` instead of `4` does not seem working.

One of the problems here is that the threshold is too low and is accepting too many noise-level events as spikes. 

```matlab
par.stdmin = 5;                      % minimum threshold for detection                                                                      
                                                                                                                                              
par.stdmax = 50;                     % maximum threshold for detection  
```

I suspect that if I set `par.stdmin` high enough to ignore most of noises, and `par.stdmax ` low enough to include the larege unit, then it might work.

What is the order of magnitude of these parameteres?

Are they defining the threshold as an integer multiple of standard deviations? eg. '5' means '5 SDs'?

On a related note, what is the red horizontal line in the top panel of GUI? Is it an SD (is seems too low fo that)? Maybe 2*SDs?

**Comment by ferchaure** [comment]
The magnitudes of the parameters are usually that ones, stdmin could be 4 up to 5. And stdmax depends of the noise and spikes but it could go up to 200, in some specific cases. 


Yes the threshold is an integer multiple of standard deviations. The red dot is the real threshold used for detection. Do you have missing data of a lot of ceros in you signal? Something is wrong

**Comment by ferchaure** [comment]
The magnitudes of the parameters are usually that ones, stdmin could be 4 up to 5. And stdmax depends of the noise and spikes but it could go up to 200, in some specific cases. 


Yes the threshold is an integer multiple of standard deviations. The red dot is the real threshold used for detection. Do you have missing data of a lot of ceros in you signal? Something is wrong

**Comment by kouichi-c-nakamura** [comment]
Sorry, but let me repeat the question above with a screenshot.

> what is the red horizontal line in the top panel of GUI? Is it an SD (is seems too low for that)? Maybe 2*SDs?

The red horizontal line that I'm talking about is indicated by large red arrow:

![Image011](https://user-images.githubusercontent.com/6400352/60600633-6b31c080-9da8-11e9-95e9-bc41d5b6b1aa.png)

I doublechecked the data, but it's just continuous signal in double type.

In this plot, the blue line is the same data and red line is the 2*SD of the data.

![Image013](https://user-images.githubusercontent.com/6400352/60601908-c9f83980-9daa-11e9-91ed-bb470f800988.png)

I'd assume using `par.stdmin = 10` would remove lots of noise-level units, whereas `par.stdmax = 100`  (SD *100 = ~2.07) should be big enough to keep the large units. Even with this (after re-loading data), I still can't see the large units detected by wave_clus.

**Comment by ferchaure** [comment]
Yes, that red line is the threshold. Remember that it calculated using the median of the absolute value of the signal, and could be quite smaller that the std from the raw signal. Probably you should use a higher value of stdmax. Probably you have a neuron really really close to the electrode.
