### ISSUE TITLE
No temperature in wave_clus

### ISSUE THREAD

**Issue by sllevy2828** [csn-le/wave_clus#136]
I'm using wave_clus for the first time and am not able to see anything in the temperature graph on the gui with my data. I've checked that the temperature settings are still at the default. I also tried loading the simulated data - screenshot below:
![No temperature](https://user-images.githubusercontent.com/53315257/61902257-7f17a080-aed6-11e9-968e-a83c3cae191a.PNG)

There error in the screenshot pops up after I attempt to select a new temperature (even though the graph is not populated).

Are there any toolboxes or functions that I might be missing?

Thanks.

**Comment by ferchaure** [comment]
Do you remove the two temporary files that wave_clus create in the folder? (or maybe matlab doesn't have permissions to write in that place)

**Comment by sllevy2828** [comment]
After I have loaded the data via the wave clus gui, I don't see any temporary or new files created in the folder. MATLAB should have write permission to the folder. 
![image](https://user-images.githubusercontent.com/53315257/61978106-2d8a1700-afa5-11e9-83b2-a3211c36b6b0.png)

What are the temporary files usually called?

**Comment by ferchaure** [comment]
the 'data_' files are the temporal ones. Do this: copy the raw data you want to sort to another folder and run wave_clus there. It may be that wave_clus found an older solution in that folder and it is trying to load it.

**Comment by sllevy2828** [comment]
Thanks for the quick response. 

I initially had run wave_clus on new data in an unpopulated folder w/ no existing solution which is when I didn't see any temperature variables. 

But just to verify, I also just created a new folder, and moved the sample data's times_CSC.mat file (downloaded from the website) into that folder, re-ran wave clus. There's still no temperature visible in the plot. 

Does wave_clus require any particular external functions to run?

**Comment by ferchaure** [comment]
the file times_CSC.mat is a solution file (without temperature map) for that reason you can't see a temperature map. In that old recording the file Ncs is the raw data, but the format is quite old and not supported. The easy way to fix that is renaming the file times_CSC.mat  to CSCaux_spikes.mat, doing that wave_clus (it detects any XXX_spikes.mat file as a detected spikes files) will recalculate a times for it.

**Comment by sllevy2828** [comment]
I see. I tried this and ran into the error "Undefined function or variable 'index'." Since I was only running the simulation data to make sure I have the workflow running, I switched back over to my actual data. 

The data (a .ns6 blackrock file) has been pre-processed and I have the CSC#_spikes.mat file, which contains a spikes matrix and a time index matrix. It does not contain a sampling rate, so for now, I'd like to use the default parameters.

Error when I loaded the CSC#_spikes.mat via the wave_clus gui:

Reference to non-existent field 'par'.
Error in wave_features (line 4)
scales = handles.par.scales;
Error in wave_clus>load_data_button_Callback (line 234)
    [inspk] = wave_features(spikes,handles.par);                 %Extract spike features.
Error in gui_mainfcn (line 95)
        feval(varargin{:});
Error in wave_clus (line 63)
    gui_mainfcn(gui_State, varargin{:}); 
Error while evaluating UIControl Callback

**Comment by ferchaure** [comment]
> I see. I tried this and ran into the error "Undefined function or variable 'index'." Since I was only running the simulation data to make sure I have the workflow running, I switched back over to my actual data.

My bad, I forgot how to tell you that you have to add the spikes times (in a variable called index) from that old times file as well. In tht recording, the index of the spikes are probably inside the variable cluser_class.

> Error when I loaded the CSC#_spikes.mat via the wave_clus gui:
Reference to non-existent field 'par'.

Are you using the current version of wave_clus from this repo? That error looks like from an older version. 

Notice that you don't need to call the file like that. Adding the _spikes, is a way to tell wave_clus that you used the function Get_spikes to do the filtering and detection of spikes.

**Comment by sllevy2828** [comment]
Yes, I am using the latest version from this repo (I downloaded the wave_clus file from the github). 

> > Error when I loaded the CSC#_spikes.mat via the wave_clus gui:
> > Reference to non-existent field 'par'.
> 
> Are you using the current version of wave_clus from this repo? That error looks like from an older version.

Which file should I load in through the gui? The output of my preprocessing scripts (from someone else in the lab) are CSC#_spikes and CSC#. Loading both of these files leads to the same error about sampling rate:
"Wave_clus didn't find a sampling rate in file. It will use the input parameter or set_parameters.m" with the error from above. 
> Notice that you don't need to call the file like that. Adding the _spikes, is a way to tell wave_clus that you used the function Get_spikes to do the filtering and detection of spikes.

**Comment by ferchaure** [comment]
> Yes, I am using the latest version from this repo (I downloaded the wave_clus file from the github).

Sorry but the lines I can see from the error aren't from the current code (https://github.com/csn-le/wave_clus/archive/master.zip)


> "Wave_clus didn't find a sampling rate in file. It will use the input parameter or set_parameters.m"
That is just a warning that wave_clus couldn't load the sampling rate directly from the raw data.
I can't check the error because the code you are using is from a unknown version.

**Comment by sllevy2828** [comment]
Ah! It now works. Although I had deleted the older versions of wave clus that I found in Matlab's path, there must have been some older functions of wave clus interfering because when I moved the newest wave clus folder to the top of the path - it now runs smoothly and creates the temperature maps.

Thank you for your patience and help!
