### ISSUE TITLE
Odd error when interacting with SPC

### ISSUE THREAD

**Issue by aboharbf** [csn-le/wave_clus#137]
I got the error below for a seemingly normal file

```
SPC v2.1 (14/2/2000) -- efficient KNN and mstree                     
SPC v2.0.1 (1/12/2000) -- StopRunAtBreak option                      
SPC v2.0 (1/11/1999) -- new param file + revised data structures     
-------------------------------------------------------------------

error:
at line 233 of 'param.c': N<=0
```

I ran this in a large loop with many similar files, yet this is the only one which yielded this result. even among files collecting immediately before and after this one. a little digging around shows that at the top of the 'run_cluster' code, when the tmp file is loaded, 
```
dat = load(par.fname_in); %Don't add path here, it needs to be added before.
n = length(dat);
fid = fopen(sprintf('%s.run',[par.file_path filesep fname]),'wt');
```
dat comes up 0*0, empty. despire the fact the _spikes file has spikes in it. Any thoughts?

**Comment by ferchaure** [comment]
I haven't see something like that. How many spikes do you have ?
