### ISSUE TITLE
Data problems

### ISSUE THREAD

**Issue by Jie369** [csn-le/wave_clus#138]
Firstly, thanks for providing this great toolbox!!!

I have some problem on the begining stage.Sorry I am new guy in this field so maybe I asked many silly questions. Any help will be appreciated! I tried to modify par.stdmin according to the original problem, but there was still an error, the error is as follows:

Wave_clus didn't find a sampling rate in file. It will use the set in set_parameters.m
Error using wave_clus>load_data_button_Callback (line 230)
Less than 15 spikes detected

Error in wave_clus>wave_clus_OpeningFcn (line 107)
      load_data_button_Callback('w_arg',varargin{1},handles)

Error in gui_mainfcn (line 220)
    feval(gui_State.gui_OpeningFcn, gui_hFigure, [], guidata(gui_hFigure), varargin{:});

Error in wave_clus (line 63)
    gui_mainfcn(gui_State, varargin{:}); wave_clus>load_data_button_Callback (line 230)
Less than 15 spikes detected

Error in wave_clus>wave_clus_OpeningFcn (line 107)
      load_data_button_Callback('w_arg',varargin{1},handles)

Error in gui_mainfcn (line 220)
    feval(gui_State.gui_OpeningFcn, gui_hFigure, [], guidata(gui_hFigure), varargin{:});

Error in wave_clus (line 63)
    gui_mainfcn(gui_State, varargin{:});

In addition, I also found that the parameter of wave_clus data_handler.max_segments is 0.

**Comment by ferchaure** [comment]
Hi, it looks like an issue loading the data. Tell me more about the type of data, the file, etc. It was a good call to change stdmin, another fast check is the detection polarity, you can try with 'both' and when the issue is fixed change it to the polarity of the spikes.

**Comment by Jie369** [comment]
[matlab.zip](https://github.com/csn-le/wave_clus/files/3454825/matlab.zip)
ok,ok ,thank you!!!!!

**Comment by Jie369** [comment]
Hello, I have another question about signal segmentation.I see segments before amplitude detection, which my data don't go through.Does fragmentation affect results?x = obj.file_reader.get_segment(obj.n_to_read);Is there a specific function definition for get_segment ()?Thank you very much for answering my question!!!

**Comment by ferchaure** [comment]
> Does fragmentation affect results?

In some specific cases could affect. For example if want to use the exactly the same threshold for all the data (even in intervals with a high noise level), in that case you should use only one segment.

> Is there a specific function definition for get_segment ()?

yes, check your data type in the folder Raw_data_readers, for example if you are loading a mat file check mat_wc_reader.m.

**Comment by Jie369** [comment]
So is our threshold the whole threshold?Why do we want to segment?

**Comment by Jie369** [comment]
Here's my data
[matlab.zip](https://github.com/csn-le/wave_clus/files/3464460/matlab.zip)

**Comment by Jie369** [comment]
Hi, sorry to interrupt.
What is the function of w_pre and w_post.Thank you very much!!!!

**Comment by ferchaure** [comment]
Each spike is aligned with the peak in the sample w_pre and then w_post more samples.
