### ISSUE TITLE
extracting thresholds from sorted data

### ISSUE THREAD

**Issue by dragospekic** [csn-le/wave_clus#139]
Could you please let me know if I can extract the detection threshold from already sorted data.
Thanks!
Todor

**Comment by ferchaure** [comment]
yes, that info is inside the **XX_spikes.mat** file (the output of the Get_spikes batch file).

**Comment by dragospekic** [comment]
not sure how to get that out. for me this contains a matrix of all the
waveforms aligned on the waveform min and a vector called 'index'. However
i would like that aligned on when the threshold was crossed (not the
waveform min)...  Thanks! Todor

**Comment by ferchaure** [comment]
That file should contains a **thresholds** variable with the values used for the detection. 
Are you using the last version of the code?

**Comment by dragospekic** [comment]
unfortunately not, I am trying to reanalyze some older sorted data. how
about cluster_results.txt:
"data wav 0.15 3 5 983 13372 4116 1495"?
or data_sp_th.mat500
the latter is a binary which I cannot read unfortunately but the name
sounds like it might contain threshold information ; )
Thanks a lot!
Todor

**Comment by ferchaure** [comment]
> "data wav 0.15 3 5 983 13372 4116 1495"?
From that line you could say that a par.stdmin= 5 was use. The value in 'Volts' wasn't save, If you used the same filter for detection and  sorting, you could get the value as (and if you used a negative threshold ):
`min(spikes(:,par.w_pre))`

**Comment by aboharbf** [comment]
Can I recommend that this variable be passed to the 'times' files produces when the spikes files are put into Do_clustering? 

I use it for some post processing after do_clustering, but occasionally want to use the GUI where I think more manual curation is needed. In cases where the GUI is used, the end result doesn't have any trace of the threshold.

**Comment by ferchaure** [comment]
Sorry I can't do that, the variables have to be as simple as possible. But in any case you could load the thresholds from the spikes file and add them to the times file just after calling Do_clustering. Remember that you can easy add variables to a mat file with:  `save('times_filename.mat',thresholds,'-append')`
