### ISSUE TITLE
Do_clustering Batch Files

### ISSUE THREAD

**Issue by eschuma** [csn-le/wave_clus#14]
I have a .txt file containing the filenames:
nless_spikes.mat
test_spikes.mat

When using Do_clustering('File.txt'), I keep getting this error message regardless of what I do:
Error using readInData (line 124)
Reference to non-existent field 'ref_ms'.

This value is par.ref_ms is present in set_parameters. Are they loaded automatically or do I need to load them prior to batch clustering?
Thank you for your help!

**Comment by ferchaure** [comment]
That's quite odd, and shouldn't happen. 
Are those spike files created using Get_spikes? If they aren't, try to use another names. 
Are you using the last update from a few days ago?
Did you change something in readInData? Because that line is executed only if the field 'ref_ms' exists

**Comment by eschuma** [comment]
The files are not from get_spikes. I got the spikes from a different program and formatted them in the .mat files with index of times, sr for sampling rate, and a matrix spikes containing the spike data. I have tried changing the names, but I still cannot get it to work properly. 
I will try the new update. I had been using the previous one. But I did not change anything in readinData.

**Comment by eschuma** [comment]
It is working with the new update. Thank you for the help!
