### ISSUE TITLE
Detection Parameters

### ISSUE THREAD

**Issue by aswinchari** [csn-le/wave_clus#140]

**Comment by aswinchari** [comment]
Hi,

I'm trying to use Waveclus via the Brainstorm interface for human microelectrode recordings and had a few questions:

- Detection thresholds: What are the usual thresholds for spike detection? The default is 5SD but is that realistic with human data? Do you have an idea of what thresholds people usually use?

- Detection parameters: Should they be negative or is it ok to select both? 

- In your experience with human data, what portion of channels actually detect spikes?

Thanks,
Aswin

**Comment by ferchaure** [comment]
> Detection thresholds: What are the usual thresholds for spike detection? The default is 5SD but is that realistic with human data? Do you have an idea of what thresholds people usually use?

Usually a value of 3.5 to 4.5 is used in humans, but it could change a lot... as the quality of the record.

> Detection parameters: Should they be negative or is it ok to select both?

The best practice is use 'both' first, check the results and then use 'neg' or 'pos'. The alignment of the spikes is quite better if you use pos or neg. If you have both types of polarity, sometimes the best is to make two sorting, with each polarity. 

> In your experience with human data, what portion of channels actually detect spikes?

That could change a lot with the region of the brain and the quality and the hand of the surgeon. Probably you have to look for bibliography close enough to your recordings to check

**Comment by aswinchari** [comment]
Awesome. Thank you Fernando.

This is one of my channels and, changing the thresholds to 4SD and 'both', it has given me this. I am recording at 16kHz - do you think these looks like APs? I am not convinced, both by their shape and the ISI histograms. Would you have an example of what one is meant to look like?

Thanks,
Aswin

<img width="1183" alt="Screenshot 2019-08-16 at 14 22 57" src="https://user-images.githubusercontent.com/50949664/63170524-5c8a2a80-c031-11e9-8c18-01b3b07fc754.png">

**Comment by ferchaure** [comment]
Hi Aswin, 
They don't look like AP, just noise filtered and aligned. Please notice that 16kHz is quite low for a decent spike sorting. Probably you will have to change the parameters w_pre and w_post to 12 and 20. Otherwise you are taking a lot of non AP waveform to the signal segment to sort.
