### ISSUE TITLE
Throws "Reference to non-existent field 'nbins21' " error when plotting via GUI

### ISSUE THREAD

**Issue by sevgiozturk** [csn-le/wave_clus#144]
Hi, I continue to sort spikes from behaving animal. I get this error for a channel data! It generated this error when par.max_clus = 20. When I change it to default(par.max_clus = 200), it generates no error. I just try to decrease clusters but I think max_clus = 20 causes some field not created in gui!

Reference to non-existent field 'nbins21'.

Error in wave_clus_aux3>wave_clus_aux3_OutputFcn (line 94)
	eval(['set(handles.isi' si '_nbins,''string'',par.nbins' si ');']);

Error in gui_mainfcn (line 262)
        [varargout{1:nargout}] = feval(gui_State.gui_OutputFcn, gui_hFigure, [], gui_Handles);

Error in wave_clus_aux3 (line 38)
    [varargout{1:nargout}] = gui_mainfcn(gui_State, varargin{:});

Error in plot_spikes (line 360)
                opened_figs{4} = wave_clus_aux3('Visible', 'off');

Error in wave_clus>load_data_button_Callback (line 405)
plot_spikes(handles); %This function edits userdata

Error in gui_mainfcn (line 95)
        feval(varargin{:});

Error in wave_clus (line 63)
    gui_mainfcn(gui_State, varargin{:});
 
Error while evaluating UIControl Callback.

**Comment by ferchaure** [comment]
You are right, I will fix this

**Comment by sevgiozturk** [comment]
Thanks for this super quick fix :)
