### ISSUE TITLE
GUI Interface w/ multiple figures

### ISSUE THREAD

**Issue by aboharbf** [csn-le/wave_clus#146]
Running into error when trying to load a data which requires 2 GUI figures be generated.

```
Reference to non-existent field 'bin_step6'.

Error in wave_clus_aux>wave_clus_aux_OutputFcn (line 97)
	eval(['set(handles.isi' si '_bin_step,''string'',par.bin_step' si ');']);

Error in gui_mainfcn (line 262)
        [varargout{1:nargout}] = feval(gui_State.gui_OutputFcn, gui_hFigure, [],
        gui_Handles);

Error in wave_clus_aux (line 36)
    [varargout{1:nargout}] = gui_mainfcn(gui_State, varargin{:});

Error in plot_spikes (line 353)
                opened_figs{1} = wave_clus_aux('Visible', 'off');

Error in wave_clus>load_data_button_Callback (line 484)
plot_spikes(handles); %This function edits userdata

Error in gui_mainfcn (line 95)
        feval(varargin{:});

Error in wave_clus (line 63)
    gui_mainfcn(gui_State, varargin{:});
```

I realize this is unlikely to be an issue with the package as it came, and more likely a result of changes I've made. In particular, I've done the following
1. Modified both the GUI version and the batch files to not change the directory (mostly by modifying paths where files are saved and looked for where appropriate). This is particularly important for parallel processing.
2. Created a parameter 'clusThr' which allows for a threshold on spikes used to cluster (we've discussed it before in a previous issue, you suggested an alternative which may be easier to implement, but at the current point I also added a 'spike Index' so I was certain that spikes were sorted and unsorted correctly.
3. Threshold saving - I added 'threshold' to the parameter file, though it seems you've added this in the _spikes file recently, and I need to see if I can get rid of this to bring things more in like with your version.

I don't see how any of the above changes could have caused the issue I'm having now. Any insights into nbins generation and how this might have been caused by my changes would be great. This issue doesn't happen in the batch file version of the pipeline, but will happen even just opening previously sorted data.

**Comment by aboharbf** [comment]
So in a weird turn of events, simply defining a few more of the missing bin values is adequate to fix the problem:

```
par.nbins6 = 100;
par.bin_step6 = 1;
par.nbins7 = 100;
par.bin_step7 = 1;
par.nbins8 = 100;
par.bin_step8 = 1;

for i = 4:8
	si = num2str(i);
	set(eval(['handles.isi' si '_accept_button']),'value',1);
	set(eval(['handles.isi' si '_reject_button']),'value',0);
	set(eval(['handles.fix' si '_button']),'value',0);
	
	eval(['set(handles.isi' si '_nbins,''string'',par.nbins' si ');']);
	eval(['set(handles.isi' si '_bin_step,''string'',par.bin_step' si ');']);
	
end
```

Naturally not an ideal solution, so I would like to know how I can fix this correctly if possible.

**Comment by ferchaure** [comment]
I don't know in which version are you working, but at least now I do all that definitions up to the cluster 33 (the maximum amount of clusters ploted )

**Comment by aboharbf** [comment]
Oh, I must be using something quite old. Can you point me to the proper file for these definitions?

**Comment by ferchaure** [comment]
wave_clus.m

**Comment by aboharbf** [comment]
Didn't see this until after I deleted my comment, but I saw the loop shortly after asking. Thanks a lot!
