### ISSUE TITLE
find_temp returning 'temp' empty

### ISSUE THREAD

**Issue by aboharbf** [csn-le/wave_clus#147]
Using the GUI to sort a file leads to a temp of 0. leads to problem with subsequent problems with other variables. Not sure why. Link to processed file: https://1drv.ms/u/s!Ah7iCG_uriY8kuIpqTavzImAM9uicw?e=bQExw0

**Comment by ferchaure** [comment]
The minimum temperature can't be exactly 0 but a step higher.

**Comment by aboharbf** [comment]
Apologies - Not a temp of 0, but an empty temp vector. Any idea why?

**Comment by ferchaure** [comment]
can you give me more info?
current version? error in the command window? did you try using the bash? maybe you have a small amount of spikes
