### ISSUE TITLE
Can't change parameters within the script

### ISSUE THREAD

**Issue by AnnaK42** [csn-le/wave_clus#149]
I know you're supposed to be able to save your waveform data along with the par structure, which should replace the parameter values in the set_parameters.m file for the clustering analysis, but it doesn't seem to work for me.

My general format of saving my data, then the sampling rate, and then the parameter values:

save('FileName.mat,'data','sr','par')

Get_spikes('FileName.mat);
load(strcat(['FileName.mat']));
Do_clustering('FileName.mat);

I have tried changing the par.stdmin value within the script itself but it never seems to work. It always pulls from the set_parameters.m file instead.

Am I missing something? 
Do you need every parameter to be in your par structure? 
I just have a par structure where par.stdmin = 3.5

**Comment by ferchaure** [comment]
HI AnnaK42 

The way to do that is explain in the Get_spikes.m file. If you want to change a detection parameter, you should run `Get_spikes('FileName.mat,'par',par);` 
The `par `structure is fine.
I don't understand why the line `load(strcat(['FileName.mat']));` is there.

**Comment by AnnaK42** [comment]
even when I try: 

save('FileName.mat,'data','sr','par')
Get_spikes('FileName.mat','par',par);
Do_clustering('FileName.mat');

Get_spikes is still only using the stdmin threshold from the set_parameters file, not the par.stdmin value that I set in par.

**Comment by AnnaK42** [comment]
I should probably also mention that I'm using an old version  of matlab - R2014a.

**Comment by AnnaK42** [comment]
Nevermind, seems to work now. I think I was using a threshold that was too high, so it just resorted back to the default set_parameters during the clustering (gave a warning). The par printout after Get_spikes seems to always be the default set_parameter values, which was confusing (and wasn't what was being used).

Thanks!
