### ISSUE TITLE
About simulate dataset

### ISSUE THREAD

**Issue by txgxp** [csn-le/wave_clus#15]
Hi! 
I am sorry to ask this question here. From your webpage you still provide the similated dataset to help us to understand the wave_clus tool. But I cannot understand the structure of simulated data. For example,  after loading mat. file,  the  spike_times providing in ground_truth can not be consistent with the peak value of raw data. So I am asking the spike_times providing in ground_truth represent the index of raw data or other else??

Thanks for your help....

**Comment by ferchaure** [comment]
The ground truth of the simulation gives the first sample of the simulated spikes, not the one with the peak value. The samples between first sample and peak depends of the neuron.

**Comment by txgxp** [comment]
Just following question, from the data  we cannot find the timecourse of the data, only sampling interval. So I am a little bit confused. Is It means that the time interval  between each data point is 0.0417 second ??

Thanks

**Comment by ferchaure** [comment]
sampling interval = 0.0417 ms
The sampling rate is approximately  24kHz
