### ISSUE TITLE
Spike alignment issue

### ISSUE THREAD

**Issue by yitongqi** [csn-le/wave_clus#150]
![Capture](https://user-images.githubusercontent.com/57579193/69183956-ec80ba00-0ae1-11ea-8bc3-d6387eaba3dc.PNG)

Issue shown in the figure above

sampling rate is 20kHz

Detection parameter used:
% DETECTION PARAMETERS 
par.tmax = 'all';                    % maximum time to load 
%par.tmax= 180;                      % maximum time to load (in sec) 
par.tmin= 0;                         % starting time for loading (in sec) 
par.w_pre = 20;                      % number of pre-event data points stored (default 20) 
par.w_post = 44;                     % number of post-event data points stored (default 44)) 
par.alignment_window = 20;           % number of points around the sample expected to be the maximum 
par.stdmin = 4;                      % minimum threshold for detection 
par.stdmax = 50;                     % maximum threshold for detection 
par.detect_fmin = 300;               % high pass filter for detection 
par.detect_fmax = 3000;              % low pass filter for detection (default 1000) 
par.detect_order = 4;                % filter order for detection 
par.sort_fmin = 300;                 % high pass filter for sorting 
par.sort_fmax = 3000;                % low pass filter for sorting (default 3000) 
par.sort_order = 2;                  % filter order for sorting 
par.ref_ms = 1.5;                    % detector dead time, minimum refractory period (in ms) 
par.detection = 'neg';               % type of threshold ('pos','neg','both')

**Comment by yitongqi** [comment]
![Capture2](https://user-images.githubusercontent.com/57579193/69185620-1b4c5f80-0ae5-11ea-8f04-5b7d6c43d857.PNG)
Above is a code snippet in the amp_detect.m file. As indicated in the figure, do you think that might be the reason?

**Comment by ferchaure** [comment]
The code is fine, Wave_clus can't handle overlapping spikes. A way to fix your issue is increasing par.alignment_window up to 35 (maybe)

**Comment by yitongqi** [comment]
Thanks, will try some work-around...
