### ISSUE TITLE
Problem to visualize "times_xxx.mat"

### ISSUE THREAD

**Issue by mndiguilmi** [csn-le/wave_clus#151]
Hi Fernando

I’m acquiring with Intan and before processing with Wave_class, I made a convertion to .mat. The clustering works OK and I can save it. The problem is to visualize these results once I try to do it a time later. I mean, when I load “times_xxx.mat” file with the Load Data option in the Wave_Clus GUI, sometimes clustering result can be displayed, but other times it is not possible, and the following message appeared:

///
 Reference to non-existent field 'fix34'.
Error in plot_spikes (line 120)
		eval(['fixx = par.fix' num2str(i) ';']);

Error in wave_clus>load_data_button_Callback (line 349)
plot_spikes(handles); %This function edits userdata

Error in gui_mainfcn (line 95)
        feval(varargin{:});

Error in wave_clus (line 63)
    gui_mainfcn(gui_State, varargin{:});
 
Error while evaluating UIControl Callback. 
///

Could you help me?
Thanks for your help 
Best
Mariano

![error](https://user-images.githubusercontent.com/26251722/69494969-63320480-0ea0-11ea-8ab7-ef4a8064d213.jpg)

**Comment by ferchaure** [comment]
Hi Mariano,

Download the last version from [master.zip](https://github.com/csn-le/wave_clus/archive/master.zip) . You have an old version of the code. Let me know if that works for you

**Comment by mndiguilmi** [comment]
Hi Fer
thank you so much! The last version worked perfect!
best
Mariano
