### ISSUE TITLE
Example database

### ISSUE THREAD

**Issue by yujiahuo1209** [csn-le/wave_clus#152]
Hello, 

I am wondering where I can download the sample data sets (simulator.zip) for this software? I tried to search them a lot. But it seems that the link online is expire.  Also from website 
https://www2.le.ac.uk/departments/engineering/research/bioengineering/neuroengineering-lab/software
I cannot find them. I would really like to have these data sets because lots of paper generated their results from them. 
If you can provide the access of them, I will be really appreciated. 

Thank you!

**Comment by ferchaure** [comment]
this ones?
[www2.le.ac.uk/centres/csn/software/linked-publications/unsupervised-spike-detection-and-sorting-with-wavelets-and-superparamagnetic-clustering](https://www2.le.ac.uk/centres/csn/software/linked-publications/unsupervised-spike-detection-and-sorting-with-wavelets-and-superparamagnetic-clustering)

**Comment by yujiahuo1209** [comment]
Thank you for your reply.
Yes. It is the data base for this paper. But in side this link, there is
only a paper in the zip file.

**Comment by ferchaure** [comment]
just to check, do you need the 95 simulations with a variable number of neurons or the ones called Difficult and Easy with different levels of noise?

**Comment by yujiahuo1209** [comment]
the ones called Difficult and Easy with different levels of noise. I think lots of paper for spike sorting are using this dataset.

**Comment by ferchaure** [comment]
https://drive.google.com/file/d/15U_cpEixrl3d71uy4yawfrpwDXJJ3U5c/view?usp=sharing

**Comment by yujiahuo1209** [comment]
Thank you so much! I really appropriated! That is really really helpful to our research!
