### ISSUE TITLE
GUI error

### ISSUE THREAD

**Issue by sv-bio** [csn-le/wave_clus#155]
Hello,

First of all I would like to thank you for the wave_clus. It works well in my hands but I have a couple of questions regarding its use:

1. My Matlab ver. 2009b (Debian 8.11). I can run Get_spikes and Do_clustering functions without an issue. However wave_clus one triggers the following error:

Error using ==> hqload at 53
Invalid figure file format

Newer versions seem to have no such problem. Header of *.fig file assumes that it should be compatible with Matlab 5.0 or newer. Could you give me a hint on what could be an issue?

2. After clustering is done, is there a way to take a close look at the clusters: i.e. choose individual cluster and browse through spike shapes/units it constitutes of, to make sure that clustering is correct and if not - move suspiciuous/mis-classified ones to other clusters?
Thank you in advance for reply,
Sincerely,
Stanislav

**Comment by ferchaure** [comment]
1. That is odd. That is all the error you got?
2. Yes, using the GUI (the command you can't run) is possible to open the _times_ file and check the waveforms.

**Comment by sv-bio** [comment]
The full error looks like:
??? Error using ==> hgload at 53
invalid Figure file format

Error in ==> openfig at 72
    [fig, savedvisible] = hgload(filename, struct('Visible','off'));

Error in ==> gui_mainfcn>local_openfig at 286
    gui_hFigure = openfig(name, singleton, visible);

Error in ==> gui_mainfcn at 159
        gui_hFigure = local_openfig(gui_State.gui_Name, gui_SingletonOpt, gui_Visible);

Error in ==> wave_clus at 63
    gui_mainfcn(gui_State, varargin{:});

**Comment by ferchaure** [comment]
It looks like a way to fix this is changing the format of the .fig files. [Here ](https://www.mathworks.com/matlabcentral/answers/305986-while-opening-a-figure-file-fig-in-matlab-i-get-an-error-error-using-open-at-159-invalid) is how

**Comment by sv-bio** [comment]
The issue with wave_clus is solved. Thanks!

As of question #2: when I open times_*.mat file in GUI, there are several figures, that show overlapping spikes that belong to clusters, cluster 0 (which represents noise) and the left-most figures with either spike shapes or features + temperature plot.
I can zoom in to a cluster and select data points, but I can not see corresponding spike shape and decide whether this spike was correctly clustered or not.
Or I can press "Manual" button and select a bunch of spikes in a plot of individual clusters to make them new cluster, but as bunch may contain hundreds of spike forms it is hard to see them one by one.
Alternatively temperature can be changed, but it only deals with the whole set of spikes.
Could you give me a hint on how to take a look at spikes' wave forms and if necessary, re-assign them to the other clusters right way?

Sincerely,
Stanislav

**Comment by ferchaure** [comment]
> I can not see corresponding spike shape and decide whether this spike was correctly clustered or not.

corresponding spike shape == mean spike shape (the black line) ?  If a spike is far away of the cluster you will see it, because you are seen all the cluster.

> Alternatively temperature can be changed, but it only deals with the whole set of spikes.

If you like a cluster, you can fix it using the checkbox below the cluster and it won't change that spikes after changing the temperature (the fixed clusters will get the higher class numbers).

> Could` you give me a hint on how to take a look at spikes' wave forms and if necessary, re-assign them to the other clusters right way?

Unforce the spikes helps a bit, check the clusters that now are smaller, fix the good clusters (always before change each time the temperature) and explore the small peaks in the temperature map and then for all the unsigned spikes again. If you can't find a proper peak in the temperature map use the manual selection (this works selecting all the spikes with a peak in the waveform inside the selection rectangle)

**Comment by sv-bio** [comment]
Thanks!
