### ISSUE TITLE
Overlapping Coefficient of Clusters

### ISSUE THREAD

**Issue by Einzelunit** [csn-le/wave_clus#156]
Hi,

I have two question about the correlation coefficient which decides about whether two clusters at two different temperatures are kept. In the default settings it seems to be set to k = 0.9.

1. Isn't that a very high value? Can two clusters with a spike-overlap of even 30% be considered as deriving from two different neurons?

2. When there is an overlap between two clusters, does Wave_clus sort those overlapping spikes into both of the clusters or does it assign each spike to one of the clusters? If it does assign them, to which of the two clusters?

Best wishes,

Tim

**Comment by ferchaure** [comment]
Hi Tim,

That coefficient is not a correlation is a overlapping coefficient. About the questions:
1. It's not a high value usually the value will be around 0.9. The value really doesn't change the results, usually the SPC is a quite strong hierarchical clustering.
2. The template at higher temperature has the priority in the selection.

**Comment by Einzelunit** [comment]
thank you very much!
