### ISSUE TITLE
Add a file that contain version inside the code

### ISSUE THREAD

**Issue by samuelgarcia** [csn-le/wave_clus#158]
Dear waveclust developers,
could it be possible to add a file inside sources like version.txt or even version.m
This file would contains a string with the official version of waveclust.

Since in spikeforest and spiekinterface we are running some benchmark, tracking the version is really important.

At the moment 
 ```python
spikesorters.print_sorter_version()
 ```
give 
```
herdingspikes: unknown
ironclust: 5.0.8
kilosort: unknown
kilosort2: unknown
klusta: 3.0.16
mountainsort4: unknown
spykingcircus: 0.9.0
tridesclous: 1.4.2
waveclust:  unknown
```

If a file inside source would have the version number it would be strithforward to parse and render the version.

Best,

Samuel

**Comment by samuelgarcia** [comment]
https://github.com/MouseLand/Kilosort2/issues/182

https://github.com/magland/ml_ms4alg/issues/22

https://github.com/flatironinstitute/ironclust/issues/39

**Comment by ferchaure** [comment]
done, let me know if you need help anything else

**Comment by samuelgarcia** [comment]
Thanks you this is very cool.

**Comment by samuelgarcia** [comment]
Integrated in spieinterface
https://github.com/SpikeInterface/spikesorters/pull/93/commits/e4357602a6e6e6edd108cd4eb9462fc8da5ceeae
