### ISSUE TITLE
Spike time (ms) after Do_clustering

### ISSUE THREAD

**Issue by seble2016** [csn-le/wave_clus#16]
Hello,

I am new to wave_clus and I was wondering if any of you could be of help.

I have recordings done by Neuralynx so I have a folder with .ncs files (e.g. CSC01.ncs). I used the following code to run the 'Get_spikes' and 'Do_clustering' m-files. As a proof that I have spikes detected, I wanted to get the time at which the detected spikes occurred and wanted to overlay them over my raw traces. I went to 'times_CSC01.mat' file that is saved already --> then opened 'cluster_class', where I got the clusters and the 'spike times' in millisecond (i.e. cluster_class (: , 2). 

The problem happens here as I keep getting values (time-stamps) larger than what is recorded as the last data in my original trace. Example: Last data point in raw file = 22, 063, 615 time-frames ; first spike recorded using wave_clus occurs at  = 119, 108, 528 time-frame.

N.B: 1 time-frame = sampling rate * 1 second

I made sure that the par.sr is set as 16000, which is the sampling rate recorded. Is there anything that I'm not doing right? I can't seem to bypass this issue.

Any help would be greatly appreciated.

Thanks,

Seb

**Comment by seble2016** [comment]
The code: 

lear all
clc
close all

directory='D:\DATAS\1_PLAYDATA\';

ncsfiles=dir(fullfile(directory,'*ncs'));
ncsfiles={ncsfiles(1:end).name}';
rootnames = cellfun(@(x) x(1:find(x=='.',1,'last')-1) ,ncsfiles,'uniformoutput',0);
matfiles=cellfun(@(x) [x(1:find(x=='.',1,'last')-1) '_spikes.mat'],ncsfiles,'uniformoutput',0);

addpath('D:\DATAS\matlab scripts\spike analyses Quiroga\wave_clus-testing')
par=set_parameters();
par.stdmin = 4;
par.stdmax = 25;
par.sr=16000;

for i=1:size (ncsfilelist,1);

disp(['Analysing ' ncsfiles{i,1}])

% spike identification
Get_spikes (ncsfiles(i,1),'par',par)

% spike clustering
Do_clustering (matfiles(i,1),'par',par)

end

**Comment by ferchaure** [comment]
Wave_clus uses the code in Raw_data_readers/ncs_wc_reader.m to open the ncs file. Maybe Neuralynx changed the format again, we read from the binary without use another libraries. 
Another way to run Wave_clus is making a new .mat file with the raw signal in a data variable and read from that.
Could you check the par.sr value inside the _spikes_ or _times_ files? The ncs file has the sampling rate inside, and that value it will be use.

**Comment by seble2016** [comment]
Thanks a lot for your quick reply. I will try using the .mat file and see if I will be able to manage to bypass this problem.

Yes, I checked the par.sr in the times file and it show 16000, as I specified.

I'll get back to after trying this in a bit.

**Comment by ferchaure** [comment]
Another source of problems could be the reference. We use the timestamps of the file... do you set the first time frame as 0?

**Comment by seble2016** [comment]
I haven't done any changes really. I have just submitted the file to wave_clus. Do you know how I should check for this? Sorry, pretty new.

**Comment by seble2016** [comment]
I the meantime, I checked using the .mat format. I have a new form of error when I use the code below:

Error: 'Wave_clus didn't find a sampling rate in file. It will use the set in set_parameters.m
0 of 1 'spikes' files done.'

Code:
%% use .mat file instead of .ncs
% open .ncs file - fieldtrip
cd(foldername);
files=dir('*ncs');
hdr=neuralynx_getheader('CSC01.ncs');
n=size(files,1);
[dat]=ft_read_data('CSC01.ncs');

data=zeros(n,size(dat,2)); %create a matrix where we put traces
clear dat;

for i=1:length(files)
    data(i,:)=ft_read_data(files(i).name);
end

clear i;
%ADBitVolts=hdr.ADBitVolts*1000000
clear ans;
thedata=data*(-1);
clear data;
clear files;
thedata=thedata';

% save the data as .mat
save ('thedata.mat', 'thedata')

% set params

addpath('D:\DATAS\matlab scripts\spike analyses Quiroga\wave_clus-testing')
par=set_parameters();
par.stdmin = 4;
par.stdmax = 25;
par.sr=16000;

% detect spike
Get_spikes('thedata.mat','par',par);

**Comment by ferchaure** [comment]
that should be only a warning.... add a sr variable with the sampling rate in the mat file.

About the reference:
Wave_clus use the timestamps of the ncs, maybe the first one isn't 0 and your code suppose that.

**Comment by seble2016** [comment]
Ok. I'll try that and revert back.
Thanks

**Comment by seble2016** [comment]
Hi I thought I'd write here for posterity's sake. 

So the problem as you pointed out, ferchaure, was because ncs_wc_reader.m was reading time0 to be different from 0. Hence the problem with the time stamps later on.

So I tried to offset the time stamp as follows: 

 o = ncs_wc_reader(par, ncsfiles{i,1}); % saving the ncs file readout
 spktimems_offset=cluster_class(:,2)-o.TimeStamps(1)/1000; % deduct time time0 recorded in us (ms=us/1000) from each timestamp in cluster_class recorded in ms
 cluster_class(:,3)=spktimems_offset; % save corrected timestamp back in cluster_class

this seems to do the trick.

Thanks again for your help
