### ISSUE TITLE
polytrode data

### ISSUE THREAD

**Issue by GIL42** [csn-le/wave_clus#160]
I am using wave_clus to analyze data from a 16 channel electrode by first running parse_data_pl2, Get_spikes_pol, and do_clustering. In regards to the output files generated by wave_clus how can I differentiate what spikes came from what channel and the unit they belong to.  I'm looking to find the amplitude and time of each unit, which I can find when I run each parsed file individually, but when ran as a polytrode I cannot tell what entry in the arrays are associated with what channels or units

**Comment by ferchaure** [comment]
_cluster_class_ gives you the time and class of each concatenated spike (the samples around that time for all the channels).
There is not an automatic way to relate a unit with a channel. You could check where is the maximum absolute value for the mean waveform for each class and then (assuming that the length of the spike is 64 for each channel) if the peak is on the first 64 samples the class "belongs" to the first channel; if the peak is in between the sample 65 and 128 the class "belongs" to the second channel, etc. remember that if the channels are close enough a class could have a hight amplitude in more than one channel.

I would recommend separating the channels in groups geometrically close to each other to analyze polytrodes with fewer channels.

**Comment by GIL42** [comment]
Thank you for your reply! Should the batch functions get_ spikes and do_clustering work with the individual .pl2ch files that are generated after running parse_data_pl2? I can load the .pl2ch through the GUI, but am unable to do so running the batch files. Unfortunately, I cannot post the error message I receive but can do so tomorrow.

**Comment by ferchaure** [comment]
It should work the same as the GUI

**Comment by GIL42** [comment]
![Wave_clus_save_error](https://user-images.githubusercontent.com/61711647/76095296-0ca18f80-5f92-11ea-82bd-13c952f3b069.jpg)
Sorry I couldn't post this yesterday, but these are the messages I receive when using Get_spikes on pl2ch files types.

**Comment by ferchaure** [comment]
try changing the filename to one without the '-' symbol.

**Comment by GIL42** [comment]
![Get_spikes_error](https://user-images.githubusercontent.com/61711647/76111267-f5709b00-5fad-11ea-8f45-3fc1d84fb7ea.jpg)
Hi,
So it does seem that the filename was the cause of the issue. Above you can see some of the combinations I tried. I would note that "Get_spikes('test02.pl2ch') says 0 of 1 files done even though it had produce the xx_spike.mat file.  Changing  the files names allows it to work from a txt file as well.

Thank you for you help, let me know if you'd like me to try anything else!

**Comment by ferchaure** [comment]
> 0 of 1 files done even though it had produce the xx_spike.mat file
That is just the operative system giving outdated info to Matlab, it doesn't matter really.
