### ISSUE TITLE
matlab crash

### ISSUE THREAD

**Issue by paweltacikowski** [csn-le/wave_clus#162]
Hi, 

Thanks for creating this awesome tool!

I open pre-clustered spikes, inspect them, save final times_CSC successfully, and then Matlab crashes. 

Is anyone experiencing the same problem? What's the trick?

I'm using wave_clus3 and Matlab 2014b. MacBook Pro, 3.1 GH Intel Core i7, Mac OS High Sierra, 16 GB RAM.

Thanks for your help!

Pawel

![crash](https://user-images.githubusercontent.com/42366397/76693697-e1b8da80-6626-11ea-9e6b-00db998c8b87.jpg)

**Comment by paweltacikowski** [comment]
FYI problem stopped after installing Matlab 2019b.

Btw, with Matlab 2020a the 'manual' button (draw rectangles) doesn't work. 

Best,

Pawel

**Comment by ferchaure** [comment]
Good to know, I will check the issue with Matlab 2020a and the 'manual' button

**Comment by ferchaure** [comment]
Do you have the "Image Processing Toolbox" in your Matlab 2020a ?
