### ISSUE TITLE
Outputs not displaying Properly 

### ISSUE THREAD

**Issue by Bilalgp** [csn-le/wave_clus#164]
Hi. I am using MATLAB 2019b. Wave_clus works well for most data sets but there is one that is causing some issues. The output cluster_class is not displaying some of the clusters for some odd reason. There is a warning in the command window that pops up. The issue I think is it isn't exporting properly. I am not sure why it is only for this data set because other electrophys data displays well. 

I tried to fix the problem by doing an 'auto' paperpositionmode after line 105 in wave_clus.m but I am not sure if this is where to place it/the warning persists. 

![image](https://user-images.githubusercontent.com/26805330/78305404-ceef4280-750e-11ea-8ef9-e001d9837049.png)
![image](https://user-images.githubusercontent.com/26805330/78305474-f6dea600-750e-11ea-8c42-de75d8834e1b.png)
![image](https://user-images.githubusercontent.com/26805330/78305482-fba35a00-750e-11ea-8326-53ea165fca8c.png)

**Comment by ferchaure** [comment]
That is quite odd. Can you reproduce the error? or sharing the file that generates it?
I would worry more for the warning about the missing file, that looks like you removed the temporal files used by the GUI.

**Comment by Bilalgp** [comment]
Is there an email that I can send the file to you? It is too large to attach here.

I did a while back change the code to remove any filtering (to input already filtered data) but I did compare the results and everything seemed normal. I will check the code files again.

**Comment by Bilalgp** [comment]
I just checked my files. I am not sure how but some files were indeed missing. I think I resolved the issue for now. Thanks.
