### ISSUE TITLE
Question about automatic results 

### ISSUE THREAD

**Issue by Bilalgp** [csn-le/wave_clus#167]
I have a question about the automatic results in the new wave_clus algorithm. Is there a way to select clusters from different temperatures manually if we are not satisfied with the output of the clusters? Or is merging the only option?

**Comment by ferchaure** [comment]
You can select other clusters using the GUI, just remember to fix the clusters that are fine before changing the temperature. more info [wiki/Graphical-User-Interface](https://github.com/csn-le/wave_clus/wiki/Graphical-User-Interface)
