### ISSUE TITLE
"non-existent field 'tsmax'

### ISSUE THREAD

**Issue by GIL42** [csn-le/wave_clus#169]
Hi,

When I change the tmax field in set_parameters from 'all' to 30 I receive  this error
![tsmax](https://user-images.githubusercontent.com/61711647/80536212-06b3a380-8970-11ea-93f5-842687ecc8cf.png).

this is my set_parameters file: 
![tmax](https://user-images.githubusercontent.com/61711647/80536284-234fdb80-8970-11ea-8534-c7f1f90e3aa1.png).

When change the parameters in the UI and the load my data I do not get an error message, but when I look at par in the times_*.mat file tmax is still set to 'all'.
The specific file is 50 seconds long, any help would be appreciated.

Dylan

**Comment by ferchaure** [comment]
Hi Dylan you misspell the parameter t**s**max. 
It works in the other case because it uses the previous default parameter

**Comment by GIL42** [comment]
Hi Fernardo,

I am still unable to change the variable to 30 as when I change the parameters file  to tsmax it come back with the error undefined field tmax.

![tsmax_error](https://user-images.githubusercontent.com/61711647/80600782-e846ba00-89fa-11ea-826a-9d1d20a25b99.png)
![tsmax](https://user-images.githubusercontent.com/61711647/80600785-e8df5080-89fa-11ea-8e46-4167d7b444f2.png)

As I am using the batch file should I be attempting to change the variable when using the batch script instead of the parameters file?

**Comment by GIL42** [comment]
I was able to set tmax to 30 by adding a line of code to parameter file 
![tsmax_tmax](https://user-images.githubusercontent.com/61711647/80610240-1cc07300-8a07-11ea-9ce0-fd32536c6d8a.png)

Is this the correct method for changing the variable?

**Comment by ferchaure** [comment]
That is ok for now. We will fix the naming issue in the next version.

**Comment by GIL42** [comment]
Awesome, thank you!

**Comment by GIL42** [comment]
After looking over some of my data it seem that the 'fix' I found did not fix my problem. The code I have above is able to set the par.tmax variable in the times files to the desired time, 30 seconds in my case. But it seems Get_spikes is still using the whole file for processing as the time stamps found in cluster class are greater than 30. I can work around this problem I just wanted to give you an update.

**Comment by ferchaure** [comment]
thanks for updating me.
What type of data are you reading? from a matfile?

**Comment by GIL42** [comment]
I start with a Pl2 file with raw data, run that through parse_data_pl2, then the batch files Get_spikes and Do_clustering.

**Comment by ferchaure** [comment]
Ok, can you try setting the parameter:
 `par.segments_length = 0.5;`

**Comment by GIL42** [comment]
1) ![tmax_test4](https://user-images.githubusercontent.com/61711647/81185032-1722da00-8f7f-11ea-9ba4-f5c2e9d1098b.png)
2) ![par2test4](https://user-images.githubusercontent.com/61711647/81185125-33bf1200-8f7f-11ea-93e8-da2e6f7d5f58.png)
I ran get_spikes and Do_clustering with par.segments_length = .5;
For the first image I receive the error: Warning: Reference to non-existent field 'tsmax'.
For the second Get_spikes and Do_clustering produce their respective file with par.segment at .5 and par.tmax at 30. The times stamps in cluster_class are still larger than 30

**Comment by ferchaure** [comment]
That is really odd, could you send me the parsed file and its 'pl2_meta_data.mat'?

**Comment by GIL42** [comment]
https://howardu-my.sharepoint.com/:f:/g/personal/dylan_gilhooly_howard_edu/Eh14yanbwVZEgQ2jokah9G8B8wJwkBQUFYOeawAojluY8g?e=WCsk9W

Let me know if you have any issue accessing the files. File005.pl2 is the original file with all the data, the rest is the output from parse_data_pl2.

**Comment by ferchaure** [comment]
thanks, I download what I need, you can stop the sharing. I will fix this bug with the tsmax/tmax condition and let you know

**Comment by ferchaure** [comment]
Done, please download the new code

**Comment by GIL42** [comment]
Thank you for your help!
