### ISSUE TITLE
wave_clus: GUI temperature setting

### ISSUE THREAD

**Issue by seble2016** [csn-le/wave_clus#17]
Hello,

I have a more general question about using the wave_clus temperature setting on the GUI.

I am having a hard time understanding how the temperature works. My plan was to play with my data on the GUI to get the right temp. and see if the spikes I have in the selected cluster detects the spikes that are outside of my noisy periods (I have a lot of noisy periods). When I'm happy I want to do a batch processing.

Now the problem is when I want to do batch processing, where do I go and look at the temperature I used so that I can apply it to all my data?

Thank you in advance for your help.

Seb

**Comment by ferchaure** [comment]
It doesn't work like that. 
Generally, the best solution requires more that only one temperature, for that reason it's better if you use the GUI always. 
For now (I'm working in new algorithms) this is my way to work: 
1)Get_spikes
2)Do_clustering
3) After looking the figures, I open with the GUI  the channels with worst automatic clustering.

If you really want to try you idea, you can change the parameters: mintemp and maxtemp. In this way you're forcing the batch processing to choose a temperature between them. To be honest, the idea of choosing the same temperature could work only if the datasets are almost the same and even in that case it won't be necessarily the best sorting.

**Comment by seble2016** [comment]
Thanks a lot for your reply, ferchaure.

In fact at the beginning I run step 1 (Get_spikes) and step 2 (Do_clustering) like you did. I have to say, I don't know how to identify what is a 'good clustering'? Is a 'good' clustering one that gives more than one cluster in the figures?
What should one look at to decide that one cluster is good over the other? The ISI(ms) graph?

**Comment by ferchaure** [comment]
Things to look:
-All the samples of the cluster with more or less the same deviation. Usually you can see easily if a cluster has more than one type of spikes.
- each cluster with unique waveforms.  Merge them if the templates are visually the same.
- cluster 0 with noise. If you see a lot of  spikes there, the automatic solution didn't found its neuron.

**Comment by seble2016** [comment]
Thanks a lot for your reply.

**Comment by seble2016** [comment]
One other question: is there a way to only tell wave_clus to analyse data within a limited window?
i.e if I want to tell wave_clus to run 'Get_spikes' only in selected periods of the recording period.

In the example of Get_spikes.m there is this code
% Get_spikes([1:8 33:56],'parallel',true,'par',param);
Would you explain to me what [1:8 33:56] is doing?

Thanks again and sorry for the stupid questions.

**Comment by ferchaure** [comment]
You can use the parameters: tmax and tmin to load only that segment of raw signal. You can create a param variable for each segment,  set that fields and then call  Get_spikes( .............. , 'par',param )

In that example, Get_spikes will open all the spikes files with that numbers ([1:8 33:56]) in the name (i.e. something34_spikes.mat).

**Comment by seble2016** [comment]
Thanks a bunch. I'll try changing the tmin/tmax.

On 5 Sep 2016 17:47, "Fernando Chaure" <notifications@github.com> wrote:

You can use the parameters: tmax and tmin to load only that segment of raw
signal. You can create a param variable for each segment, set that fields
and then call Get_spikes( .............. , 'par',param )

In that example, Get_spikes will open all the spikes files with that
numbers ([1:8 33:56]) in the name (i.e. something34_spikes.mat).

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub
<https://github.com/csn-le/wave_clus/issues/17#issuecomment-244775303>, or mute
the thread
