### ISSUE TITLE
error messages upon temperature change

### ISSUE THREAD

**Issue by sv-bio** [csn-le/wave_clus#170]
Dear Fernando,
There is a bunch of error massages upon pressing "Change temperature" button (below).
I do not know how this might affect the analysis, so it is just FYI.

Sincerely,
Stan

System configuration:
OS Debian 8.0
Matlab v.7.9.1

min. cluster size: 5
total number of clusters: 17

Messages:

Error using ==> setappdata
Invalid object handle

Error in ==> iptsetapi at 21
    setappdata(h,'API',api);

Error in ==> impoint>impointAPI at 281
iptsetapi(h_group,api)

Error in ==> impoint>impoint.impoint at 90
            [h_group,draw_api] = impointAPI(varargin{:});

Error in ==> wave_clus>change_temperature_button_Callback at 433
    point = impoint(handles.temperature_plot);

Error in ==> gui_mainfcn at 96
        feval(varargin{:});

Error in ==> wave_clus at 63
    gui_mainfcn(gui_State, varargin{:});
 
??? Error while evaluating uicontrol Callback

**Comment by ferchaure** [comment]
Thanks Stan

It's quite useful can change the temperature. Can you try:
Change line 428 on wave_clus.m:
`if exist('impoint','class')`
for
`if false`
that should allow you to use an alternative method to select a temperature.
