### ISSUE TITLE
Request for SpikeInterface Readout

### ISSUE THREAD

**Issue by Bilalgp** [csn-le/wave_clus#172]
Hello. I am using both Wave_clus and SpikeInterface to analyze data. Would it be possible to make an SI readable format or extractor from the times_data.mat file output?

**Comment by ferchaure** [comment]
I guess that I can do it, it should be similar to the JRCSortingExtractor, just reading variables in a Matlab file.

am I right, @alejoe91?

**Comment by alejoe91** [comment]
Hi @ferchaure 

Yes I think it will be similar. Right now for wave-clus we save the output to mda and load it with the `MdaSortingExtractor`. I guess one could load the mat files directly!

**Comment by Bilalgp** [comment]
Great thank you

**Comment by ferchaure** [comment]
This is already implemented now
