### ISSUE TITLE
How to set parameters in command window?

### ISSUE THREAD

**Issue by xurong2016** [csn-le/wave_clus#175]
Hi Fernando,

I want to use wave_clus to do spike sorting automaticaly, so I would like to ask you some questions about the command.

1. I filtered the data from 300Hz to 3000Hz, and saved as 'save('***.mat','data');' then I want to use the wave_clus without set parameters manually, should I set parameters in program? Like par.sr, par.detection.... How can I do that? Please show me the details.

2. Can the results be saved automaticaly? Could you show me the code? 

Thank you very much!

**Comment by ferchaure** [comment]
1. You can use Wave_clus without filtering (by default wave_clus will filter again the signal). To set the parameters you can use code like:

```
%you can set the parameters in a structure:
par.sr = 30000; %sampling rate in Hz
par.detect_order = 0; %to disable the detection filter
par.sort_order = 0; %to disable the sorting filter
par.detection = 'neg'; %if the peaks of your spikes are negatives
%Then call the batch file to detect spikes
Get_spikes(filename,'par',par); %it creates a filanme_spikes.mat file with the detected spikes
%you can set parameter used for the clustering
par.template_sdnum = 3;    % for example, if you set a greater value like 4 more spikes will be forced in one detected class
%Finally call the batch file to classify the spikes
Do_clustering([filename '_spikes.mat'],'par',par)
```
You can find more info in the Get_spikes.m and Do_clustering.m files.

2. The results will be saved on the file 'times_filename.mat' and the variables are explained [here](https://github.com/csn-le/wave_clus/wiki/Output-Files)

**Comment by xurong2016** [comment]
Hi  Fernando,

Thanks for your kindly help, so if I use this two functions,  will I get the same result as the wave_clus? And the wave_clus can not be used as wave_clus('***.mat','par',par) , right? 

Thank you very much!

**Comment by ferchaure** [comment]
> I use this two functions, will I get the same result as the wave_clus? And the wave_clus can not be used as wave_clus('***.mat','par',par) , right?

Exaclty

**Comment by xurong2016** [comment]
Hi Fernando,

Sorry to bother you again, but when I set the par.detect_order=0 and / or
par.sort_order=0 the program will show error :

Error using ellipap
Expected N to be positive.

Error in ellipap (line 26)
validateattributes(n,{'numeric'},{'scalar','integer','positive'},'ellipap','N');

Error in ellip (line 99)
[z,p,k] = ellipap(n, Rp, Rs);

Error in spike_detection_filter (line 12)
    [b,a] = ellip(par.detect_order,0.1,40,[fmin_detect fmax_detect]*2/sr);

Error in readInData/get_segment (line 235)
                xf_detect = spike_detection_filter(x(1:lplot), obj.par);

Error in Get_spikes>get_spikes_single (line 182)
            x = data_handler.get_segment();

Error in Get_spikes (line 134)
        get_spikes_single(filename, par_input);


It will go well if I do not change them to 0, and I change other parameters
like par.sr=30000; par.detection='both'; Did I do something wrong? Thank
you very much.

Fernando J. Chaure <notifications@github.com> 于2020年6月9日周二 下午12:57写道：

**Comment by ferchaure** [comment]
Just update the wave_clus code from this repository

**Comment by xurong2016** [comment]
Hi Fernando,

Sorry to bother you but I have another question:  after I do wave_clus, it
will appear a result named 'time***.mat', with that I can find out each
spike and its time, but how can I figure out each spike belongs to which
cluster? Thank you very much.

Fernando J. Chaure <notifications@github.com> 于2020年6月15日周一 下午12:21写道：

**Comment by ferchaure** [comment]
check the wiki page related to the outputs: [https://github.com/csn-le/wave_clus/wiki/Output-Files](https://github.com/csn-le/wave_clus/wiki/Output-Files)

**Comment by xurong2016** [comment]
Hi Fernando,

Thank you very much for reply me so quickly, but if I would like to set
spikes into just two clusters, which parameter should I change? Thanks
again.

Best,
Rong

Fernando J. Chaure <notifications@github.com> 于2020年6月30日周二 上午5:02写道：

**Comment by ferchaure** [comment]
Hi, the tricky issue, that we can't resolve for you is: which clusters to remove?. I don't recommend just keep a fixed number of clusters. 
A way to just keep some clusters is open the times_* file using the GUI and manually reject the clusters you don't like, and then force again the spikes just in the rest of the clusters. 

If you really want to keep a fixed number of clusters, the lines to remove clusters and force the rest of the spikes into them can be:

```
load('times_filename.mat')
classes = cluster_class(:,1)
classes(classes>2) = 0 %use son criteria to remove classes, for example keep just the 2 first ones
par = set_parameters()
f_in  = spikes(classes~=0,:);
f_out = spikes(classes==0,:);
class_in = classes(classes~=0);
class_out = force_membership_wc(f_in, class_in, f_out, par);
classes(classes==0) = class_out;

```
