### ISSUE TITLE
50Hz noise 

### ISSUE THREAD

**Issue by AnnaShpektor** [csn-le/wave_clus#176]
Dear Fernando,

I just started using wave clus. Thank you for such an easy to get going software!
For most of the recordings I get pretty reasonable outputs. However, from some of the ISIs (examples attached) it seems that the software sometimes confuses 50Hz noise with spikes. I’m wondering how this can be possible if I have the 300Hz high pass filter on. I attended the screenshot of my settings. Do you have any suggestions? 

Thank you very much!
Anna
<img width="1040" alt="example2" src="https://user-images.githubusercontent.com/66362903/84774867-18680d80-afe7-11ea-8661-bca7dcfa7a15.png">
<img width="969" alt="example1" src="https://user-images.githubusercontent.com/66362903/84774882-1bfb9480-afe7-11ea-87d8-d72fbf3d9890.png">
<img width="533" alt="settings" src="https://user-images.githubusercontent.com/66362903/84774949-33d31880-afe7-11ea-98d2-741c2cab1b9d.png">

**Comment by ferchaure** [comment]
Hi Anna, 

I would recommend: increase a little the stdmin (you have a quite noisy channel) and preprocess the data before wave_clus using a notch filter at 50Hz, the noise from the line is too hight to filter using a typical bandpass filter.

On the other hand, is a good practice to use a positive or negative threshold on different runs (then just join the results together). That is related to the alignment of the peak of the spike and the bipolar spikes. Otherwise, you could end up with multiple clusters of the same bipolar neuron.

If the signal is from humans (I read patient), as an experimenter myself, I will tell you:  If you can **always** unplug the bed (they have batteries anyway), otherwise, the signal in the microelectrodes are just 50Hz noise.

**Comment by AnnaShpektor** [comment]
Hi Fernando,

Thank you very much for your answer. Next time I'll definitely recheck if the bed is switched off. 
I tried to filter out 50HZ frequency, but sadly it didn’t improve the output very much. It looks like there’s more noise that isn't 50Hz. You can see the same peak in ISIs is there after applying the notch filter. And that peak is around 18ms. I also attached the power spectrum of the data.

I also noticed that there are some periods of the data that consist only of noise (picture attached).
￼
So I run a notch filter, then removed all the periods with this strong mechanical noise, and then reference the data by subtracting mean signal across channels from each channel.
This changed the output, but while the number of the “spikes” reduced, the strange peak in ISI is still there. 
￼
<img width="983" alt="preprocessed_data_sorting" src="https://user-images.githubusercontent.com/66362903/85152317-874e9c00-b25d-11ea-94dc-e2636e1bacd0.png">
<img width="1027" alt="filtered_data_sorted" src="https://user-images.githubusercontent.com/66362903/85152334-8d447d00-b25d-11ea-9709-1b6bdce54352.png">
<img width="497" alt="power_spectrum" src="https://user-images.githubusercontent.com/66362903/85152337-8e75aa00-b25d-11ea-883f-4df93dc64515.png">
<img width="489" alt="noise" src="https://user-images.githubusercontent.com/66362903/85152339-8f0e4080-b25d-11ea-9fe2-c5385f5a852a.png">

**Comment by AnnaShpektor** [comment]
I tried the same procedure on another recording that had a strong 50Hz peak in the power spectrum.
I attached the original output from wave clus and the  the output after removing 50HZ, deleting noisy periods and referencing.
￼

Do you have any other suggestions on what I could try? And may be you have some ideas on where those very noisy periods can come from?

I'm sorry for so many questions! Thank you so much for your help

**Comment by AnnaShpektor** [comment]
I tried the same procedure on another recording that had a strong 50Hz peak in the power spectrum.
I attached the original output from wave clus and the the output after removing 50HZ, deleting noisy periods and referencing.
￼

Do you have any other suggestions on what I could try? And may be you have some ideas on where those very noisy periods can come from?

I'm sorry for so many questions! Thank you so much for your help
<img width="518" alt="power_spectrum2" src="https://user-images.githubusercontent.com/66362903/85152935-44d98f00-b25e-11ea-8a5e-9ed1f09dd18d.png">
<img width="1069" alt="raw_data_sorting2" src="https://user-images.githubusercontent.com/66362903/85152938-460abc00-b25e-11ea-8a30-5f5973d2d79d.png">
<img width="1064" alt="preprocessed_data_sorting2" src="https://user-images.githubusercontent.com/66362903/85152945-473be900-b25e-11ea-9f6c-f91afd17410d.png">

**Comment by ferchaure** [comment]
It is an interesting signal. What is the sampling rate of the recordings?

> reference the data by subtracting mean signal across channels from each channel.

That could be dangerous in some cases, try with the median of the channels

Maybe an elevator close to the room? I would add a few notches to remove any other peak (outside the 1/f^k curve) on the power spectrum lower than 50 Hz. 

To be honest, when the recording has this odd characteristic, we don't use it. More and more pre-processing just make unreliable the results. Can you check the approximate position on the brain? if these channels are flexible micro-electrode, they can finish outside any dense structure, floating on liquid, getting a lot of noise and no real spike.

**Comment by AnnaShpektor** [comment]
Thank you very much for your suggestion. I tried them, but as you said those channels ended up being just noise. Luckily, other recording sites look better. 
Just the last technical questions. In 20-30% of the cases when I run wave clus, it fails with the same error [message:](url) segmentation fault. Then if I rerun it 1-2 times more, it usually works fine. I was wondering if there is a way to optimise this. 
Thanks a lot for all your inputs!
<img width="543" alt="Screenshot 2020-06-25 at 20 06 37" src="https://user-images.githubusercontent.com/66362903/85766561-d5611500-b71f-11ea-8d88-9fdf40fd623e.png">

**Comment by ferchaure** [comment]
That is the mac executable maybe recompile SPC for your particular OS version will help but we don't have the source code of the SPC to fix that.
A Linux or Windows machine won't have that issue.
