### ISSUE TITLE
Stange timings in cluster_cluss

### ISSUE THREAD

**Issue by AnnaShpektor** [csn-le/wave_clus#177]
Hi Fernando, 

When I run wave clus on .ncs files, in most cases the second column of the cluster_cluss doesn't seem to be in milliseconds. The minimum value can be, for example, 1590513367032. However, if before using wave clus I transform the .ncs file into a .mat file, wave clus outputs time in milliseconds.  Do you know what can be causing this issue?
I'm wondering as I already run many session in wave_clus using .ncs files, but now I'm not sure how to use the output. 

Thanks a lot!

**Comment by ferchaure** [comment]
That looks like the new version of .ncs just broke own parser... again

Which code are you using to parse from ncs to Matlab?

**Comment by AnnaShpektor** [comment]
data_ncs=read_neuralynx_ncs([data_folder '/u' site num2str(w) addition '.ncs']);
data==reshape(data_ncs.dat,1,size(data_ncs.dat,1)*size(data_ncs.dat,2));
save([data_folder '/u' site  num2str(w) '.mat'], 'data', 'sr')

Does this sound okey?

**Comment by ferchaure** [comment]
Maybe... I don't know the source of the function read_neuralynx_ncs, but if the results make sense especially the timing keep it. 
Did the waveforms look fine when you use the ncs file directly on wave_clus?

**Comment by AnnaShpektor** [comment]
read_neuralynx_ncs is a function used by fieldtrip.
Yes, the waveforms look the same for .ncs and .mat, only timings are different

**Comment by ferchaure** [comment]
I recommend you to keep using the read_neuralynx_ncs, but I would like to try to fix our code.

Could you look inside the files created by using the ncs file directly on wave_clus, and check the par.sr value?
Maybe the bug is there.

**Comment by AnnaShpektor** [comment]
par.sr=32768 seems correct. 
may be I can send you the output for one of the channels to have a look?

**Comment by ferchaure** [comment]
I think I can fix the parser now. Anyway, I will be grateful if you can send me a small ncs recording to test the code

**Comment by AnnaShpektor** [comment]
I emailed you.
