### ISSUE TITLE
Error using ones NaN and Inf not Allowed (Small Inconvenience) 

### ISSUE THREAD

**Issue by goldenbuddy** [csn-le/wave_clus#178]
Hi! I am fairly new to this program and the world of spike sorting so my following question may be at a novice level. So any help you can provide would be greatly appreciated! I am working with microelectrode data from an MCS machine so I have to convert the data to a .mat format in order to use it with this program. For some reason when I try to use the GUI to run some channels it gives me the following error message in my MATLAB terminal: 

![WaveClusGuiErrorMessage](https://user-images.githubusercontent.com/67498049/88610118-a8639300-d03a-11ea-96a3-2e414292e4b7.png)

When I run the function 'Get_spikes' it gives me a message that 0 of 1 'spikes' files are done. However, it seems to generate a myfile_spikes.mat file. This file then can be opened in the GUI. 

I realize that this is only a small inconvenience to myself, but I just want to make sure that this doesn't have anything to with the integrity/quality of my data that could affect the results. 

Thank you so much for reading and have a good one!

**Comment by ferchaure** [comment]
Hi, It's a quite odd case, both ways load data in almost the same way. 
How do you run Get_spikes? using the 'par' argument? Are you using polytrodes or single channels?


>  0 of 1 'spikes' files are done.
That is just the operative system been slow when asked if the spikes files were created.

**Comment by goldenbuddy** [comment]
Hi! Thanks for getting back to me. When I run Get_spike I just put the name of the file I am using in as a string without a 'par' input. I have edited the parameters through the "Set parameters" button but have only changed the sampling rate from 30,000 to 40,000 Hz. For the error shown above I was only using single channel.

**Comment by goldenbuddy** [comment]
Additionally, running a batch of files from a txt file or running Get_spikes_pol doesn't yield any errors.

**Comment by ferchaure** [comment]
We find this issue before [here](https://github.com/csn-le/wave_clus/issues/43). We suppose that's related to Windows 10 (and/or maybe some versions of Matlab).

I guess (I didn't have the opportunity to check myself) that is related to the way Matlab look for the size of the variables. If you have time and want to check, put a breakpoint on line 47 of _mat_wc_reader.m_ and tell me the value of _data_info.size_ maybe we can find what is exactly happening 

In any case, you can trust your results. If you want to be extra careful check that the value on par.sr is the same value you set on set_parameters.

**Comment by goldenbuddy** [comment]
Awesome! Thank you! That's good to know! Looking at the size, I have a [1,200000] vector. This is the same size as the data set I loaded in.

**Comment by ferchaure** [comment]
Ok, then I don't know why it's failing. could you check the value of obj.max_segments as well? and if it's Nan or Inf check which element of the line 47-48 is zero or nan?

**Comment by goldenbuddy** [comment]
max_segments is not Nan or Inf, it is actually just empty. However, obj.min_index is Nan. On line 38 obj.min_index = floor(par.tmin * obj.sr); My par.tmin is Nan which I assume this is where this error is coming from? This is weird because in the set_parameters file, par.tmin is set to 0. So I am uncertain where the NaN is coming from. I have attached some screenshots. 

Also thank you for your quick responses and apologies for my delayed ones! I've been going back and forth between things. 

![image](https://user-images.githubusercontent.com/67498049/88915030-64c68000-d218-11ea-8b80-e6feb8489d39.png)
![image](https://user-images.githubusercontent.com/67498049/88915063-77d95000-d218-11ea-9595-cd03f40a81ee.png)
![image](https://user-images.githubusercontent.com/67498049/88915132-92abc480-d218-11ea-8d7a-1a03119a4725.png)

**Comment by goldenbuddy** [comment]
Thank you!!! That was exactly what was happening. I had wave_clus 2.0 originally installed from the University of Leicester's website. Everything is working as it should be right now!
