### ISSUE TITLE
the same cell picked up on different electrodes 

### ISSUE THREAD

**Issue by AnnaShpektor** [csn-le/wave_clus#179]
Dear Fernando, 

I am using Ad-Tech microelectrodes, which are supposed to be too far from each other to pick up the same cell on different wires. Thus, I run wave clus separately for each electrode. However, it seems that sometimes I have the same cell picked up on multiple channels. I did many checks before to get convinced - the wave forms look similar, when I check the spike times 90% of them overlap (although on one wire there can be many more spikes attributed to this cluster than on another wire). Of course, the task response is also very similar. 
I'm wondering if there is a way in wave clus to merge/reject some of those units across wires?

Thank you!
Anna

**Comment by ferchaure** [comment]
Hi Anna,

You can try using the channels as polytrodes (more info [here](https://github.com/csn-le/wave_clus/wiki/Polytrodes)). 

Notice that if the microelectrodes end up too close together you are losing the chance to get more neurons. Maybe an issue with the preparation of the microelectrodes is preventing them to open correctly.
