### ISSUE TITLE
Batch files Get_spikes & Do_clustering

### ISSUE THREAD

**Issue by balou1902** [csn-le/wave_clus#18]
Hello,

I meet some difficulties with the spikes sorting. I have used the GUI but I want to use the method on my signal without it. The format of ma data is like... a vector (1*N), N being the length of my signal (.mat).
 I use Get_spikes() and Do_clustering() and I don't understand the format of the input... Do I need to put only a vector ? Because in the beginning of the code, it is written :

% input must be: 
%               A .txt file with the names of the files to use.
%               A matlab cell with the names of the files to use.
%               A vector with channel numbers. In this case the function will proccess all the
%                   supported files (except .mat files) located in the folder with those
%                   channel numbers (e.g., CSC1.Ncs or NSX4.NC5)                    
%               'all', in this case the functions will process all the
%                   supported files in the folder (except .mat files).
% optional argument 'par' and the next input must be a struct with some of
%       the detecction parameters. All the parameters included in the structure 
%       par will overwrite the parameters loaded from set_parameters()
% optional argument 'parallel' : true for use parallel computing

Thanks

**Comment by ferchaure** [comment]
Maybe it will be enough with an example:
You have a file, called **channel43.mat**, with the raw data in the variable **data** (and maybe the sampling rate in the sr variable) . Then you can call  Get_spikes in this ways:
- Get_spikes(43)      (or a vector with all the numbers in the names of the raw files )
- Get_spikes('all')     (it will be try to open all the suported files in the folder)
- Get_spikes('channel43.mat')     (it will be try to open all the suported files in the folder)

Do_clustering is similar, but it will try to open only *_spikes.mat files.

About the optional arguments you have an example in the code, just below that text.

**Comment by balou1902** [comment]
Alright.

I have my signal ('sig.mat') (it is renamed 'data' in matlab) and when I execute the following code : Get_spikes('sig.mat'), it returns the following warning ...

Warning: File type '.mat' isn't supported 
> In Get_spikes>get_spikes_single (line 153)
  In Get_spikes (line 126) 
0 of 1 'spikes' files done.

Thanks

**Comment by ferchaure** [comment]
Did you add the wave_clus folder with subfolders to your path?

**Comment by balou1902** [comment]
Good morning,

I added the path to my folder and it works!  Thanks you very much for your help.

Best, Harry
