### ISSUE TITLE
Plot 'raw' data

### ISSUE THREAD

**Issue by mndiguilmi** [csn-le/wave_clus#180]
Hi Fer
I can't see neither the 'raw' trace nor the threshold line in the upper panel of GUI. I just visualize the sorted spikes (clusters). Could you help me to fix this problem?
best
Mariano

**Comment by ferchaure** [comment]
Hi, Mariano

Did you call get_spikes and do_clustering and then use wave_clus to open the results? Is the filename_spikes file on the same folder that the times_filename file? 
or you just use the GUI to open a raw_data file?

**Comment by mndiguilmi** [comment]
Hi Fer
excuse me. My explanation was really bad. Actually, I obtain my recordings with Intan (RDH files) or with TDT (with NEX extension) from 16 channels (Neuronexus silicon probes). In both cases, I  make a convertion to creates .mat files with continuous variable data (one file per channel). I usually load in Wave_clus each .m file to perform the sorting. After that, the 'raw' trace with its threshold line appears in the upper plot and spike clusters at bottom. Today I tryed to do the same but in this case, just the clusters are displayed in the GUI.  
Best
Mariano

**Comment by ferchaure** [comment]
Did you update the code lately?
Can you check the value of par.cont_segment in your set_parameters.m file?

**Comment by mndiguilmi** [comment]
I updated yerterday by GitHib. 
It is a 10 min recording @40 KHz. Note that the x axis is from 0 to 1.

% PLOTTING PARAMETERS                                                                                                                                                                                                                                                                 
par.cont_segment = true;                                                                                                                                                                                                                                                             
par.max_spikes_plot = 1000;          % max. number of spikes to be plotted        

[Presentación1.pdf](https://github.com/csn-le/wave_clus/files/5089924/Presentacion1.pdf)

**Comment by ferchaure** [comment]
do you have other waveclus files (times_filename, filename_spikes) with the same name in that folder?
It looks like it is finding a times file and plotting the results from there, not making new ones.
