### ISSUE TITLE
Problem with S probe recording

### ISSUE THREAD

**Issue by aboharbf** [csn-le/wave_clus#186]
Running into an issue w/ S probe recordings. 32 channels, and each one I've checked yields:
"""
----------
SPC result of file: 20201115Mo001_NSX_Ch1_spikes

SPC v2.1 (14/2/2000) -- efficient KNN and mstree                     
SPC v2.0.1 (1/12/2000) -- StopRunAtBreak option                      
SPC v2.0 (1/11/1999) -- new param file + revised data structures     
-------------------------------------------------------------------

error:
at line 233 of 'param.c': N<=0
"""

Any tips or trouble shooting advice would be great.

**Comment by ferchaure** [comment]
try calling get_spikes first and check the spikes matrix in the results, something could be wrong with the input to the SPC algorithm.  Other common issue is having another library on path that is overwriting some wave_clus function.

**Comment by aboharbf** [comment]
So I added a try loop, and it seems like 4 channels specifically are causing the issue - 1, 5, 26, and 32. Looking at each _spike file, nothing clear seperates channels making this errors and ones that do:
![image](https://user-images.githubusercontent.com/25850560/99394541-08fa3280-28ad-11eb-99a7-f8108341c2ea.png)
tmp is channel1, which failed, while tmp2, channel 2, has way fewer spikes but did not fail. The 32 channels are processed together, so I'd be surprised if it was a path problem, especially given that seemingly random ones in the middle fail as well. Anything else I may be able to try?

**Comment by ferchaure** [comment]
an option is to plot the spikes and see if they are spikes or maybe a strong noise or acquisition error.

 another stronger check is to add a breakpoint in line 548 of Do_Clustering an see the values in inspk_aux.
