### ISSUE TITLE
is there a way to delete all spikes from cluster 0?

### ISSUE THREAD

**Issue by shirquinn** [csn-le/wave_clus#189]
Hi, 
is there a way to reject/delete all spikes from cluster 0 that are unassigned? 
Thank you

**Comment by ferchaure** [comment]
Hi, sorry but I don't understand the question. If you don't want them in your analysis, after loading the times file you can do something like:

```
keep = cluster_class(1,:)>0; %keep only the spikes from non zero clusters
cluster_class = cluster_class(:,keep);
```
