### ISSUE TITLE
Error unsolved for some signal

### ISSUE THREAD

**Issue by balou1902** [csn-le/wave_clus#19]
Good morning,

I use Get_spikes() and Do_clustering() functions and it works perfectly for some signals. However, it does not work for some microelectrode signals I have. The path is correct but I don't know how to fix the following problem : 
---

Deletion requires an existing variable.

Error in amp_detect (line 115)
index(aux)=[];

Error in Get_spikes>get_spikes_single (line 176)
            [new_spikes, aux_th, new_index]  = amp_detect(x, par);

Error in Get_spikes (line 126)
        get_spikes_single(filename, par_input);
---

Could you help me ?

Thanks.

**Comment by ferchaure** [comment]
that's quite odd... Which version of Matlab are you using?

In any case you can fix it adding:

> index = [];

in the line 51 of wave_clus/Batch_files/amp_detect.m

Let me know if that works, and I will make the change in the next version.

**Comment by balou1902** [comment]
Yes it is working but for some signals it displays only this following statement : 

0 of 1 'spikes' files done.

Thus, I have some empty variables and I can 't run Do_clustering() (or it displays an error) :

index=[]
psegment=[]
spikes = []
sr_psegment = Inf

I have checked the path - it is correct. Do you have any idea ?

**Comment by ferchaure** [comment]
Could you explain me a little more about that signals? The format, etc
Because it's loading a sr = inf

**Comment by balou1902** [comment]
A typical signal of mine (real micro electrode data) is named "micro_channelX.mat" with X=1...34 (the numero of the channel) and is a 1*88965 vector. That's all.

I put in set_parameters() my sampling rate in the variable par_sr.

By the way, I have Matlab R2015b (academic use).

**Comment by ferchaure** [comment]
If the structure of the files are the same it's possible that in that cases you didn't detect any spikes. You can try changing the sign of the threshold

**Comment by balou1902** [comment]
I have changed the length of the following parameter : par.cont_plot_samples = 100000. 
The initial value was 100000 and the length of my signal was 88965 (<100000). I think that's the reason why it did not work. If I put a value <88965, the algorithm works.

The variable 'par.cont_plot_samples' has no influence on the spike algorithm and clustering ? Does not it ?

**Comment by ferchaure** [comment]
You are right, the parameters doesn't influence the algorithms.

**Comment by ferchaure** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Fix error al cargar archivos de menos de un minuto](https://trello.com/c/h4K5MO1E/5-fix-error-al-cargar-archivos-de-menos-de-un-minuto)

**Comment by ferchaure** [comment]
fixed in last commit
