### ISSUE TITLE
Saving error "-V6 option may not be used in combination with the -V7.3 option"

### ISSUE THREAD

**Issue by GuthrieDyce** [csn-le/wave_clus#190]
Hello all,

I have recently encountered the following error while trying to save my progress in wave_clus.

"Error using save
The -V6 option may not be used in combination with the -V7.3 option.

Error in wave_clus>save_clusters_button_Callback (line 587)
	eval(['save( ''' outfile ''',''' var_list '' ver ',''-v7.3'');']);

Error in gui_mainfcn (line 95)
        feval(varargin{:});

Error in wave_clus (line 63)
    gui_mainfcn(gui_State, varargin{:});
 
Error while evaluating UIControl Callback"

I do not think I have ever seen this error before.
Does anyone know why this occurs and how to fix it?

**Comment by GuthrieDyce** [comment]
Just a follow-up here.
I thought I might have been trying to save too much information because I lowered my spike detection threshold too much, but I successfully saved sorted units from another channel containing more spikes.

**Comment by ferchaure** [comment]
You are right, the issue is related to the size of the file but the unusual error message appears for a bug on a catch trying to change the file format. You can download the new code and try again, and maybe it will work fine.

**Comment by GuthrieDyce** [comment]
I only recently downloaded the code.
Has there been an update in the last couple of weeks which might have fixed this?
If not, do you have any idea how many spikes one has to detect before this error is likely to start appearing?
Many thanks,
Guthrie

**Comment by ferchaure** [comment]
> Has there been an update in the last couple of weeks which might have fixed this?

Yes, yesterday. Probably it fixes the issue.

**Comment by GuthrieDyce** [comment]
I have tried again with this same channel after re-downloading wave_clus.
I got a new error this time while trying to save:
"
Error using wave_clus('save_clusters_button_Callback',gcbo,[],guidata(gcbo),0)
Error: Unexpected MATLAB expression.

Error in wave_clus>save_clusters_button_Callback (line 587)
	eval(['save( ''' outfile ''',''' var_list ''',''-v7.3'');']);

Error in gui_mainfcn (line 95)
        feval(varargin{:});

Error in wave_clus (line 63)
    gui_mainfcn(gui_State, varargin{:});
 
Error while evaluating UIControl Callback
"

**Comment by ferchaure** [comment]
ok, Can you try with the code I just update?

**Comment by GuthrieDyce** [comment]
I retried with the updated code, started sorting the data file from scratch and was able to successfully save!
Thank you so much!
I'm curious to know what the problem was now.
Happy holidays!

**Comment by ferchaure** [comment]
Some .mat versions have limitations on the maximum size of the file. If the save fails the idea was to save in other format (a slower one) without that limitation. But I added a typo coding that exception .
