### ISSUE TITLE
Max Cluster Parameter Not Updating

### ISSUE THREAD

**Issue by goldenbuddy** [csn-le/wave_clus#194]
Hi Fernando,

I am attempting to update the max cluster parameter for programmatical clustering. I have changed the parameters in the default, non-default, and directly through the do clustering function. However, non of these have updated the parameters settings for the clusters. I was wondering if you could share some insight into what is going wrong with any of these approaches?

Thank you so much!

**Comment by ferchaure** [comment]
Hi, sorry, but we don't have a max cluster parameter in the new algorithm. Are you using the latest code?

**Comment by goldenbuddy** [comment]
As of right now, I am not. Just to be consistent with some other members of the lab, I have used an older version that's about a year old. However, if this information is of any use, the parameters files will update through the GUI but not through the functions. 

Thank for getting back to me quickly!

**Comment by ferchaure** [comment]
I don't remember exactly that version but for a long time the max cluster parameter was used just to put a limit in the units to show in the GUI, It didn't change any real result.
