### ISSUE TITLE
Sorted spike timestamps colored with cluster colors

### ISSUE THREAD

**Issue by AlexMathi** [csn-le/wave_clus#195]
Hi guys, I'm wondering if it is possible to plot a timeline with timestamps of sorted spikes below the continuous data. Ideally the timestamps would have the colors of the regarding clusters. Is there any option to do so inside wave_clus? Thanks in advance! - Greetings, Alex

**Comment by ferchaure** [comment]
Hi Alex, the continuous segment is just a minute of downsampled signal, it's useful to check the threshold. It won't be informative to mark there the spikes classes. More about this [here](https://github.com/csn-le/wave_clus/pull/25) and in other closed issues.
