### ISSUE TITLE
Chaning the temprature range

### ISSUE THREAD

**Issue by mina65** [csn-le/wave_clus#2]
I loaded CSC4 data and I want to change the temperature range from 0-20. I do it by setting the parameters  
par.mintemp = 0.00;                  
par.maxtemp = 20;                 
par.tempstep = 1;

and once I load the data and I try to set the temperature on Temperature-Cluster size plot, it gives me an error and doesn't allow me to set the temperature.

I would appreciate it if you can help me

**Comment by ferchaure** [comment]
I'm now sure, but probably the temperature is too high that the SPC algorithm find hundreds of "clusters" and the GUI can't handle them. 
Are you sure that you need that temperatures? The interaction between elements is so weak to form a real cluster. (Check the size of the clusters in the temperature plot )

I could give you more help if you attach the message error.

**Comment by mina65** [comment]
![screen shot 2016-02-14 at 11 20 33 am](https://cloud.githubusercontent.com/assets/17225516/13035803/10916c98-d30d-11e5-858b-46aa617777e7.png)
This is how it looks. And I am just trying to duplicate the results that are shown in the tutorial, which is this
![screen shot 2016-02-14 at 11 23 10 am](https://cloud.githubusercontent.com/assets/17225516/13035825/5e60ebec-d30d-11e5-99a4-b9c8b6569d2a.png)
Here the range of the temperature is between 0-20.

This is the error:
Error using  & 
Matrix dimensions must agree.

Error in draw_histograms (line 14)
        times = diff(spk_times(classes==i & ~rejected));

Error in plot_spikes (line 341)
draw_histograms(handles, 0:min(nclusters,3),USER_DATA);

Error in wave_clus>change_temperature_button_Callback
(line 384)
plot_spikes(handles);

Error in gui_mainfcn (line 95)
        feval(varargin{:});

Error in wave_clus (line 63)
    gui_mainfcn(gui_State, varargin{:});
 
Error using drawnow
Error while evaluating uicontrol Callback

Error using handle.handle/set
Invalid or deleted object.

Error in matlab.hg.internal.openfigLegacy (line 104)
            set(fig,'Visible','off');

Error in gui_mainfcn>local_openfig (line 286)
    gui_hFigure = matlab.hg.internal.openfigLegacy(name,
    singleton, visible);

Error in gui_mainfcn (line 233)
            gui_hFigure =
            local_openfig(gui_State.gui_Name,
            'reuse',gui_Visible);

Error in wave_clus_aux4 (line 38)
    [varargout{1:nargout}] = gui_mainfcn(gui_State,
    varargin{:});

Error in plot_spikes (line 331)
                opened_figs{5} =
                wave_clus_aux4('Visible', 'off');

Error in wave_clus>change_temperature_button_Callback
(line 384)
plot_spikes(handles);

Error in gui_mainfcn (line 95)
        feval(varargin{:});

Error in wave_clus (line 63)
    gui_mainfcn(gui_State, varargin{:});
 
Error while evaluating uicontrol Callback

**Comment by ferchaure** [comment]
It's happening what I said earlier.
In that picture we used another scale of temperatures, that is equivalent to the current 0 - 0.2 (the default values).
We will update the pictures of the tutorial for the new version.

**Comment by mina65** [comment]
I see, Thank you for your help.

**Comment by mina65** [comment]
Another question:
I was wondering why the threshold in the first plot is negative but in the second one is positive. Isn't supposed to be always positive since the threshold is set to
Thr= 4std;   std=median{|x|/0.6745}

**Comment by ferchaure** [comment]
In the parameters you can set one of these:
- par.detection = 'pos'; 
- par.detection = 'neg'; 
- par.detection = 'both';

**Comment by mina65** [comment]
Is there anyway that you share the SPC implementation with me?

**Comment by ferchaure** [comment]
I'm sorry, we don't have the authorisation for that.
For more information about the SPC algorithm: _Blatt, M., Wiseman, S., & Domany, E. (1997). Data clustering using a model granular magnet. Neural Computation, 9(8), 1805-1842_
