### ISSUE TITLE
Cannot load data

### ISSUE THREAD

**Issue by wangxinwei1017** [csn-le/wave_clus#20]
Hi,
I have some data pre-detected, and I put these data into one mat file containing index and spikes, but when I load the file, error occurs saying **Subscripted assignment dimension mismatch.**.I tried several times, and I found that if I set the waveform length to maybe 64 points, this error does not occur, but my data has 320 points per waveform, what can I do?

**Comment by ferchaure** [comment]
How did you call the mat file? _something_spikes.mat_? Can you try using a name without the _ _spikes_ ?

If you sampling rate is higher than 30kHz: you can subsample your spikes; or change the parameters w_pre and w_post to use ~2ms of signal per spike.
