### ISSUE TITLE
Optimize for a limited number of cluster

### ISSUE THREAD

**Issue by goldenbuddy** [csn-le/wave_clus#201]
Hi Fernando,

I am working with a data set that has hundreds of electrodes and it is time consuming to manually fix and merge clusters. Fortunately the experimental setup is such that we only expect a few neurons to be detected. In my experience with this data set, Wave Clus tends to over classify the spike shapes so that we end up with too many clusters that I have to manually fix and merge. Is there a way to get Wave Clus to optimize for minimizing the number of clusters it produces more than it already does? For example putting a cap on the number of clusters it is allowed to produce? 

Thanks for your consideration and time!
-Sam

**Comment by ferchaure** [comment]
Hi Sam,

A way to do that is by increasing the value par.min_clus, which represent the smaller peak to select a temperature (and the size of the minimum cluster). An alternative could be decreasing par.maxtemp, but I would test with min_clus first.

**Comment by goldenbuddy** [comment]
Thanks Fernando! Will try these!
