### ISSUE TITLE
Inter Spike Interval

### ISSUE THREAD

**Issue by Jay-Shiralkar** [csn-le/wave_clus#205]
Hi Fernando,
I'm trying to analyze whether ISI distribution of different clusters is statistically different from each other or not.
Although, I get the ISI distribution figures, I'm not able to find the associated numbers with those ISI plots in times files ?
How can I get those ?
Thanks,
Jay

**Comment by ferchaure** [comment]
Hi Jay, You have to calculated them from the spikes times:

For example for the class 1:

```
classes = cluster_class(:,1);
sptimes = cluster_class(:,2);
isi_c1ass1=diff(sptimes(classes ==1));
```
