### ISSUE TITLE
GUI of wave-clus does not produce new figures after I loaded new times_polytrode.

### ISSUE THREAD

**Issue by MBLH** [csn-le/wave_clus#21]
I have used wave clus in batch mode for many months, and it has worked very well so far.
Recently I clicked "save" on the GUI of wave_clus  by mistake (saved as matlab figure file)
, since then the initial screen of GUI always contains the data which I saved by mistake.
But it still worked if I loaded a new data.

However today after my 1st analysis,
even I loaded new data on GUI, it didn't make new figure anymore
(the figure which I saved by mistake persisted, so initial image of GUI does not change).

Do you have an idea to fix this symptom?
Error message is like this;

------------------------------------------------------------------------------------

Index exceeds matrix dimensions.

Error in wave_clus>load_data_button_Callback (line 242)
    clu_aux(:,ipermut+2) = clu(:,(1:length(ipermut))+2);

Error in gui_mainfcn (line 96)
        feval(varargin{:});

Error in wave_clus (line 63)
    gui_mainfcn(gui_State, varargin{:});
 
Error while evaluating uicontrol Callback

**Comment by ferchaure** [comment]
You overwrote the GUI figures. A way to fix that is replace the files in the _fig_ folder for new ones.  If the problem persist, we will think in another solution.

**Comment by MBLH** [comment]
Thanks for very fast reply, I will try it next morning.

**Comment by MBLH** [comment]
Thank you, it was fixed!
