### ISSUE TITLE
Do_clustering

### ISSUE THREAD

**Issue by EveyZhang** [csn-le/wave_clus#214]
Hi,
I ran **Do_clustering** with a detected spike file. When I input '**Do_clustering ('1_spikes.mat')**', and the **1_spikes.mat** is  a file contains a matrix named _spikes_ (nspikes x length) and a vector _index_ with the spike times (in ms) 
I encountered an error:
Wave_clus didn't find a sampling rate in file. It will use the input parameter or set_parameters.m
reference to a non-existent field 'tmin'.
find_temp (line 19)
if ~isempty(aux) && par.tmin==0 && aux==2

Do_clustering>do_clustering_single (line 561)
    [clust_num temp auto_sort] = find_temp(tree,clu,par);

Do_clustering (line 177)
            do_clustering_single(filename,min_spikes4SPC, par_file, par_input,fnum,save_spikes);

I would like to know the possible reasons. Any advice would be appreciated!

**Comment by ferchaure** [comment]
Hi, I remember a similar old bug. are you using the[ last version](https://github.com/csn-le/wave_clus/archive/refs/heads/master.zip)? Could happen if you use an old set_parameters as well

**Comment by EveyZhang** [comment]
Yes, I used the version 3.0.3.

**Comment by ferchaure** [comment]
that version has the issue, just download the latest code

**Comment by EveyZhang** [comment]
ok, Thanks for your response!

**Comment by EveyZhang** [comment]
Sorry, the latest version I found on Github is 3.0.3, did I get something wrong ?

**Comment by ferchaure** [comment]
just from the main page and download or from the link in my previous comment. probably it says the same version but it has a few bug fixed

**Comment by EveyZhang** [comment]
I download from the link in your previous comment and this errors still occurs. Is there something wrong with my input?

**Comment by ferchaure** [comment]
Do you have an old set_parameters in the same folder as the data? It looks like is loading from there and without par.tmin
run:
`which('set_parameters.m')`
and check that is in the new code path.

**Comment by EveyZhang** [comment]
Yes, a new set_parameters.m is in the new folder.

**Comment by ferchaure** [comment]
Ok, I found the issue. Rename the file to something withoyt the '_spikes' at the end. If the spikes are already interpolated (or you just don't have extra samples ) set par.interpolation = 'n' in set_parameters
Let me know if that works

**Comment by ferchaure** [comment]
Ok I just committed code that could fix your issue. Can you  download the new code and try again?

**Comment by EveyZhang** [comment]
It works! Thank you for your patience!

**Comment by ferchaure** [comment]
Thank to you for keep trying :1st_place_medal:
