### ISSUE TITLE
Parameters setting in Do_clustering appears to be ignored

### ISSUE THREAD

**Issue by jbrger** [csn-le/wave_clus#216]
First of all, thank you for the excellent software - it really is very nicely written and implemented.
One thing that I'm a little confused about - entering some parameters as a 'par' input under Do_clustering seems to be completely ignored, for example:
myPar = [];
myPar.stdmin = 5;
myPar.randomseed = 1;
myPar.mintemp = 0.05;
Do_clustering('myfile.mat', 'par', myPar)

Am I missing something here? I've tried setting ridiculous parameters to test, but it still seems to just use the ones in set_parameters.
Appreciate your advice!

**Comment by ferchaure** [comment]
Hi jbrger, I will takea look, but at least stdmin is only used in Get_spikes. For that reason, the times will have the ones in the spikes file or if they aren't there will keep the ones in set_parameters.
