### ISSUE TITLE
how to access the dataset ?

### ISSUE THREAD

**Issue by AuroraWong** [csn-le/wave_clus#217]
I need to download the spike sorting dataset from multi-units from your paper  ‘‘How many neurons can we see with current spike sorting algorithms? ‘’ on the website https://www135.lamp.le.ac.uk/hgr3/. However, it seems that something is wrong with that website. Would you mind share this dataset with me?

**Comment by ferchaure** [comment]
I uploaded them to my personal onedrive:
https://fiubaar-my.sharepoint.com/:f:/g/personal/fchaure_fi_uba_ar/Etp-LojW65VPrXPykpsReMQBuoRmnOR-qhVdRdU7uLofVA?e=cq9Ffu

password: neurons123
