### ISSUE TITLE
Is it possible to extract more waveform info?

### ISSUE THREAD

**Issue by YichenXu1998** [csn-le/wave_clus#221]
Hi,

First I want to thank you for this amazing spike cluster toolbox! I am quite interested if wave_clus can give more info about spike waveform? I noticed that several spike waveform features are quite important such as the peak-to-trough amplitude, waveform phase duration etc. Can waveclus give information about these features?

Best
Felix

**Comment by ferchaure** [comment]
Hi felix, These metrics are out of scope for Waveclus.
