### ISSUE TITLE
Get_spikes_pol.m not dealing with whitespaces in filenames

### ISSUE THREAD

**Issue by rzucca** [csn-le/wave_clus#222]
If the path of your files contain whitespaces (like in the case of storing data on GDrive, where by default the drive is called 'My Drive') Get_spikes_pol.m truncates the filenames and an error is raised when trying reading the file `(File type ' ' isn''t supported)`.

Fixing line 93 like this `electrodes = textread(pol,'%s', 'delimiter', '\n', 'whitespace', '');` fixed the problem.

Best,
Riccardo

**Comment by ferchaure** [comment]
done, thanks for the fix
