### ISSUE TITLE
Error in spike_alignment.m

### ISSUE THREAD

**Issue by YGUO29** [csn-le/wave_clus#225]
It seems there are some errors for line 30-31 in spike_alignment.m
Line 30 does not have the same length on the two sides; line 31 is missing a ":" I think. Just wanted to confirm how to modify this section before I go ahead.. thanks!
<img width="530" alt="image" src="https://user-images.githubusercontent.com/14928111/199302257-b179ae49-9097-4d8e-bfb0-ac07966e08e5.png">

**Comment by ferchaure** [comment]
Hi, you are right. I guess you have already extracted spikes with a lot of samples and you want to realign them? 
To be honest, I guess you don't even need that two lines. I would replace them with something like:

```
rm_borders = floor((size(spikes,2)-ls-2*align_window-4)/2);
rm_odd_spike = rem(size(spikes,2), 2) == 1
spikes1 = spikes(:,(1+rm_borders ):end-(rm_borders+rm_odd_spike ) );
```

The following code is expectring spikes of ls+2*align_window+4 samples (final spike+aligments[align_window on each side]+extra samples for interpolation borders), with a code like the one above, you remove the additional samples.

Can you do test and do a pull request?

**Comment by YGUO29** [comment]
Just did! Thank you!
