### ISSUE TITLE
The manual button is not working

### ISSUE THREAD

**Issue by AlessandraOrsini** [csn-le/wave_clus#228]
When I click on the manual button, it doesn't work. The software doesn't crash and everyhing else works perfectly, but when I try to click on the button it looks like it doesn't respond.

**Comment by ferchaure** [comment]
you have to click it and then select a rectangle in the associated subplot with the raw spikes. Then the spikes in a peak in that rectangle will be added to a new class (highest class number)

**Comment by AlessandraOrsini** [comment]
But that's exactly the problem: I can't select any rectangle after I click
the button.

Il ven 6 gen 2023, 14:28 Fernando J. Chaure ***@***.***> ha
scritto:

**Comment by ferchaure** [comment]
do you have the Image Processing Toolbox installed?

**Comment by AlessandraOrsini** [comment]
Apparently no, I didn't. After installing it, it works. Thanks

Il ven 6 gen 2023, 16:07 Fernando J. Chaure ***@***.***> ha
scritto:
