### ISSUE TITLE
Problem with Polytrode Data

### ISSUE THREAD

**Issue by seacritasianman** [csn-le/wave_clus#23]
I'm trying to use wave_clus to do some polytrode sorting. However, I'm running into some problems, and was wondering if I could get some help on the issue. Some background first:

-We're using an 8 shank polytrode, with a total of 64 sites. I've been trying to sort all the channels on a single shank (8 channels total).
- I'm first separating the data into a series of mat files, with one mat file containing all the raw, unsorted data per channel.
- Then, I create an ASCII formatted text file which has all the file names in it, as an index for wave clus, as per the instruction sheet.
- I then run Get_spikes_pol(1) and Do_clustering(1) in MATLAB, which gets the final output of times_polytrode1.mat.

After this, I try to visualize the data by loading it into the wave_clus GUI. The data loads in fine, but when I press the "Plot polytrode" button, firstly, the new window that pops up only shows one channel (see attachment "polytrode window"). Simultaneously, I get an error in matlab (see attachment "matlab error"). I've also attached a screenshot of the wave_clus window before I press "plot polytrode" (see attachment "waveclus window"). Lastly, I have attached the text file 'polytrode1.txt'. 

Any clue what's going on?

[polytrode1.txt](https://github.com/csn-le/wave_clus/files/629696/polytrode1.txt)
![waveclus window](https://cloud.githubusercontent.com/assets/20893542/20868027/6ccf22da-ba06-11e6-8aea-aed98b04855a.PNG)
![matlab error](https://cloud.githubusercontent.com/assets/20893542/20868028/70af0424-ba06-11e6-940d-fda1c1943df9.PNG)
![polytrode window](https://cloud.githubusercontent.com/assets/20893542/20868029/72942d1e-ba06-11e6-97cc-0a85832bdee3.PNG)

**Comment by ferchaure** [comment]
Hi, I think that is only a problem with the colours
Can you try the new code? (I pushed a commit a few minutes ago)

**Comment by seacritasianman** [comment]
Hey, 
First off, thanks for the prompt reply. The new code did fix the problem! 

However, I'm running into another issue. Now after I've loaded the data (and when I press plot polytrodes, I correctly get the channels), if I press 'Plot all projections', I get this error:

![capture](https://cloud.githubusercontent.com/assets/20893542/20871089/565c87f0-ba46-11e6-8f78-2dd888bfdc15.PNG)


Is that normal for polytrode data? Thanks.

**Comment by ferchaure** [comment]
Similar problem as before.
Sorry for that, I didn't test all the GUI for polytrodes after add the new colours scheme. 
Let me now if you have another issue.

 (I pushed a new commit a few minutes ago)

**Comment by seacritasianman** [comment]
I tried the updated code, and I'm running into the same problem. I compared the 'Plot_polytrode.m' that I have with the online version, and they're identical.

**Comment by ferchaure** [comment]
Can you try  again?

**Comment by ferchaure** [comment]
To be clear, the new commit changes the code of Plot_amplitudes.m

**Comment by seacritasianman** [comment]
I tried the updated code, and everything is working perfectly. Thanks so much for all your help, I really appreciate it!
