### ISSUE TITLE
Sampling rates and window size 

### ISSUE THREAD

**Issue by yrg19** [csn-le/wave_clus#231]
Hello, 

I need some clarifications about the parameters for spikes detection and sorting. 

The default settings are for a 30,000Hz sampling rate and 64 samples as the window for a spike, this would mean a ~2ms window. A spike duration with iEEG is anywhere between 30-300ms. It doesn't seem that Get_spikes/ amp_detect does any downsampling of the data and so I am very confused as to why it is storing full spikes in the simulated data when the window is too short for a physiological spike. 

Using the same batch functions with my data (25,000Hz sampling rate) I am getting a tiny part of the spike being stored. Changing the window size to appropriately contain the ~300ms around a spike would mean storing 7,500 samples. As per an issue committed previously, it was stated that for the feature analysis, such a large window would generate too many features which would be difficult to classify appropriately. 

Can you clarify this and if you recommend downsampling, then at what point in the code? 

Thanks so much for your help, 
Yuval

**Comment by ferchaure** [comment]
Hi Yuval, Spike sorting as an area uses the word "spike" as a synonymous of extracellular action potential (with a duration of ~2ms). And I guess you are asking about iEEG spikes, that are a different thing.  You could try to analyze them using Wave_clus but you will need a totally custom set of parameters and honestly the software is not design for that use.
