### ISSUE TITLE
Simulated data access

### ISSUE THREAD

**Issue by hejinyan0609** [csn-le/wave_clus#233]
Hi,ferchaure
I want to download the simulated data availabled at http://www.vis.caltech.edu/ ~rodri/Wave_clus/Simulator.zip which was introduced in Quian Quiroga et al. (2004) ,but I find the website is gone. Can I have another way to have access to the data sets? Thanks a lot.

**Comment by ferchaure** [comment]
I saw them here: https://spikeforest.flatironinstitute.org/studyset/SYNTH_MONOTRODE
