### ISSUE TITLE
'Manual' cluster selection is not intuitive

### ISSUE THREAD

**Issue by tsieger** [csn-le/wave_clus#26]
It is great to have a way of manually selecting spikes. However, I found the behaviour counter-intuitive. 

The 'Manual' function currently _selects spikes whose **maximum or minimum** over given selected x-range resides inside the given rectangle_ (drawn manually). 

IMHO, a more intuitive way of selecting spikes would be to select spikes that _**pass through** the rectangle_.

For example, the current implementation does not enable to select well-defined spikes coinciding with the red rectangle, because both the maxima and minima of most of the spikes over the selected x-range are outside the rectangle:

![manual_issue](https://cloud.githubusercontent.com/assets/1840074/21259727/01c424aa-c383-11e6-99cf-8386762cf12a.png)

**Comment by tsieger** [comment]
Enabled to select 1-sample wide rectangles.

**Comment by ferchaure** [comment]
I know that the behaviour is counterintuitive and the root of the issue is the lack of documentation... 
We found that the current way is a bit better, at least with our real data. I can show the benefits in your example:

- With you method (red rectangle) the spikes inside the yellow rectangle will be selected as well.
- With the current method you can select the same spikes using que green rectangle, without selecting extra spikes.

![example manual](https://cloud.githubusercontent.com/assets/5598671/21468128/9097b91a-c9e3-11e6-90b3-f76b02426d86.png)

**Comment by tsieger** [comment]
I understand your points, however, using the current behaviour, I can't select easily neither the spikes in the red rectangle, nor those left to the red box (the negative peaks around sample 15).
I understand that selecting the red rectangle using the more intuitive way would result in extra spikes selected, but this often happens also following the current approach.
Moreover, following the current approach, rectangles of width of 1 pixel can't be selected  at all (not sure whether this is a feature or a bug), which makes selection of fast and short peaks almost impossible.

Do you think that implementing both the ways of manual cluster selection would be acceptable, such that users will decide which one to use at runtime, perhaps changing the mode depending on the characteristics of spikes to select? (For example, the manual selection mode could be switched by some key pressed on keyboard and passed to the window key event handlers.)

**Comment by ferchaure** [comment]
Could be that either method works perfectly well.
The current approach needs at least 3 points to find a local extrema. Maybe a good idea is that when the user select a rectangles of width of less than 3 pixels, the Manual function will select all the spikes in that area. What do you think?

**Comment by tsieger** [comment]
I like this idea. I implemented it and will keep using it to learn whether it works well or falls short of selecting some spikes.

**Comment by ferchaure** [comment]
Maybe it's not perfect but I implemented the case for less than 3 samples and added a FAQ about tha manual selection in https://github.com/csn-le/wave_clus/wiki/Frequently-Asked-Questions

what do you think?

**Comment by tsieger** [comment]
Nice. Thanks.
