### ISSUE TITLE
Wave_clus not running in Ubuntu 14.04 LTS

### ISSUE THREAD

**Issue by eliezyer** [csn-le/wave_clus#27]
Hi,

I'm trying to run wave_clus in Ubuntu 14.04 with Matlab R2012a and it looks like that it can't run the spc after calculating spike features.

I'm getting the following error:

/bin/bash: /.../cluster_linux64.exe: Permission denied

Error using load
Unable to read file data_wc.dg_01.lab: No such file or directory.

Error in run_cluster (line 107)
clu = load([fname '.dg_01.lab']);

Error in wave_clus>load_data_button_Callback (line 233)
    [clu,tree] = run_cluster(handles.par);

Error in gui_mainfcn (line 96)
        feval(varargin{:});

Error in wave_clus (line 63)
    gui_mainfcn(gui_State, varargin{:});
 
Error while evaluating uicontrol Callback

I've looked through run_cluster in debug mode and it can't run this cluster_linux64.exe. This is happening even when I run MATLAB as super user.

Any ideas to fix this?
Regards,
Eliezyer

**Comment by ferchaure** [comment]
Hi,
Can you check the permissions of that file? You should make that file executable. 
Let me know if that works.

**Comment by eliezyer** [comment]
Hi,
Thanks for the prompt reply.
I did try to change the file permission, but the ubuntu wouldn't let me do it, even with sudo. So I think it's a folder problem, since I've changed the files to my home directory, the wave_clus worked.
Regards
