### ISSUE TITLE
spike alignment question

### ISSUE THREAD

**Issue by qualiaMachine** [csn-le/wave_clus#29]
I've just realized I've mistakenly processed a small batch of data with incorrectly specified w_pre and w_post parameters.  While the spike peaks are at sample point 15, I mistakenly set w_pre to 12 (sample rate = 24 kHz).  I am wondering, however, if this would actually result in having a drastic effect on the output of the algorithm if my alignment window (interpolation on) is set to 10 sample points.  I would think that the end resulting aligned waveforms would still be normalized toward the 15th sample point given the size of my alignment window.  Is my intuition correct, or am I missing something?

**Comment by ferchaure** [comment]
how did you give the spikes to wave_clus? directly from the hardware, using a file called only _something.mat_ or _something_spikes.mat_ ?

**Comment by qualiaMachine** [comment]
These particular spikes were labelled something_spikes.mat and had been detected and aligned (w/out interpolation) prior to being fed into wave_clus.  I opted to leave wave_clus's alignment feature on given that I thought the interpolation aspect would benefit the sorting process.

**Comment by ferchaure** [comment]
If you use the label something_spikes.mat, Wave_clus will assume that the interpolation and alignment is done, and it won't interpolate or align the spikes again. 
If you try again w/out the __spikes_  label remember to set  w_pre and w_pos  to have 2 extra samples in each side of your detected spikes. (1 for the alignment + 1 for the interpolation)

**Comment by qualiaMachine** [comment]
Thank you for the speedy responses.  I should take a step back before I reply to your advice.  The way that I am implementing this software (for the purposes of running variable batches) has been to make spike alignment a flag, allowing me to turn it on regardless of file name.  Therefore, spike alignment was run with an incorrect w_pre (off by 3 sample points).  Is the effect on the output data fatal, or should the clustering procedure have ran with minimal loss?  I would think that this error would have a trivial effect given that the alignment serves to normalize over a window of points, but I am not certain as I have not spent too much time working with spike alignment algorithms.  

"If you try again w/out the _spikes label remember to set w_pre and w_pos to have 2 extra samples in each side of your detected spikes. (1 for the alignment + 1 for the interpolation)"
I want to make sure I am understanding this correctly.  So say I have 14 sample points prior to the spike sample point and 34 after the spike sample point.  You're simply saying that I should enter in 15 for w_pre and 34 for w_pos, is that correct?  Or are you saying to make w_pre = 15 and w_pos = 35 due to and extra sample for the interpolation.  If it is the latter, can you elaborate on why I need to include an extra sample point for interpolation?  Thanks.

**Comment by ferchaure** [comment]
You are right about the effect of the alignment, (if the all the waveform is inside the segment)

I was talking about add 2 extra samples to the original spikes, to be totally safe of any border effect of the interpolation. If you want to use interpolate spikes of 48 samples in Wave_clus it's safer load raw spikes of 2+48+2 samples.

**Comment by qualiaMachine** [comment]
"You are right about the effect of the alignment, (It's fine if all the waveform is inside the segment)"
To clarify, by segment, do you mean the points formed from w_pre and w_post, or do you mean the interpolation window size?  The peaks of all waveforms are quite likely to reside in the interpolation window size (centered around w_pre), but not the entire waveforms.  The waveforms, however, are nearly fully specified by the sample points I handed the algorithm (i.e. plotting all points from 1 to wpre+w_post yields roughly ten points prior to the rise of the peak/A.P., the trough from the refractory period, and a few sample points at resting state).

"I was talking about add 2 extra samples to the original spikes, to be totally safe of any border effect of the interpolation. If you want to use interpolate spikes of 48 samples in Wave_clus it's safer load raw spikes of 2+48+2 samples."
So once more to ensure I have this correct.... if your original detection method extracts 48 samples with the fifteenth sample as the spike event, you should go back and add 4 samples to this extracted waveform (+2 prespike and +2 post spike) prior to feeding the spikes to wave_clus for interpolation.  After adding additional samples, the w_pre variable should be set to 17 (i.e. 15+2) and your w_post variable set to 35 (i.e. 52-17).  Is that correct?

One final thought... given that my waveforms are already extracted to include a few resting state sample points pre-A.P. and post-refractory period, I think I should be able to avoid adding additional sample points to the waveform for interpolation purposes.

**Comment by ferchaure** [comment]
> The waveforms, however, are nearly fully specified by the sample points I handed the algorithm 

Ok, that is the real requirement 

> After adding additional samples, the w_pre variable should be set to 17 (i.e. 15+2) and your w_post variable set to 35 (i.e. 52-17). Is that correct?

No, at this point you have to use pre=15 and pos=33  . The algorithm will remove the extra samples, you only need them for the interpolation

>  I think I should be able to avoid adding additional sample points to the waveform for interpolation purposes.

You can do it,  if the signal doesn't have a lot of noise and the peak is quite clear.

**Comment by qualiaMachine** [comment]
Got it, thank you!  You've been very helpful!
