### ISSUE TITLE
Wave_clus on Mac

### ISSUE THREAD

**Issue by mrezak** [csn-le/wave_clus#30]
I noticed that Wave_clus uses a bunch on .exe files (ClusterXX.exe) for the clustering part. There is a file named 'cluster_mac.exe' which I suppose is to use with Mac but the .exe file type can only run in windows OS and not Mac. I am a bit confused about this, how can I get wave_clus run on Mac?

**Comment by ferchaure** [comment]
Yes, you can run 'cluster_mac.exe' in a Mac. The extension is only the name, the file was compiled for Mac.

**Comment by mrezak** [comment]
You are right and I could get it working on Mac. Thank you for the prompt and helpful answer.
