### ISSUE TITLE
TDT tank or NEX files to open

### ISSUE THREAD

**Issue by mndiguilmi** [csn-le/wave_clus#31]
Hi

I’m acquiring multichannel recordings with TDT devices and I obtain a TDT Tank. I want to use wave_clus for spike sorting. I read in the Wave_clus pdf that there is possible to open this tank but when I try to do it, I have this message:  

>> parse_data_tdt('C:\Users\Mariano\Desktop\1_tirar\1a');
Maximum possible array:                 3965 MB (4.157e+009 bytes) *
Memory available for all arrays:        3965 MB (4.157e+009 bytes) *
Memory used by MATLAB:                   442 MB (4.632e+008 bytes)
Physical Memory (RAM):                  8071 MB (8.463e+009 bytes)

*  Limited by System Memory (physical + swap file) available.
??? Error using ==> parse_data_tdt at 46
Error opening block

I have another possibility exporting the tank as Neuronexus file and then open it in Matlab with a routine (http://www.neuroexplorer.com/downloadspage/). In the second case, I can see the information but I don’t know how to use it in order to run wave_clus.

Could you help me? I can send a tank and a neuronexus file if it’s necessary.
Best
Mariano

**Comment by ferchaure** [comment]
You don't have enough ram for that method. 
If you can load the signal in matlab: for each channel make a .mat file (the name isn't important) with the signal inside a variable called "data"
