### ISSUE TITLE
Issue with manual selection

### ISSUE THREAD

**Issue by neurotime** [csn-le/wave_clus#32]
Our lab has been using WaveClus for some time, and we love it! But I'm having an issue trying to use the manual selection tool. Maybe I'm missing something simple, but I can't get it to work. I don't see any references in the documentation -- what am I missing? I've tried all the different tools I can find, but cannot draw a rectangle and get it to form a new cluster. I don't get any error messages, but nothing happens. (There are definitely extrema inside the area I'm trying to outline.)

What am I missing here? Can you maybe provide a step-by-step of how this tool should be used?

Thanks!

**Comment by ferchaure** [comment]
Did you read the issue #26 ? Probably there is all the information you need

**Comment by neurotime** [comment]
Thanks for your reply! I did read that issue as well, and I understand what the Manual function should be doing. My problem is simply that I can't get it to work. I want to make sure that I'm using the GUI properly versus this being an actual bug. 

When I click on the "Manual" button for a cluster, drawing a rectangle does nothing. Can you provide the actual steps you do to make this work?

**Comment by ferchaure** [comment]
are you using the latest version in the repository?

The steps are quite simple:
1. Open the Wave_clus gui.
2. Load a file.
3. Click the 'manual' button below a cluster (the mouse will take a + shape).
4. Select a rectangle  that include a local extrema, in the axes above the pressed button.
5. A new cluster will appear after the last cluster.

**Comment by ferchaure** [comment]
maybe a mouse issue? If you do double-click before make a rectangle with local extrema inside, is like cancel the selection.

**Comment by neurotime** [comment]
Hello,

Sorry for my long delay in replying.

This is not an issue of me double-clicking and cancelling. When I click the "Manual" button, the mouse does not become a +, and I am unable to select anything.  It seems like this function isn't working for me. I have the recent version. 

Let me know how I can fix this!

**Comment by neurotime** [comment]
Also, after testing a bit it looks like the function "manual_clus_button_Callback" is never actually called, so my mouse-click is lost there somewhere...

**Comment by neurotime** [comment]
So after some testing, I think I've found the problem... 

In function manual_clus_button_Callback, getrect() is never evaluated (I reach the else statement with the eval on line 718, but nothing happens). 

        if cl == -1
            rect = getrect(handles_local.projections);
            valids = ~USER_DATA{15}(:); %First, I don't select the rejected
        else
            eval(['rect = getrect(handles_local.spikes' num2str(cl) ');']);
            valids = ~USER_DATA{15}(:) & (classes(:)==cl); %First, I don't select the rejected
        end

It reaches that else statement but no user mouse change for me, and if I try to draw a rectangle anyway nothing happens. 

Thanks for your help!

**Comment by ferchaure** [comment]
Sorry,  but at the moment, it's the only way to use the manual button. I will try to use another function but it doesn't look like an easy fix.

**Comment by neurotime** [comment]
Ah ok. I can make a workaround that involves leaving WC, splitting the cluster in my own script and then reloading WC, but I don't think that will preserve temperature info so I could then manipulate the new cluster back in the GUI. let me know if you find a way around it, or if you have any advice on how to do an external manual step and keep the cluster WC-GUI-friendly once reloaded!

**Comment by ferchaure** [comment]
The blank temperature window, it could be because WC didn't find the `data_*dg_01*`  files. Try to not rename the times.mat file.
