### ISSUE TITLE
Loading data to GUI from Matlab script

### ISSUE THREAD

**Issue by jeamtx** [csn-le/wave_clus#33]
Hello,

I am trying to automatize my code as much as possible, however, from time to time I will need to change the temperature when running in batch mode. What is the best way to automatically load a given 'times_.....mat' file to the GUI so when it opens (by just adding wave_clus() in a line of my script) there is no need to click on Load and search for the file?

Thank you,
Enrique

**Comment by ferchaure** [comment]
It's a cool feature I will try to do something like that in the next commit.
The best way to do that is using an argument in the call of wave_clus to execute the 
load_data_button_Callback function with an argument that remove the call to uigetfile. I don't know the details, but should be possible.

**Comment by ferchaure** [comment]
Done, in this commit I added this new feature. You can use `wave_clus(filename) ` for open the gui and load a file automatically.
