### ISSUE TITLE
Error importing .nse file

### ISSUE THREAD

**Issue by mahagonx** [csn-le/wave_clus#34]
Hi

I recorded spike data saved as .nse. The import works with FieldTrip but not wave_clus. How can I fix this issue? Should I import with FieldTrip instead and reformat to a wave_clus compatible .mat file (if yes, how should it be structured)? The full MATLAB error message is at the end (using GUI). You can download an example file from here:
https://www.dropbox.com/s/yt9wgqpr4r07o6j/sPHL1.nse (12MB)
As reference: When using FieldTrip
spike = ft_read_spike('sPHL1.nse','spikeformat','neuralynx_nse');
shows that 110380 spikes are detected in that channel.

Thanks a lot for help!
Matthias

I use the latest wave_clus download from GitHub and Matlab 2016b.

-------------------------------------------
Error using nse_wc_reader
Too many input arguments.

Error in readInData (line 97)
                obj.file_reader = eval([ext(2:end) '_wc_reader(obj.par,obj.par.filename)']);

Error in wave_clus>load_data_button_Callback (line 160)
data_handler = readInData(handles.par);

Error in gui_mainfcn (line 95)
        feval(varargin{:});

Error in wave_clus (line 63)
    gui_mainfcn(gui_State, varargin{:});
 
Error while evaluating UIControl Callback

**Comment by ferchaure** [comment]
To be honest the support for that format is broken, and we will remove it in a few commits. I'm thinking about ask for FieldTrip (or similar, let me know if you try other tools) as a new way to open the files.
Make a file with a variable spikes inside with size(spikes,1)='number of spikes' and 'size(spikes,2)= 'length of the spikes'. And then open it with wave_clus
Remember to make the spikes with extra samples, at least two in each direction, to avoid border effects when Wave_clus interpolate them. For more info read #29

**Comment by mahagonx** [comment]
Dear Fernando
Thank you for your quick reply. I appended and prepended two zeros at the start and end, and saved the 'spikes' matrix [110380x36] as test.mat and tried opening it with wave_clus. It seems to detect less than 15 spikes (Error message below). I assume this is because I did not provide a par structure (I think so, because the same error occurs if I saved the spikes variable from your sample data without the other variables and try to open it). So I constructed a par structure from the little information I have, but still no success.

`spikeImport = ft_read_spike('sPHL1.nse');
spikes      = squeeze(spikeImport.waveform{1}(1,:,:))';
spikes      = [zeros(size(spikes,1),2) spikes zeros(size(spikes,1),2)];
par.w_pre   = 10;
par.w_post  = size(spikes,2)-4-par.w_pre;
par.fmin    = min(spikes(:));
par.fmax    = max(spikes(:));
save test.mat spikes par`

What am I missing? Thank you for further assistance
Matthias

The data contains spikes:
![spikes](https://cloud.githubusercontent.com/assets/9224723/24257695/d299d156-0feb-11e7-90ae-b29c3b4891b6.PNG)


---------------------------------------------------------------
Error using wave_clus>load_data_button_Callback (line 204)
Less than 15 spikes detected

Error in gui_mainfcn (line 95)
        feval(varargin{:});

Error in wave_clus (line 63)
    gui_mainfcn(gui_State, varargin{:});
 
Error while evaluating UIControl Callback

**Comment by ferchaure** [comment]
Sorry I forgot to tell you to add a variable **index** with the times in ms in the file.

The idea isn't add zeros to the spikes, if you have only 32 samples is better if you make a file called test_spikes.mat with the **index** and  **spikes** variables (without the extra samples). For that file: w_pre=10 and w_post=22

**Comment by mahagonx** [comment]
Thanks again. It's almost working (I hope). wave_clus is now stuck with "Calculating spike features..." until an error occurs (see below). I tried several ways to specify **index**, but none worked so far. Thanks for advice and your patience.

---------------------------------------------------------------
Nonfinite endpoints or increment for colon operator in index.

Error in wave_features (line 39)
        coeff(1:inputs)=ind(ls:-1:ls-inputs+1);

Error in wave_clus>load_data_button_Callback (line 208)
    [inspk] = wave_features(spikes,handles.par);                 %Extract spike features.

Error in gui_mainfcn (line 95)
        feval(varargin{:});

Error in wave_clus (line 63)
    gui_mainfcn(gui_State, varargin{:});
 
Error while evaluating UIControl Callback

**Comment by ferchaure** [comment]
The index variable is ok, something odd is happening with the parameters. Did you change the parameter inputs? It should be a number from 1 to 32

**Comment by mahagonx** [comment]
Apparently I am misspecifying the variables. Could you please provide a complete list of the variables and fields that should be contained, together with a description? So far I've got:
spikes - [n x t] matrix containing the waves
index - [n x t] matrix, containing time in ms for each wave
par.w_pre = 10 - which I guessed from the plot
par.w_post = 22 - total time minus w_pre
par.fmin
par.fmax

What else do I need? where do I specify the parameter inputs 1:32?

Thanks

**Comment by ferchaure** [comment]
index  - [n x 1] 

you can't define the detection parameters (like fmin) because you already have the spikes. The rest of the parameters should be loaded from the set_parameters... I'm not sure about what happened with par.inputs but its value should be 10

**Comment by mahagonx** [comment]
Still same error. I attached the file. What is going on?

spikeImport = ft_read_spike( 'sPHL1.nse');
spikes      = squeeze(spikeImport.waveform{1}(1,:,:))';
par         = set_parameters;
par.w_pre   = 10;
par.w_post  = size(spikes,2)-par.w_pre;
par.inputs = 10;

Fs          = 32000;
index       = linspace(0,size(spikes,2)/Fs,size(spikes,2))';

save test_spikes.mat spikes par index

https://www.dropbox.com/s/poves3tqhh9r306/test_spikes.mat

**Comment by ferchaure** [comment]
You were right, I forgot to tell you add this parameter:
par.channels = 1   (that will be the default in the next commit)

About the index vector, It should be the times in ms of the spikes ( with size 110380x1)

**Comment by mahagonx** [comment]
Thank you, sir! It works nicely now.
Below is my code, in case someone else has this issue:

hdr         = ft_read_header([folder with lfp channels and Events.nev]);
spikeImport = ft_read_spike( [folder with spike channels]'\sPHL1.nse');
spikes      = squeeze(spikeImport.waveform{1}(1,:,:))';
par         = set_parameters;
par.w_pre   = 10;
par.w_post  = size(spikes,2)-par.w_pre;
par.channels = 1;

Fs          = spikeImport.hdr.SamplingFrequency;
index       = double((spikeImport.timestamp{1}-spikeImport.hdr.FirstTimeStamp)/hdr.TimeStampPerSample/hdr.Fs);

save test_spikes.mat spikes par index


![spikes2](https://cloud.githubusercontent.com/assets/9224723/24298395/3209d324-10a6-11e7-8d1c-c1bd8f309602.PNG)

**Comment by hoycw** [comment]
Hi all,

First off, thanks for this thread! I was struggling to get .nse files into wave_clus, so this was a big help (just as you suspected @mahagonx!). Since others might also run into this, I wanted to add a few points:

- The code in @mahagonx 's last post has a bug- the conversion to double should happen before converting to ms, otherwise you get all zeros. So it should read:
`index = double((spikeImport.timestamp{1}-spikeImport.hdr.FirstTimeStamp))/hdr.TimeStampPerSample/hdr.Fs;`

- par.w_pre can be read from the .nse hdr (spikeImport.hdr.AlignmentPt), which might be important given the Neuralynx default is 8, not 10.

- @ferchaure it might be nice to mention on the wiki what is needed for .mat input files, though hopefully people can figure it out if they see this thread. (Or maybe I missed that bit of documentation somewhere?)

Cheers,
Colin

**Comment by ferchaure** [comment]
Hi @hoycw, we know that the wiki needs a like of work. Do you think that the first paragraph of [Input-Files](https://github.com/csn-le/wave_clus/wiki/Input-Files) need more information? I tried to keep it simple, but maybe is not clear enough.

**Comment by hoycw** [comment]
Oh! One other bug from @mahagonx 's code above: the index times there are in sec, so should be multiplied by 1000 to convert to ms. Otherwise you'll have some _really_ fast spiking units ;)

Haha fair enough @ferchaure , maybe a big enough project to justify leaving it for a big overhaul later. That paragraph is good, though I would add that the times should be in ms (see my mistake above). The only other thing would be maybe a warning to check that the parameters fit your .nse data, since the import functions can't check against the header in the case of .mat files.

Thanks again to you two for the code snippet to make this work! Too bad the filtering was somehow accidentally set to 1-1000 Hz on my .ncs files and I have to use the more contaminated .nse files for this patient, but as they say, collect good data and you won't have to try to fix it later!
