### ISSUE TITLE
Batch files

### ISSUE THREAD

**Issue by neuroclef** [csn-le/wave_clus#37]
I am not really understanding the batch files option. I am recording with a multi-electrode array and would like to run spike detection on all of my electrode with a set SD for the entire array.  The voltage data from each electrode is saved in a .mat file with a variable known as "data." I'd like to run spike detect on the .mat files saved in the directory.  Can this be done with the batch files and how?

**Comment by ferchaure** [comment]
For example, if you have 2 tetrodes, 
1) Create a files polytrode1.txt with a list of the files in the first tetrode:

> ch1.mat
> ch2.mat
> ch3.mat
> ch4.mat

And a similar polytrode2.txt for the another one.
2) run ` Get_spikes_pol(1:2)`
3) run ` Do_clustering(1:2)`
Done

**Comment by neuroclef** [comment]
Thanks
