### ISSUE TITLE
Batch processing of Do_clustering

### ISSUE THREAD

**Issue by MBLH** [csn-le/wave_clus#4]
When I perform Do_clustering for each single plytrode, the procesing seems successfully completed
as follows.

> > Do_clustering(1);
> > 0 of 1 'times' files finished.
> > Computations Done. Creating figures...
> > 1  
> >  Do_clustering(2);
> > 1 of 1 'times' files finished.
> > Computations Done. Creating figures...
> > 1  
> >  Do_clustering(3);
> > 1 of 1 'times' files finished.
> > Computations Done. Creating figures...
> > 1  
> > Do_clustering(4);
> > 0 of 1 'times' files finished.
> > Computations Done. Creating figures...
> > 1  
> >  Do_clustering(4);
> > 0 of 1 'times' files finished.
> > Computations Done. Creating figures...
> > ## 1  
> > 
> > But when I am try to do the same in batch mode,
> > some warning came up. Do you know why?
> > 
> > Do_clustering(1:4);
> > Warning: File not found or permission denied
> > In run_cluster at 105
> >   In Do_clustering>do_clustering_single at 419
> >   In Do_clustering>(parfor body) at 131
> >   In parallel_function>make_general_channel/channel_general at 922
> >   In remoteParallelFunction at 28 
> > 0 of 4 'times' files finished.
> > Warning: File 'data_polytrode2.dg_01.lab' not found.
> > In run_cluster at 8
> >   In Do_clustering>do_clustering_single at 419
> >   In Do_clustering>(parfor body) at 131
> >   In parallel_function>make_general_channel/channel_general at 922
> >   In remoteParallelFunction at 28 
> > Warning: File 'data_polytrode2.dg_01' not found.
> > In run_cluster at 9
> >   In Do_clustering>do_clustering_single at 419
> >   In Do_clustering>(parfor body) at 131
> >   In parallel_function>make_general_channel/channel_general at 922
> >   In remoteParallelFunction at 28 
> > 0 of 4 'times' files finished.
> > 0 of 4 'times' files finished.
> > Warning: File 'data_polytrode1.dg_01.lab' not found.
> > In run_cluster at 8
> >   In Do_clustering>do_clustering_single at 419
> >   In Do_clustering>(parfor body) at 131
> >   In parallel_function>make_general_channel/channel_general at 922
> >   In remoteParallelFunction at 28 
> > Warning: File 'data_polytrode1.dg_01' not found.
> > In run_cluster at 9
> >   In Do_clustering>do_clustering_single at 419
> >   In Do_clustering>(parfor body) at 131
> >   In parallel_function>make_general_channel/channel_general at 922
> >   In remoteParallelFunction at 28 
> > 0 of 4 'times' files finished.
> > Computations Done. Creating figures...
> > 1 2 3 4

**Comment by ferchaure** [comment]
Did you try with only the politrodesX_spikes.mat in the folder?
Have you another folder with  'data_polytrode1.dg_01' in your path?

**Comment by ferchaure** [comment]
Are you using a UNIX system? It could be related to the permissions in the executable files.

**Comment by MBLH** [comment]
I don't know why, but it started working, so I don't have this problem currently.
I am sorry not to respond to your comment for long time,
but thank you very much!
