### ISSUE TITLE
overlapping spikes

### ISSUE THREAD

**Issue by jtbirmingham** [csn-le/wave_clus#41]
Hi -

Is the algorithm designed to accommodate overlapping spikes?  
I attached a picture showing an extracellular recording and the identified clusters.  (There's a shoulder cluster associated with the short spikes, but that's another matter.)  Having trouble when the tall and short spikes overlap.

2nd figure is the wave_clus output.  Colors corresponding to those in first figure.

![spikes and clusters](https://user-images.githubusercontent.com/29710381/27549219-29dd44c6-5a50-11e7-9442-74a9729e016d.jpg)
![wave_clus output](https://user-images.githubusercontent.com/29710381/27549293-5919937a-5a50-11e7-9aa4-fdfa2f9d2e31.jpg)

Thank you! 
john
jbirmingham@scu.edu

**Comment by ferchaure** [comment]
Sorry, but Wave_clus doesn't handle overlapping spikes.
If you want to detect both of them you can reduce the value of par.ref_ms (1.5 ms by default). Even though Wave_clus won't sort them correctly.

**Comment by jtbirmingham** [comment]
Thank you; that was my fear.  

I'm just wondering...aren't overlapping spikes, in general, an issue in spike sorting?  Ultimately I am trying to sort much busier spike trains (or at least identify the spikes I want), e.g.

![pyloric](https://user-images.githubusercontent.com/29710381/27550623-3d158558-5a55-11e7-958b-f79b6a5dd139.JPG)

Do you have any advice/suggestions on approaches to pursue or research?  If I am going to start from scratch I would do something simple (and likely naive) like PCA plus some subtractions and to hope that a simple superposition was at work.  

Thank you again!  
John

**Comment by ferchaure** [comment]
Yes, they are a quite an issue. But for some applications, where the overlapping spikes are uncommon, they aren't a priority. 

I remember some work about this topic, where it had been checked that the superposition is linear. In theory you could try to decompose each overlapped waveform in a summation of N know waveforms. 
But in practice this idea isn't so simple. Have in mind that, in general, any decomposition will have less certainty than a normal sorting.

**Comment by jtbirmingham** [comment]
Thanks for all your assistance!
