### ISSUE TITLE
sorting error

### ISSUE THREAD

**Issue by dragospekic** [csn-le/wave_clus#42]
I am sorting some spikes using Wave_Clus and came across an error. I ‘fixed’ cluster 1 and then tried to force into clusters 2 and 3 as on the screenshot below and got:
Could you please help.
todor

Index exceeds matrix dimensions.

Error in plot_spikes (line 178)
        oclass = clustering_results(ind(1),4); % get original
        class

Error in wave_clus>force_button_Callback (line 1163)
plot_spikes(handles);

Error in gui_mainfcn (line 95)
        feval(varargin{:});

Error in wave_clus (line 61)
    gui_mainfcn(gui_State, varargin{:});

Error while evaluating UIControl Callback.

**Comment by ferchaure** [comment]
I can't follow the issue, because I don't know which version of the code you are using. Could you please download the [latest version from the repository](https://github.com/csn-le/wave_clus/archive/testing.zip)?

**Comment by dragospekic** [comment]
thanks, I downloaded it and the problem goes away! ; )
