### ISSUE TITLE
error nan and inf not allowed.

### ISSUE THREAD

**Issue by dragospekic** [csn-le/wave_clus#43]
Hi Fernando, I am trying to load a data.mat file using your latests Wave_clus version and get the following message. I've checked the file and it doesn't contain any inf or NaNs. In fact the file sorted with a previous version of Wave_clus ( wave_clus_2.0wb). I wonder if I've messed up the parameter file?..
![capture](https://user-images.githubusercontent.com/29750937/28124659-41155ac4-671c-11e7-82a3-37330807c250.PNG)
Thanks a lot!
Todor

**Comment by ferchaure** [comment]
Yes, probably an issue with the parameters, check the values you used for:
segments_length
tmin
tmax

**Comment by dragospekic** [comment]
this is what I have:

par.segments_length = 5;             % length (in minutes) of segments in which the data is cutted (default 5min).              
% DETECTION PARAMETERS                                                                                                          
par.tmax = 'all';                    % maximum time to load                                                                     
%par.tmax= 180;                      % maximum time to load (in sec)                                                            
par.tmin= 0;

**Comment by ferchaure** [comment]
Did you store the signal in a variable called "data"?
Which par.sr value are you using?  Did you include a "sr" variable inside the data file?

**Comment by dragospekic** [comment]
hi Fernando, yes it's a horizontal vector called data.mat. I don't have a sampling rate variable inside the data.mat file. instead I set the parameter file to the correct sampling rate (20kHZ in my case).

**Comment by ferchaure** [comment]
Ok, but the file is called data.mat, how is the variable inside called?

**Comment by dragospekic** [comment]
its also called 'data'.

**Comment by ferchaure** [comment]
Can you try in matlab, inside the folder with your data file:
data_info = whos('-file','data.mat','data');
data_info.size

**Comment by dragospekic** [comment]
HI Fernando,
here is the data_info:
data_info = 

  struct with fields:

          name: 'data'
          size: [1 54664000]
         bytes: 437312000
         class: 'double'
        global: 0
        sparse: 0
       complex: 0
       nesting: [1×1 struct]
    persistent: 0

**Comment by ferchaure** [comment]
It doesn't make sense... can you check that par.sr is not 0 in set_parameters.
Is it happening with this file only?
Could you show me all the output of: 
whos('-file','data.mat')

**Comment by dragospekic** [comment]
This is the output for data.mat.

whos('-file','data.mat')
--

  Name      Size                      Bytes  Class     Attributes

  data      1x54932000            439456000  double     

and here is the parameter info:
                                                                                                                                 
% LOAD PARAMS                                                                                                                    
par.segments_length = 1;             % length (in minutes) of segments in which the data is cutted (default 5min).               
par.sr = 20000;                      % sampling rate (in Hz). This parameter will be only used if the data file don't have a sr. 
               
I wonder if this is a Matlab2017 issue or some other silly thing I am doing. Just to check, my data folder contains only the file data.mat and when I open wave_clus, I go through load data --> and choose the data.mat.

**Comment by dragospekic** [comment]
This is my full parameter setting:

                                                                                                                                 
% LOAD PARAMS                                                                                                                    
par.segments_length = 1;             % length (in minutes) of segments in which the data is cutted (default 5min).               
par.sr = 20000;                      % sampling rate (in Hz). This parameter will be only used if the data file don't have a sr. 
                                                                                                                                 
                                                                                                                                 
% PLOTTING PARAMETERS                                                                                                            
par.cont_segment = true;                                                                                                         
par.max_spikes_plot = 2000;          % max. number of spikes to be plotted                                                       
par.print2file = true;               % If is not true, print the figure (only for batch scripts).                                
par.cont_plot_samples = 100000;      % number of samples used in the one-minute (maximum) sample of continuous data to plot.     
par.to_plot_std = 1;                 % # of std from mean to plot.                                                               
                                                                                                                                 
                                                                                                                                 
% SPC PARAMETERS                                                                                                                 
par.mintemp = 0.00;                  % minimum temperature for SPC                                                               
par.maxtemp = 0.201;                 % maximum temperature for SPC                                                               
par.tempstep = 0.01;                 % temperature steps                                                                         
par.SWCycles = 100;                  % SPC iterations for each temperature (default 100)                                         
par.KNearNeighb = 11;                % number of nearest neighbors for SPC                                                       
par.min_clus = 60;                   % minimum size of a cluster (default 60)                                                    
par.min_clus_rel = 0.005;            % minimum cluster size, relative to the total nr. of spikes (only for batch scripts).       
par.max_clus = 33;                   % maximum number of clusters allowed (default 13)                                           
par.randomseed = 0;                  % if 0, random seed is taken as the clock value (default 0)                                 
%par.randomseed = 147;               % If not 0, random seed                                                                     
%par.temp_plot = 'lin';              % temperature plot in linear scale                                                          
par.temp_plot = 'log';               % temperature plot in log scale                                                             
                                                                                                                                 
% DETECTION PARAMETERS                                                                                                           
par.tmax = 'all';                    % maximum time to load                                                                      
%par.tmax= 180;                      % maximum time to load (in sec)                                                             
par.tmin= 0;                         % starting time for loading (in sec)                                                        
par.w_pre = 20;                      % number of pre-event data points stored (default 20)                                       
par.w_post = 44;                     % number of post-event data points stored (default 44))                                     
par.alignment_window = 10;           % number of points around the sample expected to be the maximum                             
par.stdmin = 5;                      % minimum threshold for detection                                                           
par.stdmax = 50;                     % maximum threshold for detection                                                           
par.detect_fmin = 300;               % high pass filter for detection                                                            
par.detect_fmax = 3000;              % low pass filter for detection (default 1000)                                              
par.detect_order = 4;                % filter order for detection                                                                
par.sort_fmin = 300;                 % high pass filter for sorting                                                              
par.sort_fmax = 3000;                % low pass filter for sorting (default 3000)                                                
par.sort_order = 2;                  % filter order for sorting                                                                  
par.ref_ms = 1.5;                    % detector dead time, minimum refractory period (in ms)                                     
% par.detection = 'pos';             % type of threshold                                                                         
par.detection = 'neg';                                                                                                           
%par.detection = 'both';                                                                                                         
par.channels = 1;                                                                                                                
                                                                                                                                 
% INTERPOLATION PARAMETERS                                                                                                       
par.int_factor = 5;                  % interpolation factor                                                                      
par.interpolation = 'y';             % interpolation with cubic splines (default)                                                
% par.interpolation = 'n';                                                                                                       
                                                                                                                                 
% FEATURES PARAMETERS                                                                                                            
par.inputs = 10;                       % number of inputs to the clustering                                                      
par.scales = 4;                        % number of scales for the wavelet decomposition                                          
par.features = 'wav';                % type of feature ('wav' or 'pca')                                                          
%par.features = 'pca'                                                                                                            
                                                                                                                                 
% FORCE MEMBERSHIP PARAMETERS                                                                                                    
par.template_sdnum = 3;             % max radius of cluster in std devs.                                                         
par.template_k = 10;                % # of nearest neighbors                                                                     
par.template_k_min = 10;            % min # of nn for vote                                                                       
%par.template_type = 'mahal';       % nn, center, ml, mahal                                                                      
par.template_type = 'center';       % nn, center, ml, mahal                                                                      
par.force_feature = 'spk';          % feature use for forcing (whole spike shape)                                                
%par.force_feature = 'wav';         % feature use for forcing (wavelet coefficients).                                            
par.force_auto = true;              %automatically force membership (only for batch scripts).                                    
                                                                                                                                 
% TEMPLATE MATCHING                                                                                                              
par.match = 'y';                    % for template matching                                                                      
%par.match = 'n';                   % for no template matching                                                                   
par.max_spk = 20000;                % max. # of spikes before starting templ. match.                                             
par.permut = 'y';                   % for selection of random 'par.max_spk' spikes before starting templ. match.                 
% par.permut = 'n';                 % for selection of the first 'par.max_spk' spikes before starting templ. match.              
                                                                                                                                 
% HISTOGRAM PARAMETERS                                                                                                           
par.nbins = 100;                    % # of bins for the ISI histograms                                                           
par.bin_step = 1;                   % percentage number of bins to plot

**Comment by dragospekic** [comment]
interestingly if the file is presorted (using a previous version of wave_clus) and I choose open the data_spikes.mat, then it opens without any problems...

**Comment by dragospekic** [comment]
Hi Fernando,
 sorry I meant which version of Windows operating system. 
I just downloaded the latest version of wave_clus and still get this error message on that file. I am running
Windows10 Enterprise and my version of Matlab is 2017a. When I load an older version of wave_clus that I have (wave_clus_2.0wb) the file loads without any problems. It must be something really simple but it's really puzzling. As mentioned before the file is an unsorted data.mat file which contains a single horizontal double vector called 'data'.
Sorry to keep bugging you with this.
Cheers
Todor

 
Error using ones
NaN and Inf not allowed.
Error in mat_wc_reader (line 56)
                obj.t0_segments = ones(1,obj.max_segments);
Error in readInData (line 97)
                obj.file_reader = eval([ext(2:end) '_wc_reader(obj.par,obj.par.filename)']);
Error in wave_clus>load_data_button_Callback (line 177)
data_handler = readInData(handles.par);
Error in gui_mainfcn (line 95)
        feval(varargin{:});
Error in wave_clus (line 63)
    gui_mainfcn(gui_State, varargin{:});
 
Error while evaluating UIControl Callback.

**Comment by ferchaure** [comment]
I will try to duplicate everything I can to check this.
In the meanwhile, do you know how to put a breakpoint in the line 50 of mat_wc_reader  and check  why 
 obj.max_segments is NaN or Inf?

**Comment by dragospekic** [comment]
Thanks Fernando, when I put the break on ln. 50, obj.max_segments = [];
However when I put it on ln. 54, (presumably after ln.50 has executed then
obj.max_segments = 7..

**Comment by dragospekic** [comment]
Hi Fernando,
just tried something I guess I should have tried first. My machine is a
dual boot Windows7/Window10. When I boot into Windows7 where I run Matlab
2012, the error message disappears. My Windows10 runs Matlab2017a so it
could be either the operating system or the newer Matlab. I hope this info
is useful for you as you upgrade the code.
Cheers
Todor

**Comment by ferchaure** [comment]
> ln. 50, obj.max_segments = [];
However when I put it on ln. 54, (presumably after ln.50 has executed then
obj.max_segments = 7..

That makes sense because when you are in the line 50 you haven't executed it. 
I have tried wave_clus in Matlab2017a and Windows7 and it works. 

Can you check the next step? I want to know why the line 
> ones(1,obj.max_segments);

doesn't work. Maybe another _ones_ function in your path?

**Comment by dragospekic** [comment]
Hi Fernando, i't not a problem any more. I am just running it from a
Matlab2012 on WIndows7 and there is no problem..

**Comment by dragospekic** [comment]
Hi Fernando,
We have some data which has already been high pass filtered for spike
sorting. Can you let me know if it is possible to turn off the filtering
option of wave_clus. E.g., would that work if I just comment out the
following lines:
par.detect_fmin = 300;               % high pass filter for
detection
par.detect_fmax = 3000;              % low pass filter for detection
(default 1000)
Thanks a lot!
Todor

**Comment by ferchaure** [comment]
Hi Todor

We don't have that option. If you want to do that, you have to edit the file amp_detect (or amp_detect_pol if you are using polytrodes). In that file make the variables _xf_ and _xf_detect_ equal to the input variable _x_. It's a easy modification, let me know if you have any issue.

I will try to remember to add this idea as a new feature in a future commit.
