### ISSUE TITLE
Plot polytrode button unresponsive

### ISSUE THREAD

**Issue by GCamp6** [csn-le/wave_clus#45]
Hi all, the "Plot polytrode" button doesn't work (or at least if I click it does nothing). Maybe I'm using a wrong configuration? I can not figure it out because I have no clue on what I can get with it...

**Comment by ferchaure** [comment]
Are you using polytrode data?

**Comment by GCamp6** [comment]
I have tetrodes but now I load one channel at the time, I did not manage to analyze all the 4 at the same time.
It should work also for the 4 channels?

**Comment by ferchaure** [comment]
If you load only one channel Wave_clus  doesn't have a way to know that you are using polytrodes (for that reason the button do nothing). If you want to detect and sort the spikes using all the channels together:

1. Write  the  name  of  the  files  you  want  to  process  as  polytrode  (in  ascii format) in a text file named as polytrode1.txt. 
2. The spike detection is done by typing in the Matlab command   window   the   batch   file   Get_spikes_pol(1)   which   will   produce   the   output   file  polytrode1_spikes.mat  containing  the  spike  times  and  shapes.  
3. Then load polytrode1_spikes.mat using the GUI.

**Comment by GCamp6** [comment]
Ok thanks for explaining.
I tried in this way:

1. saved each channel in a different file (dataCh1.mat, dataCh2.mat, [...], ..4.mat)
2. created the poltrode1.txt with inside the name of the files (dataCh1.mat dataCh2.mat ...) in ASCII code
3. run in Matlab `Get_spikes_pol(1)`

I get:
```
par = 

      segments_length: 5
                   sr: 20000

[...]

                scales: 4
             features: 'pca'

Error using readInData (line 110)
File type '' isn't supported

Error in Get_spikes_pol>get_spikes_pol_single (line 104)
        data_handler_ch{i} = readInData(par_ch{i});

Error in Get_spikes_pol (line 62)
        get_spikes_pol_single(polytrodes(j), par_input);
```

I'm still missing something in the procedure.

---
PS: in the function file is written to use 

> polytrode**s**N.txt

I tried both names but the error still occurs.

**Comment by greydongilmore** [comment]
Hi,

You should check your file paths. Make sure you do not use spaces in
directory names, also preferably do not use underscores.

For instance... 'C:\documents\Spike Data\datachn1' will produce this error
due to the space between Spike and Data. Get use to combining directory
names and capitalizing the first letter of each new word('spikeData').

Hope this helps,

Greydon

**Comment by ferchaure** [comment]
You are right, ASCII means just plain text.  Sorry for that... that instructions aren't clear.
