### ISSUE TITLE
Loading data problem

### ISSUE THREAD

**Issue by scottespada** [csn-le/wave_clus#46]
Firstly, thanks for providing this great toolbox!!!

Basicly I want to do some spike detection and sorting work. But I have some problem on the begining stage. 

Wave_clus didn't find a sampling rate in file. It will use the set in set_parameters.m
Error using wave_clus>load_data_button_Callback (line 221)
Less than 15 spikes detected

Error in gui_mainfcn (line 95)
        feval(varargin{:});

Error in wave_clus (line 63)
    gui_mainfcn(gui_State, varargin{:});

I guess this is the problem of my input .mat file. I read the introduction pdf and I am kind of confused that I must provide the spike times? So I need provide the result of spike detection into the mat file then I can use the toolbox? Cause right now I only have the single channel data in mat file. 

Sorry I am new guy in this field so maybe I asked many silly questions. Any help will be appreciated!

**Comment by ferchaure** [comment]
If you have the  continuous data, crate a .mat file with the signal in a variable **data** (If you want, you can add a variable **sr** with the sampling rate, otherwise the parameter sr will be use)

**Comment by scottespada** [comment]
Hi,

Thanks for your reply!

I do not think it is the problem of sampling rate setting since there is still this problem happening:

Error using wave_clus>load_data_button_Callback (line 221)
Less than 15 spikes detected

Error in gui_mainfcn (line 95)
        feval(varargin{:});

Error in wave_clus (line 63)
    gui_mainfcn(gui_State, varargin{:});
 
Error while evaluating UIControl Callback

My mat file only has the single channel data and sr information. I noticed that in simulator file you provide also includes the spike time information. Is this the problem? Thanks.

**Comment by ferchaure** [comment]
You don't need the spike times (that's required when you give wave_clus only the spikes already detected).
Maybe you data doesn't have spikes. Did you check the sign of the peak of the spikes in your data? Edit the set_parameters.m file, setting par.detection = 'both'

**Comment by scottespada** [comment]
This is my setting:

% par.detection = 'pos';             % type of threshold                                                                        
par.detection = 'neg';                                                                                                          
%par.detection = 'both';                                                                                                        
par.channels = 1;  

Now I understand this does not require the spike times since I deleted spike times data in the example file and it can be loaded. Maybe I need provide some threshold information? Thanks.

**Comment by ferchaure** [comment]
Only to check the sign of the spikes peak in your data, edit that lines as:
```
% par.detection = 'pos'; % type of threshold
%par.detection = 'neg';
par.detection = 'both';
```
Maybe you have a lot of noise, search in the parameter file and set value:
`par.stdmin = 4; `

**Comment by scottespada** [comment]
Yes! It is solved. I think sometimes I have too much noise. Thanks so much for your help!

Another small question is whenI finish the detection, I can see the spike cluster. But I think the time axis does not match the time length of the spike. So how can I get the value of the spike time length? Thanks.

**Comment by ferchaure** [comment]
Sorry, I don't understand. 
Check the sr value, it should be the sampling rate of your data.

**Comment by scottespada** [comment]
Hi,

Sorry, what I mean is I want to see the time length of the spike I got. The spike wave forms are shown in the second line (called cluster #0,1,2...), but the time axis is from 0-60. Is there something like parameters we can change to see the time length? Thanks.

**Comment by ferchaure** [comment]
This parameters set the length of the waveform:

`par.w_pre = 20;                      % number of pre-event data points stored (default 20 `
`par.w_post = 44;                     % number of post-event data points stored (default 44)) `

**Comment by scottespada** [comment]
Hi, thanks for your reply,

Since I use the default value of these two parameters, so spike time length is (20+44)/20k s? (my sr is 20k Hz) I do not understand this very well because these two parameters are  number of pre/post-event data points stored and I do not know how these can be related to time length of the spike.

Thanks

**Comment by ferchaure** [comment]
Exactly. That are samples and the sampling rate haven't been changed.

**Comment by scottespada** [comment]
Hi,

I am also wondering how many data points this program can process once. I just want to know how long the raw data I can run...

**Comment by ferchaure** [comment]
Usually I process only an hour or two, using a sampling rate of  30 kHz. But You could been able to process even more data-points.

**Comment by scottespada** [comment]
Hi,

I have another question. I noticed that the toolbox can only detect more than 15 spikes.
I am wodering if there is the way to make this number smaller? Or this number has some physical meaning in neural science. Thanks so much!

**Comment by ferchaure** [comment]
We do that because apply the SPC algorithm with that number of spikes is useless. If you use the batch function Get_spikes, you will see that you can detect the spikes, but if you use the GUI or the batch file Do_clustering, both will return that error.

This is only a criteria to remove empty or broken channels. If do search for '15' in the files wave_clus.m or Do_clustering.m is easy to see where you have to change the number.

**Comment by scottespada** [comment]
Hi,

Thanks for your reply again!

I am also curious about the difference the positive detection and both detetion. Generally, could you tell me what is the relationship of spike number result between this two sorting mode, please? Because I got totally different results from these two...Thanks!

**Comment by ferchaure** [comment]
This depends of the waveform of the spikes in your data. If you have both types of spikes (with a single positive or negative peak) you have to use "both" otherwise you are losing spikes. The relationship of spike number result between this two _detection_ mode depends of the waveforms in each particular dataset.

**Comment by scottespada** [comment]
Thanks so much for your explaination!

![1](https://user-images.githubusercontent.com/31420517/31960182-c58915da-b8ab-11e7-81fe-e3eafe68bc65.png)

Another small question is about the plot above (spike cluster), can you tell me how I can change the x-axis from data point number to time (ms or us), please? Thanks!

**Comment by ferchaure** [comment]
Sorry, We don't have an option for that. You have to edit this files: 
plot_spikes.m and plot_spikes_aux.m

Find the lines with this structure:
`plot( ... ,1:ls, ....)
`
And replace **1:ls** with something like:
` linspace(0,(ls-1)*1000/par.sr,ls)
`
 After that you will have the x-axis in ms

**Comment by ferchaure** [comment]
remember to replace lines like:

`xlim(..., [1 ls]);
`
for
`xlim(..., [0 (ls-1)*1000/par.sr]);`

**Comment by adamvonpaternos** [comment]
Hi Fernando, 

I'm having the same initial issue as scottespada where I am receiving the error: 

`Error using wave_clus>load_data_button_Callback (line 221)
Less than 15 spikes detected

Error in gui_mainfcn (line 95)
feval(varargin{:});

Error in wave_clus (line 63)
gui_mainfcn(gui_State, varargin{:});`

- I have tried the solutions that you suggested, however, I am still receiving this error. 
- My setup consists of a file with a variable sr =40000 and a vector of raw data of type double.

**Comment by ferchaure** [comment]
@adamvonpaternos It looks like another issue... did you add the the path with subfolders? why the function is called amp_detext ? did you make your version of  amp_detect?

**Comment by adamvonpaternos** [comment]
The .mat file is in the proper path, but I actually missed the top part of the error:

```
Error using horzcat
Dimensions of matricies bein concatenated are not consistent.

Error in amp_detect (line 106)
xf = [xf zeros(1, w_post)];
```

**Comment by ferchaure** [comment]
please, transpose the vector 'data' in your .mat file and tell me if  that works.

**Comment by adamvonpaternos** [comment]
Yep, that was the issue. It wanted a row vector instead of a column vector. 
Thanks for your help!

**Comment by Amir-Alizadeh** [comment]
Hi, 

I read this thread here. I am using wave_clus sample data and still getting that "Less than 15 spikes detected" error. 
Any suggestions?
