### ISSUE TITLE
Problems using TDT

### ISSUE THREAD

**Issue by Min-SooKANG** [csn-le/wave_clus#47]
Hi, I'm a new user trying to analyze my data with wave_clus.

I'm having trouble from the start. I have a few questions about the problems.

1. It seems that wave_clus only supports data with 1 channel, but my data has more! So I tried to use the parse_data_tdt function, but it won't work due to the availability of memory.  Is there a solution to this because in the future I'll be analyzing a much bigger data than this.

2. As 1 didn't work, I tried splitting up data into channels in ASCII format. But wave_clus acquires only .mat files, so I'm trying to convert it to an appropriate format. In the introduction, it says that it should be in a vector named data (this is where I don't get, what does this mean?)

3. Also I tried using Raw_data_reader for TDT files but I don't get what input I should write for the function. (The function , tdtch_wc_reader(par, raw_filename), what should I put in par?)

I would be glad to have help on these problems!

**Comment by ferchaure** [comment]
**1.** Sorry that's the only automatic way we used to load TDT data. If you can open the data using another tool, save the signal in a .mat file.
**2.** Maybe is not clear in the documentation. You have to save the raw signal in a mat file, inside a vector called _data_. The variable _data_ could be a vector of doubles
**3** That's an internal function, to use only only with the parse_data_tdt function.

**Comment by Min-SooKANG** [comment]
Thanks for the help! I extracted my own file and successfully applied it to wave_clus.

I have a extra question, as I understand the optimal temperature should be calculated automatically.

But I'm not sure if the temperature that is shown in the GUI after clustering is the optimal one. Is there another function that automatically calculates it?

**Comment by ferchaure** [comment]
Hi,  That is the _kind of_ the optimal temperature,  if you use only one. But the best option is to use multiple temperatures. I'm working in a way to do it automatically.... for now you have to explore the temperature map manually.
