### ISSUE TITLE
polytrodes1.txt issue

### ISSUE THREAD

**Issue by Min-SooKANG** [csn-le/wave_clus#48]
Hi. I'm trying to process my data using Get_spike_pol function.

In the instruction, it says to make a textfile named polytrodes1.txt with .mat files to concatenate.

I wonder where this textfile should be located for the matlab function to work.

Where should I put it?

**Comment by ferchaure** [comment]
the mat files and  the textfile should be in the same folder.
The documentation in the file isn't correct, the file should be named polytrodeN.txt
