### ISSUE TITLE
Question:  source code for "cluster.exe"

### ISSUE THREAD

**Issue by chenxinfeng4** [csn-le/wave_clus#49]
In order to implant **SPC algorithms to MClust**, and **speed-up SPC** for huge-spikes-data. So, I'm desiring the source code for "cluster.exe".

**Comment by ferchaure** [comment]
Sorry, We don't have permission to publish the source code

**Comment by chenxinfeng4** [comment]
I'm a postgraduate in behavioral neurosciences. **Would you tell me where to contact the author for permission?** I'm not commercial purposing, but for academic researching.

The SPC algorithm has been described detailly in published work *"RQ Quiroga, 2004, Unsupervised Spike Detection and Sorting with Wavelets and Superparamagnetic Clustering"*, which recommended me to use WAVE_CLUS. I suggest there is no need to CLOSE the code for SPC algorithm.

What's more, you should be aware that **"Cluster_64.exe" is very time-consumptive**, it takes 4-20min to cluster  10k-100k  spikes. "Cluster_64.exe" seems to be a 32bit application. Intermediate files, such as "data_wc.dg_01*" "tmp_data_wc", are big and annoying. I will try my best **reconstruct the SPC to MEX file**, using vectorization.

**Comment by greydongilmore** [comment]
@chenxinfeng4 Your request and the way you pitched it is extremely rude. First you demand a source code that was developed by Eytan Domani and not the developers of Wave_clus. You then follow it up by saying the performace is inferior and that you want to apply it to a completely different toolbox! 

I had to jump in on this request, I have used Wave_clus for a long time and love this toolbox.

**Comment by chenxinfeng4** [comment]
SORRY for my rude behavior. Something I have to explain.
First, I DON'T KNOW where the 'cluster.exe' is from. Second,  my expression above may be rude, but is true, not a lie nor threaten. Third, I have used Wave_clus for a long time and love it, as well as the MClust (full source opened).  You love it, you promote it, then more people will love it.

**Comment by jniediek** [comment]
@chenxinfeng4 (sorry for jumping in!), just in case you are unaware of some publications relevant to your question:

- Blatt, M., Wiseman, S., and Domany, E. (1996). Superparamagnetic clustering of data. Phys. Rev. Lett. 76, 3251–3254.
- Blatt, M., Wiseman, S., and Domany, E. (1997). Data clustering using a model granular magnet. Neural Computation 9, 1805–1842.
- Wiseman, S., Blatt, M., and Domany, E. (1998). Superparamagnetic clustering of data. Phys. Rev. E 57, 3767–3783.

**Comment by chenxinfeng4** [comment]
@jniediek Thank you for your reply. Although I'm fear of the profound math, I will try my best to read these papers. 
Besides, I just find out that **the MClust4.4 has implanted the similar SPC already**. It seems that MClust-SPC cluster is extremely fast and quality-acceptable. I guess it's fair potential to take this advantage to Wave_clus.
