### ISSUE TITLE
std smaller than default bug ..

### ISSUE THREAD

**Issue by m4loman** [csn-le/wave_clus#5]
Hi there,

when setting std_min smaller than default I sometimes run into the following error:
Do you have any idea why this happens ? 

Subscripted assignment dimension mismatch.

Error in plot_spikes (line 216)
clustering_results(:,2) = classes;

Error in wave_clus>load_data_button_Callback (line 331)
plot_spikes(handles); %This function edit userdata

Error in gui_mainfcn (line 95)
        feval(varargin{:});

Error in wave_clus (line 63)
    gui_mainfcn(gui_State, varargin{:});
 
Error while evaluating UIControl Callback

**Comment by ferchaure** [comment]
Hi, I didn't see that specific problem before.
Which par.permut are you using?
Did you process the data with the batch files or directly in the GUI?
Could you please add:

> size(clustering_results(:,2) )
> size(classes)

before the line 216 of plot_spikes.m and tell me the output?

**Comment by m4loman** [comment]
par.permut was set to y

output is [109919  1] and [109920 1]

**Comment by ferchaure** [comment]
Are you using the newest version from: [https://github.com/csn-le/wave_clus](https://github.com/csn-le/wave_clus) ?
