### ISSUE TITLE
batch processing

### ISSUE THREAD

**Issue by hanyanhanyan** [csn-le/wave_clus#51]
Hi,
1. I was reading the batch processing comments, it says:

'all', in this case the functions will process all the
%                   supported files in the folder (except .mat files).

Does that mean the batch processing could'd do .mat files?
All my data are stored in .mat files.

2. In the: Get_spikes([1:8 33:56],'parallel',true,'par',param); from the example you gave,
what is [1:8 33:56]?

Thanks a lot!

**Comment by greydongilmore** [comment]
For batch, write a .txt file that has the path to your .mat files. Wave_clus batch functions take this .txt file as an input and will cycle though all the .mat file paths.

**Comment by hanyanhanyan** [comment]
Thanks for replying.
I did:
param.stdmin = 4;
param.sr = 30000;
param.detection = 'neg';
Get_spikes('Files.txt','parallel',true,'par',param);

And it got:
>> untitled5
Wave_clus didn't find a sampling rate in file. It will use the set in set_parameters.m
0 of 3 'spikes' files done.
Wave_clus didn't find a sampling rate in file. It will use the set in set_parameters.m
0 of 3 'spikes' files done.
Wave_clus didn't find a sampling rate in file. It will use the set in set_parameters.m
0 of 3 'spikes' files done.

I put three files in the .txt for testing.

**Comment by ferchaure** [comment]
Are the spikes files there? 
Could you show us  the file _Files.txt_

**Comment by hanyanhanyan** [comment]
Hi, the files are continuous raw data. They are perfect fine when I use GUI.
The file.txt look like this:
![screen shot 2017-09-29 at 1 13 33 pm](https://user-images.githubusercontent.com/32147051/31027437-36e9c5aa-a518-11e7-8efe-8c64d1433325.png)

**Comment by ferchaure** [comment]
can you try calling the function from the data's folder and only use the files names of the files in file.txt?

**Comment by hanyanhanyan** [comment]
![screen shot 2017-09-29 at 2 56 44 pm](https://user-images.githubusercontent.com/32147051/31031438-8f910f48-a526-11e7-8a60-07fc0bcf7cfd.png)

Is this what you meant? It seems not working as well.

**Comment by ferchaure** [comment]
you have to add the the path wave_clus with sub-folders. Then in another folder put your data file. Go there  and then call get_spikes with only the name of the file (you don't need the full path).

**Comment by hanyanhanyan** [comment]
![screen shot 2017-09-29 at 3 39 15 pm](https://user-images.githubusercontent.com/32147051/31032984-680ab2fc-a52c-11e7-92a8-5604d6d9dc9a.png)

Great! It works!

Just one more thing, how come the output figure does not have the clustering?

**Comment by hanyanhanyan** [comment]
Never mind! I figured that out!

**Comment by hanyanhanyan** [comment]
Is there a way the batch processing can read everything in a folder without typing in every file's name?

**Comment by ferchaure** [comment]
You can pass a cell of filenames to get_spikes. 
You can make that cell using the _dir_ function with an argument to only list your raw data and then pass a cell of the _name_ field of that variable.

**Comment by hanyanhanyan** [comment]
![screen shot 2017-09-29 at 4 53 42 pm](https://user-images.githubusercontent.com/32147051/31035664-d49ded4e-a536-11e7-879f-f4582d1044c6.png)
 

I tried this way, using dir. Can you tell what's wrong?

**Comment by hanyanhanyan** [comment]
![screen shot 2017-09-29 at 5 34 35 pm](https://user-images.githubusercontent.com/32147051/31036969-8fdbba46-a53c-11e7-90bf-4e4017c90539.png)
![screen shot 2017-09-29 at 5 34 45 pm](https://user-images.githubusercontent.com/32147051/31036970-8fe2e528-a53c-11e7-92cf-3faa99f4191a.png)

My apologies. In my previous comment I didn't put the cell with only names as input. 
Now I did, however it got the same warning: File type ' ' isn't supported.

Those files were working perfect fine when using GUI.

Thanks a lot!

**Comment by ferchaure** [comment]
That is because you put the string _'names'_ as an argument and not the variable _names_

**Comment by hanyanhanyan** [comment]
Thanks Ferchaure!!!

**Comment by cfle** [comment]
Hi, I have done as you have said previously
> you have to add the the path wave_clus with sub-folders. Then in another folder put your data file. Go there and then call get_spikes with only the name of the file (you don't need the full path).

but I am using ncs files instead. However I keep getting this error message:
![wave_clus error](https://user-images.githubusercontent.com/34517114/33950755-1a921522-e025-11e7-8264-c6759b9e520e.PNG)
Do you have any ideas as to what is going on?

**Comment by ferchaure** [comment]
It looks like the .nsc file has a new format that we don't support.... Yo can try edit the file Raw_data_readers/ncs_wc_reader.m line 105 and remove ***obj.num_scale_factor**; but you will lose the scale of the signal. If you can open the file with Matlab, make a .mat file with the signal in a variable **data**.
