### ISSUE TITLE
batch processing output spike feature instead of spike shape

### ISSUE THREAD

**Issue by hanyanhanyan** [csn-le/wave_clus#53]
Hi,

Now the batch processing is working perfect fine.
The output screen shot like picture is very helpful.
However, I was wondering if it can show the spike feature instead of spike shape, just like I can switch it in the GUI. (the first figure, on top of the temperature figure)

Thanks a lot!

**Comment by ferchaure** [comment]
Not really. I never think about that... maybe you could try if that helps for separate spikes manually.
In Do_clustering around line 269 we get the spikes (variable _spikes_) and the features for each of them (_inspk_). You could switch them after that load.

**Comment by hanyanhanyan** [comment]
Thanks I'll try it out.
One stupid question,
Say Cluster 1: #1000 (450), what does that 450 mean?

Thanks a lot
![screen shot 2017-10-03 at 1 45 22 pm](https://user-images.githubusercontent.com/32147051/31140098-79cd59fa-a841-11e7-8f4a-953f213da68b.png)

**Comment by ferchaure** [comment]
I'm so sorry, I didn't add that to the documentation. That number is the amount of spikes in the SPC solution, the rest were "forced" to the cluster. You can play around with that using the force button in the GUI

**Comment by hanyanhanyan** [comment]
Thanks!

And what about the blue and black in the ISI, why the color are different?

![screen shot 2017-10-04 at 8 33 58 pm](https://user-images.githubusercontent.com/32147051/31206049-822fd304-a943-11e7-99f8-10921092b25a.png)

**Comment by ferchaure** [comment]
I don't know... maybe a new feature of Matlab? The colours changed around 20,40,60,80 and 100. It looks like an update of the usual hist plot.
