### ISSUE TITLE
amplitude of spikes

### ISSUE THREAD

**Issue by hanyanhanyan** [csn-le/wave_clus#54]
Hi,

I was using wave_clus to sort the spikes, and divided the recording time as firing rate.
It was very helpful, thank you very much.

Recently I was trying to quantify the amplitude of spikes. 
Do you know have any idea how to do that?
Is there a matrix that indicates the amplitude so that I can use max-min maybe?

Thanks!

**Comment by ferchaure** [comment]
Check the variable **spikes** inside the files _\*\_spikes.mat_ or _times\_\*_
There you will find the waveform of each spike. For example if the position in the parameter par.w_pre = 20; the vector spikes(:,20) is what you want.

**Comment by hanyanhanyan** [comment]
Thanks for the reply.

Say what I had is 5000 waveforms in 2 clusters, and I want to know the average amplitude of cluster2. 
I saw *cluster_class* is 5000x2 with cluster number as column, and *spikes * got 5000x64 with shape of each spikes. I get that.

But does the order in *cluster_class* and *spikes* the same?
More specific, is the 20th waveform in *spikes* also the 20th in *cluster_class*, so that I would know which cluster it belongs to?

Thanks!

**Comment by ferchaure** [comment]
> But does the order in cluster_class and spikes the same?
> More specific, is the 20th waveform in spikes also the 20th in cluster_class, so that I would know which cluster it belongs to?

Yes

**Comment by ferchaure** [comment]
Hi, @hanyanhanyan , If you don't have more questions about this topic, please close the issue.
