### ISSUE TITLE
Problem with spike detection

### ISSUE THREAD

**Issue by subhacom** [csn-le/wave_clus#55]
I am trying to process tetrode data and since I am getting too many uncategorized spikes with default setting of stdmin=5,  I increased it to 6. However that throws an error:
```
>> Get_spikes_pol(1);
Deletion requires an existing variable.

Error in index_detect_pol (line 102)
index(find(aux==1))=[];

Error in amp_detect_pol (line 25)
   [indexch,xf(i,:),thr(i)] = index_detect_pol(x(i,:),par); % spike times and filtered data

Error in Get_spikes_pol>get_spikes_pol_single (line 136)
        [spikes, new_index] = amp_detect_pol(x,par); clear x;

Error in Get_spikes_pol (line 62)
        get_spikes_pol_single(polytrodes(j), par_input);
```
Does this mean the algorithm is failing to find any spikes? 
Also, in some cases there are clusters visible in feature space, but changing temperature does not separate them. Is there a way to manually separate clusters in the projection of the feature space?

**Comment by ferchaure** [comment]
That error appears because it could t find any spike. In the next commit I will add a message for that case.

>  Is there a way to manually separate clusters in the projection of the feature space?

Not for now.
