### ISSUE TITLE
spike sorting with stimulation 

### ISSUE THREAD

**Issue by hanyanhanyan** [csn-le/wave_clus#56]
Hi,

Now I am dealing with spike sorting with stimulations, 0.5Hz to evoke neurons without spontaneous activity (red arrows in the screen shot). I was expecting the cluster results would be one with all the stimulation and stim artifacts, and one with real spikes. However it seems not like it.

Do you have any tips for the recordings with stimulations, any parameter suggestions?

![capture](https://user-images.githubusercontent.com/32147051/32028097-c15b382a-b9ba-11e7-8208-b5005fdd4859.PNG)

**Comment by ferchaure** [comment]
Probably you are rejecting the stim artifacts because they cross the threshold for detection. Try setting par.stdmax = 35;
