### ISSUE TITLE
time stamp of spikes in seconds

### ISSUE THREAD

**Issue by hanyanhanyan** [csn-le/wave_clus#58]
Hi,

I am currently working on PSTH,
Is there an array indicates the time stamp of spikes in seconds?

**Comment by hanyanhanyan** [comment]
or in position, I can divide by sampling rate?

**Comment by ferchaure** [comment]
from the readme file, about the times file:

The variable cluster_class has 2 columns and nspk rows (nspk is the number of spikes). The first column is the cluster class, with integers denoting the clusters membership and a value of 0 for those spikes not assigned to any cluster. The second column is the spike times in ms.
