### ISSUE TITLE
Unit of raw data - Simulated dataset 'C_*'

### ISSUE THREAD

**Issue by suhyun4** [csn-le/wave_clus#59]
I have some questions!!
1. What is the y-axis unit in file('C_Difficult2_noise01.mat') ?
2. What is the exact meaning of spike_time in 'C_Difficult2_noise01.mat'? starting point of spike?

Thank you

**Comment by ferchaure** [comment]
1.  It's not a physical unit. The amplitude of the mean spikes of each class is 1
2. Yes

You could find more info about this data set here:

` Quian Quiroga, R., Nadasdy, Z. & Ben-Shaul, Y. Unsupervised spike detection and sorting with wavelets and superparamagnetic clustering. Neural computation 16, 1661–1687 (2004).`

**Comment by suhyun4** [comment]
I'm so sorry. Question1 means what is the unit of y-axis of 'data'(1440000 samples) in file ('C_Difficult2_noise01.mat') such as microvolt, volt?

**Comment by ferchaure** [comment]
not really, the simulations doesn't try to be realistic in that way. The scale doesn't have a physical meaning.

**Comment by suhyun4** [comment]
Oh, I see. thank you.
So, is there any real recording raw data which include spike and noise? Can you tell me the filename?

**Comment by ferchaure** [comment]
You can make your own simulation with neurocube or ViSAPy

**Comment by HLBayes** [comment]
thx for your had share data at first.
I have some questions as well.
    1. What is the exact meaning of spike_time{1,3} in 'C_Difficult2_noise01.mat'? the time of two or three spikes was overlap?
    2. If the answer of question 1 is yes, then, why the max of spike_time{1,3} is 79? why it is greater than 64? 
Thank you

**Comment by HLBayes** [comment]
thx for your had share data at first.
I have some questions as well.

    1. What is the exact meaning of spike_time{1,3} in 'C_Difficult2_noise01.mat'? the time of two or three spikes was overlap?
    2. If the answer of question 1 is yes, then, why the max of spike_time{1,3} is 79? why it is greater than 64?

Thank you

**Comment by HLBayes** [comment]
thx for your had share data at first.
I have some questions as well.

 1. What is the exact meaning of spike_time{1,3} in 'C_Difficult2_noise01.mat'? the time of two or three spikes was overlap?
 2. If the answer of question 1 is yes, then, why the max of spike_time{1,3} is 79? why it is greater than 64?

Thank you

**Comment by ferchaure** [comment]
Hi, Sorry but I don't have the documentation of the non-fundamental variables in that simulations. It could be an internal variable of the simulation that doesn't add new information.

**Comment by HLBayes** [comment]
I'm so sorry to haven't introduce my question correctly/clearly.
 
 1. The one of the "spike_class" in the data-'C_Difficult2_noise01.mat' is label to mark the overlap spikes. And the label just be 0 or 1, so I don't known the label 1 is show us with "it's two spikes were overlapped" or "it's three spikes were overlapped"?
 2.  And another information of the "spike_class" in the data-'C_Difficult2_noise01.mat' is the the overlap-times of the overlapped spikes. And the number of this information ranges between 0 and 79, but one spike is just 64 sample points. So I'm confused to the ranges of the overlap-time, or I'am misunderstanding this data-"spike_class"

thx very much.

**Comment by ferchaure** [comment]
1. I´m not sure, I´m not even know the definition of overlapping in that simulations. You have 64 samples but some waveforms  doesn't have a enough amplitude in all of them to generate a clear overlapping in the next waveform if the next spike starts at the end of the previous waveform. For that cases I recommend to use the mean waveforms and the spike times to make your own overlapping vector.
2. I'm don't know, but you can check it just looking the signal and the spike times.

**Comment by HLBayes** [comment]
OK. thanks at all.

**Comment by HLBayes** [comment]
So sorry to bother you again,
How can we know  an overlapped-spike consists of which two or which three non-overlap spikes?
thx very much.

**Comment by ferchaure** [comment]
For each group of 3 consecutive spikes check if the difference in time between the first and the last one is less than 64 samples (or maybe 60)
probably you can use something like 
`[find(diff(times_in_samples(1:2:end))<64) find(diff(times_in_samples(2:2:end))<64)]`

**Comment by HLBayes** [comment]
Yeah, right.
I use this getting all overlapped-spikes' index,
and I just left behind a question: on the overlapped-spike index has a number which is above 64, and I have describe at first. anyway, thanks a lot

**Comment by ferchaure** [comment]
I think you can discard that ones
