### ISSUE TITLE
Independent functions

### ISSUE THREAD

**Issue by Quousque-tandem-abutere-patientia-nostr** [csn-le/wave_clus#6]
Hi,
Would you have a separate version of the wavelet feature extraction and the superparamagnetic clustering I could use independently from the GUI.
I have a set of pre-detected and cut spikes and would really like to see how those methods perform compared to what we already use. (and it doesn’t very fit to use the full original recording)

I have looked a bit under the hood of your code and I think I could “disassemble” the parts I need, but if you already have them (and especially a description of the shape the inputs/outputs takes), it would be much simpler.

Thanks for your wonderful tool!
Best,
B

**Comment by ferchaure** [comment]
Hi, 
You can run the code without the GUI using the file: Batch_files/Do_clustering.m (if you want to “disassemble” de core of the algorithm, read the function do_clustering_single in that file)

If you want to use Batch_files/Do_clustering.m, you have to make a XXX_spikes.mat file with the variable spikes (matrix, with N rows = N spikes) and index (spikes times in ms, Only for plotting the ISI, the algorithm doesn't uses them)

**Comment by Quousque-tandem-abutere-patientia-nostr** [comment]
Thanks a lot.
Do_clustering keeps complaining that I do not pass the sampling rate, so I tried giving it as:
   param.sr=1/samplingInterval;
   Do_clustering('all','par',param)
However this does not seem to work. (it keep complaining)
under which name should I integrate this in my 'XXX_spikes.mat'? (And does it actually affect the features extraction and the clustering?)
Thanks!

**Comment by ferchaure** [comment]
The way to pass the sr, in this specific case, is adding the variable sr in the XXX_spikes.mat.

Your approach didn't work because, sr is a preprocessing and detection parameter and don't effect the clustering.

**Comment by Quousque-tandem-abutere-patientia-nostr** [comment]
If I add a sr parameter in my 'XXX_spikes.mat', this generate an error:

> Error using readInData (line 124)
> Reference to non-existent field 'ref_ms'.
> 
> Error in Do_clustering>do_clustering_single (line 357)
>     data_handler = readInData(par);
> 
> Error in Do_clustering (line 127)
>     parfor fnum = 1:length(filenames)

If this does not impact the clustering I will just forget about it.

I start to get nice clusters, however the plot_features stopped working. (and if I click the Plot all projections, I get an empty window.)
I found how to save the clusters. Where can I find the wavelet features to recreate those plot by myself?

Thanks!

**Comment by ferchaure** [comment]
Sorry, that error could be fixed if you add a par.ref_ms=2 in the XXX_spikes.mat (it won't change the clustering). In any case we will remove that bug in the next update.

The problem with "plot all" is quite odd, did another error or warning appear? In the current code, that plot isn't very useful because, the subplots are too tiny (this is already improved in the next release).
You can access the features used in the variable inspk inside the file times_XXX.mat. Remember that are only the features of the spikes that SPC used (par.max_spk ). If you want to know what spikes were chosen, check the variable ipermut inside the file times_XXX.mat.

**Comment by Quousque-tandem-abutere-patientia-nostr** [comment]
Sorry for the late answer,
There was indeed a warning appearing but I can’t seem to find a way to recreate it… (I changed my code and I no longer have that problem)

Thanks a lot for your explanations, I was able to do the analysis I wanted :)
