### ISSUE TITLE
ISI histogram

### ISSUE THREAD

**Issue by hanyanhanyan** [csn-le/wave_clus#62]
Hi,

I am wondering if there is a way just plot the ISI histogram rather than in a screenshot after I sorted the spikes, using the spike time stamp/event.

Thanks a lot!

**Comment by ferchaure** [comment]
You can make it yourself, from the times load the variable **cluster_class** and then the ISIs in ms of the class number N will be:
diff(cluster_class(cluster_class(:,1)==N,2))

**Comment by ferchaure** [comment]
have you been able to make the histogram?

**Comment by hanyanhanyan** [comment]
Yes!
I'm sorry for the late reply, but it really helped!
Thanks a lot!!!
