### ISSUE TITLE
Large variable handling

### ISSUE THREAD

**Issue by hamdanspam** [csn-le/wave_clus#63]
When I run my biggest data file, I get this warning:

> Warning: Variable 'spikes' was not saved. For variables larger than 2GB use MAT-file version 7.3 or later. 
>   In Get_spikes_pol>get_spikes_pol_single (line 155)
>   In Get_spikes_pol (line 62) 

I went to line 155 as indicated in the warning, changed a line from 
`save([out_filename '_spikes'], 'spikes', 'index','par','thr')`
to
`save([out_filename '_spikes'], 'spikes', 'index','par','thr', '-v7.3')`

**Comment by ferchaure** [comment]
Thanks, I will add a try/catch for this case, in the next commit

**Comment by hamdanspam** [comment]
When I hit 'save clusters' in the gui for my largest polytrode dataset (same as before), I get an error like the one above. I don't quite know how to add the `-v7.3` parameter this time because the `save` command is inside of an `eval` command.

> Warning: Variable 'spikes' was not saved. For variables larger than 2GB use MAT-file version 7.3 or later. 
 In wave_clus>save_clusters_button_Callback (line 547)
  In gui_mainfcn (line 95)
  In wave_clus (line 63) 
Warning: UI controls may not print or export properly because the output has been scaled. Setting the figure's
PaperPositionMode property to 'auto' may help.

**Comment by ferchaure** [comment]
I know. I will have to change like 4 files that save the spikes variable.

**Comment by axwi** [comment]
You can change the default MAT-file version in the Matlab preferences.
See: https://se.mathworks.com/help/matlab/import_export/mat-file-versions.html
