### ISSUE TITLE
Loading data

### ISSUE THREAD

**Issue by Catherine100** [csn-le/wave_clus#64]
Hello!
I'm probably missing something obvious, but every time I load new data, I get the same two spike shapes and the same number of spikes. I think I have the latest version, which was in a folder called wave_clus-testing. When I try loading simulated data from the website, it does not look the same as in the PowerPoint tutorial.
Thanks in advance for any ideas!

**Comment by ferchaure** [comment]
Do you have a _times_yourfilename_ file in that folder or in your matlab path?
That PowerPoint presentation is quite old, sorry.

**Comment by Catherine100** [comment]
Hi Fernando,

Thanks so much for writing so fast!

I did eventually find a file starting with time_  in another folder and
deleting it meant that I did get different results for each dataset. I've
since had to switch to a different computer, though, and there doesn't seem
to be a problem. I can't find a file starting with time_ anywhere though
now. Should there be one? What are the .dg.lab files?

Could I also ask why the threshold in the first plot is under the data,
i.e. plotted as negative? From the literature, everyone else seems to have
it above!

Thanks again!

Best,
Catherine

Am 13.02.2018 5:12 nachm. schrieb "Fernando Chaure" <
notifications@github.com>:

**Comment by Catherine100** [comment]
I don't believe it! I checked with several data sets before writing! It's
now just started happening again though! It says 'Segment read only for
plotting'. I can't find a file starting with times_ anywhere though!




Am 13.02.2018 6:36 nachm. schrieb "Catherine Sweeney-Reed" <
catherine.sweeney-reed@med.ovgu.de>:

Hi Fernando,

Thanks so much for writing so fast!

I did eventually find a file starting with time_  in another folder and
deleting it meant that I did get different results for each dataset. I've
since had to switch to a different computer, though, and there doesn't seem
to be a problem. I can't find a file starting with time_ anywhere though
now. Should there be one? What are the .dg.lab files?

Could I also ask why the threshold in the first plot is under the data,
i.e. plotted as negative? From the literature, everyone else seems to have
it above!

Thanks again!

Best,
Catherine

Am 13.02.2018 5:12 nachm. schrieb "Fernando Chaure" <
notifications@github.com>:

**Comment by ferchaure** [comment]
> I can't find a file starting with time_ anywhere though now. Should there be one?

Wave_clus saves the sorting solution in a _times_ file. If Wave_clus finds a _times_ with the same name as the input file, it won't make a new sorting and it will use  that solution.

>  What are the .dg.lab files?

They are auxiliary files of the sorting. They have the data to explore all the SPC possible solutions. If you want to explore the temperature map, keep them.

> Could I also ask why the threshold in the first plot is under the data, i.e. plotted as negative? 

The type of detection depends of your data, you can make it positive or negative, look the **set_parameters.m** file.

**Comment by ferchaure** [comment]
>  It says 'Segment read only for plotting'. 

You see that message because wave_clus is opening the raw data to get the little segment of signal to plot  in the top of the GUI. In some cases open the input file is quiet slow and you don't want to do that. It's only a warning not an error.

**Comment by Catherine100** [comment]
It seems to plot that segment on its own when it's not doing the clustering
but simply taking the results of the last clustering. The times file has
just appeared again! It doesn't appear every time I save clusters. Should
it?

Thanks v much!

Am 13.02.2018 10:37 nachm. schrieb "Fernando Chaure" <
notifications@github.com>:

It says 'Segment read only for plotting'.

You see that message because wave_clus is opening the raw data to get the
little segment of signal to plot in the top of the GUI. In some cases open
the input file is quiet slow and you don't want to do that. It's only a
warning not an error.

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub
<https://github.com/csn-le/wave_clus/issues/64#issuecomment-365412650>, or mute
the thread

**Comment by ferchaure** [comment]
> It seems to plot that segment on its own when it's not doing the clustering but simply taking the results of the last clustering. 

Yes, because when you make the first sorting, wave_clus has to open the file to get the spikes too. For that reason it isn't "only for plotting".

> It  doesn't appear every time I save clusters. Should it?

Yes, It should. It could take a time it to save the file.

**Comment by Catherine100** [comment]
Thanks so much for all your help!



--
PD Dr. Catherine M. Sweeney-Reed
Neurocybernetics and Rehabilitation
Neurokybernetik und Rehabilitation
Clinic for Neurology and Stereotactic Neurosurgery
Otto von Guericke University
Leipziger Str. 44
39120 Magdeburg
Germany
