### ISSUE TITLE
Waveform plotting x axis

### ISSUE THREAD

**Issue by hamdanspam** [csn-le/wave_clus#66]
I am having trouble finding an explanation of what the x axis of the waveform plots mean. Is it just samples? In the picture below, it's always from 0 to 60, so ms doesn't fit for a neural waveform. 
![image](https://user-images.githubusercontent.com/15875720/36942807-d4f8639a-1f49-11e8-8cc1-34b74a57455c.png)

**Comment by ferchaure** [comment]
yes, they are samples.
You can set the number of samples before and after the peak in the set_parameters.m file.
About the picture, that is the cluster 0, they are the unsorted waveforms (usually noise)

**Comment by hamdanspam** [comment]
Great. That answers my question and more.
