### ISSUE TITLE
Cluster_class variable repeat timestamps

### ISSUE THREAD

**Issue by hamdanspam** [csn-le/wave_clus#67]
I noticed there are many repeat timestamps in cluster_class, a variable in times_[filename].mat, for multiple spike classes. A spike at time t is classified as spike class 1, and in the next row t is classified as spike class 2, for example. Does this mean that one spike may be classified as more than one spike class?

**Comment by ferchaure** [comment]
Maybe this will help, from the README file:
The variable cluster_class has 2 columns and nspk rows (nspk is the number of spikes). The first column is the cluster class, with integers denoting the clusters membership and a value of 0 for those spikes not assigned to any cluster. The second column is the spike times in ms.

**Comment by hamdanspam** [comment]
I'm right there with you. I'm seeing repeats in the second column, but each spike should only be assigned to one spike classification, right?

**Comment by ferchaure** [comment]
Right, each spike has only one class.
