### ISSUE TITLE
stdmin and clustering

### ISSUE THREAD

**Issue by babaz123** [csn-le/wave_clus#68]
​Hello,

When std_min for detection is too low, wave_clus isn't able to detect some clusters (all spikes end up in the same cluster). Why?

Here is an example with:

stdmin=2
![image](https://user-images.githubusercontent.com/16312521/37171930-6e7bb1ac-22dd-11e8-9f54-be5361d33b4f.png)

stdmin=3
![image](https://user-images.githubusercontent.com/16312521/37171914-601a9c36-22dd-11e8-8db1-77460f157f2f.png)

Thanks

**Comment by ferchaure** [comment]
Because you have too much noise to find the best temperature and/or  the relevant features  are dominated by the noise "spikes" and they aren't use for the clustering.
You can check the first case using the solution in another temperature.

**Comment by babaz123** [comment]
Thanks for you reply!

The problem is that the optimal stdmin varies from one channel to another, and from one recording session to another. Using the batch scripts, is there a way to automatically define the optimal stdmin (and get the maximum number of clusters whose size is higher than the minimum one)?

Thanks

**Comment by ferchaure** [comment]
I don't think that stdmin is the main reason of the issue. Did you improve the automatic sorting using the GUI?

**Comment by babaz123** [comment]
Yes, I found out good parameters through the GUI (my goal is to pick up as many single units as possible), but as I mentioned, according to the recordings' conditions which can fluctuate, they may require some adjustments.

**Comment by ferchaure** [comment]
But did you check all the peaks in the temperature map? Probably the clusters are there,  but the automatic temperature isn't the best or the only one.

**Comment by babaz123** [comment]
No, I didn't check all the peaks. I forgot to tell you that the amount of data I gather is quite big (several hours of daily recordings, 16 channels). I need an automatic solution.

**Comment by ferchaure** [comment]
The current algorithm is quite better if you check the peaks, you could miss a lot of neurons using only the automatic solution.

**Comment by babaz123** [comment]
Thanks. Using manual sorting would requise hundreds of hours, so out of the question. Which SPC parameters do you suggest to modify?

**Comment by ferchaure** [comment]
The parameters aren't the issue, you have to check the solution at different temperatures using the GUI to find the best clustering of the data.

**Comment by ferchaure** [comment]
Hi @babaz123 , we have a new code that could help with you problem (just download the last wave_clus from this repository). It's automatic but is probable that you have to change the parameter **par.min_clus** because you have a lot of noise there.

**Comment by babaz123** [comment]
Thanks a lot for the follow-up. What did you change?

**Comment by ferchaure** [comment]
Now, we use a variable number of features and an automatic way to select cluster at different temperatures. More info [here](https://github.com/csn-le/wave_clus/issues/85)

**Comment by babaz123** [comment]
With the new codes, I get now the following error:

Do_clustering('all','parallel',true,'make_plots',true,'par',param)
Starting parallel pool (parpool) using the 'local' profile ... connected to 4 workers.

ans = 

 Pool with properties: 

            Connected: true
           NumWorkers: 4
              Cluster: local
        AttachedFiles: {}
          IdleTimeout: 30 minute(s) (30 minutes remaining)
          SpmdEnabled: true

Error using wave_features (line 30)
Size arguments must be real integers.

Error in Do_clustering>do_clustering_single (line 516)
    inspk = wave_features(spikes,par);     %takes wavelet coefficients.

Error in Do_clustering (line 159)
        parfor fnum = 1:Nfiles

**Comment by babaz123** [comment]
PS - It seems not easy to use breakpoints in a parfor loop...!

**Comment by ferchaure** [comment]
if you do: 
`Do_clustering('all','parallel',false,'make_plots',true,'par',param)` 
It won't use the parallel

How long are the spikes in your XXX_spikes.mat file?

**Comment by babaz123** [comment]
You could download here one of my XXX_spikes.mat files: https://www.dropbox.com/s/ipgwlkf4qc7zvp7/1_spikes.mat?dl=0

The problem is in wave_fatures.m:
cc(:,nccum(cf-1)+1:nccum(cf)) = reshape(c_l(wccum(cf-1)+1:wccum(cf)),nc(cf),nspk)';

**Comment by ferchaure** [comment]
The issue is that your spikes have 35 samples it has to be a power of 2, you have to remove 3 samples. Otherwise you get border effects and the wavelets features are less useful.

Try par.w_post = 10;   and par.w_post = 22;  and use Get_spikes again.

**Comment by ferchaure** [comment]
If an acquisition system force you to use that length of spikes, I add an exception in the code to use the previous wavelet extraction.

**Comment by NeuroLuke** [comment]
Dear Fernando,

thanks for this great toolbox!

I've got a similar question like babaz123:
Sometimes, waveclus extracts only one cluster and assigns all spikes to this cluster (without having a "rest"-cluster; see the attached figure). When I slightly increase the temperature for this cluster manually, the cluster gets much nicer and also the ISI distribution gets a lot better. Is there a way to change a specific waveclus-parameter instead of manually enhancing these clusters?
I'm using waveclus 3 as follows:
file2use4wc = {strcat(spike_path_spec, 'datacut_spikes.mat')};
myPar = [];
myPar.randomseed = 1;
myPar.template_sdnum = 1.5;
myPar.min_clus = 60;
myPar.max_clus = 10;
Do_clustering(file2use4wc, 'par', myPar);

Best wishes,
L.

![waveclusquestion2fernando_041218](https://user-images.githubusercontent.com/45565018/49432489-19906b80-f7b0-11e8-85b1-8d7545a01203.png)

**Comment by ferchaure** [comment]
Increasing par.mintemp will force a higher temperature in cases like yours.

**Comment by NeuroLuke** [comment]
Great, thanks!
