### ISSUE TITLE
par.sr not overwritten in batch script

### ISSUE THREAD

**Issue by babaz123** [csn-le/wave_clus#70]
Hello,

Using:
```
X=22000;
param.sr = X;
Get_spikes(files,'parallel',true,'par',param)
Do_clustering('all','parallel',true,'par',param)
```
par.sr saved in set_parameters.m seems used instead, although the value X is saved in the resulting X_spikes.mat and times_X.mat files.

Indeed, when modifying par.sr in set_parameters.m and running the commands written above, the spikes' times show a time offset.

What do you think?

Thank you

**Comment by ferchaure** [comment]
What type of file are you loading?
Do you get a warning when you run Get_spikes?

**Comment by babaz123** [comment]
I'm loading files just containing "data" variables (the raw signal).
Yes, I get a warning ("no sr has been found in the file...")

**Comment by ferchaure** [comment]
In that same file add a variable called **sr**, with the sampling rate. Probably there is the bug.

**Comment by babaz123** [comment]
Thanks!
