### ISSUE TITLE
Use clusters of previous epochs as templates

### ISSUE THREAD

**Issue by perczelgy** [csn-le/wave_clus#71]
Is it possible to use clusters of previous epochs as templates? E.g. I have a really nice epoch of recording and succeeded to get very clear clusters. Can I somehow define these clusters as templates for the next epoch to analyse?  (Regarding our scientific interest, this is reasonable, but I am not sure I am capable of doing so using wave_clus.) Thanks for your help I advance!

**Comment by ferchaure** [comment]
Sorry, Wave_clus doesn't have that feature. You can do it manually using the previous classes as "sorted" by the SPC just before the template matching. But probably isn't easy to code.
You could try [combinato](https://github.com/jniediek/combinato), its a quite nice project based partially on Wave_clus, and that type of features.

**Comment by perczelgy** [comment]
Thank you very much for your quick answer, i will try combinato!
