### ISSUE TITLE
Error when merging clusters

### ISSUE THREAD

**Issue by perczelgy** [csn-le/wave_clus#75]
Dear Fernando!

I have the following problem: 
I run the spike detection and clustering on a polytrode in batch mode and when I load them in the GUI of wave_clus I set the temperature to high values to see very nice clusters. After successfully merging some clusters I get an error messages when I try to merge other clusters.  
![error_command_window](https://user-images.githubusercontent.com/26854636/38855590-26140926-4224-11e8-8b81-1b030990f4cc.JPG)
I did not encounter this problem when I started using wave_clus a few weeks ago, the first time it occurred was 1 or 2 day ago. I tried the 'brute-force problem-solving' (deleting and downloading wave_clus, later even uninstalling and reinstalling MATLAB R2015a) but this did not help.
Do you have any idea what could be the problem?

Thanks in advance for any help: György

P.S: I attached the clustered dataset also as an example (I received the same error message with other datasets too), without the datafiles as they are too big to be shared here:
[clustered_dataset.zip](https://github.com/csn-le/wave_clus/files/1918606/clustered_dataset.zip)

**Comment by ferchaure** [comment]
Hi György

I will check this asap, thanks for all the info.

**Comment by ferchaure** [comment]
fixed in the last commit

**Comment by perczelgy** [comment]
Hi Fernando!

Thank you very much, it works perfectly now! 

Thanks: György
