### ISSUE TITLE
exact content of variable 'inspk'

### ISSUE THREAD

**Issue by perczelgy** [csn-le/wave_clus#76]
Dear Fernando!

I was wondering  if 'inspk' in 'times_polytrode[n].mat' contains only the wavelet coefficients that were accepted during the Kolmogorov-Smirnov test (the ones with the most multimodal distribution) or all the computed coefficients?

Thank you in advance, György

**Comment by ferchaure** [comment]
Only the accepted during the Kolmogorov-Smirnov test
