### ISSUE TITLE
error when loading results in the GUI

### ISSUE THREAD

**Issue by babaz123** [csn-le/wave_clus#77]
Hello,

After detecting and clustering spikes with "batch scripts", I would like to supervise manually some results. When opening spikes_X.mat or X_times.mat files in the wave_clus GUI, I get the following error:

`wave_clus
Reference to non-existent field 'all_classes_ax'.

Error in plot_spikes (line 272)
        if get(handles.spike_shapes_button,'value') ==1 &&
        (get(handles.plot_all_button,'value') ==1) &&
        ~strcmp(par.all_classes_ax,'mean')

Error in wave_clus>load_data_button_Callback (line 375)
plot_spikes(handles); %This function edits userdata

Error in gui_mainfcn (line 95)
        feval(varargin{:});

Error in wave_clus (line 63)
    gui_mainfcn(gui_State, varargin{:});
 
Error while evaluating UIControl Callback`

**Comment by ferchaure** [comment]
Hi
Did you keep the file set_parameters.m from an older version of wave_clus?

**Comment by babaz123** [comment]
Yes... :)
