### ISSUE TITLE
segments cut

### ISSUE THREAD

**Issue by hanyanhanyan** [csn-le/wave_clus#78]
Hi,

In the set parameters I saw that you could choose the segment length for analysis.
It basically from the beginning to whenever you want to cut it.
Now I want to cut it in the middle of the recordings, i.e. from 2min to 4min.
But if I do it as par.segments_length=2, it will give 0 to 2min instead of 2 to 4.

Is there any other way to choose the segments not from the beginning?

Thanks a lot!

**Comment by ferchaure** [comment]
In set_parameters.m you can find exactly that:

```
% DETECTION PARAMETERS
par.tmax = 'all';                    % maximum time to load
%par.tmax= 180;                      % maximum time to load (in sec)
par.tmin= 0;                         % starting time for loading (in sec)
```

**Comment by ferchaure** [comment]
Have you been able to load the data as you want?

**Comment by hanyanhanyan** [comment]
Yes it worked perfectly !
Thank you !
