### ISSUE TITLE
Load simulated data C_Easy1_noise01_short

### ISSUE THREAD

**Issue by IljaPilja** [csn-le/wave_clus#80]
Hi,
I placed the wave_clus folder into my Matlab file folder. The simulated data I'd like to try, as suggested by the PowerPoint presentation is called  'C_Easy1_noise01_short.mat' and located in \wave_clus-testing\Sample_data\Simulator. I start the program by typing wave_clus in the command window. I choose Data simulator and then load data and pick the desired simulated data. The following warning is depicted by Matlab:

par = 

  struct with fields:

          mintemp: 0
          maxtemp: 0.2010
         tempstep: 0.0100
         SWCycles: 100
      KNearNeighb: 11
         num_temp: 20
         min_clus: 130
         max_clus: 13
       randomseed: 0
        temp_plot: 'log'
            fname: 'data'
             tmax: 'all'
               sr: 24000
            w_pre: 20
           w_post: 44
              ref: 72
           stdmin: 4
           stdmax: 25
      detect_fmin: 300
      detect_fmax: 3000
        sort_fmin: 300
        sort_fmax: 3000
        detection: 'pos'
       int_factor: 4
    interpolation: 'y'
           inputs: 10
           scales: 5
         features: 'wav'

Warning: File 'data_wc.dg_01.lab' not found. 
> In run_cluster (line 7)
  In wave_clus>load_data_button_Callback (line 143)
  In gui_mainfcn (line 95)
  In wave_clus (line 42) 

Warning from run_cluster (line 7)
eval( ['delete([fname ''.dg_01.lab''])' ],'[];');

Now I looked for similar problems that people were having but one person solved the problem by placing folder in home directory and the other used a Mac but I can't make use of these results. Within the Simulator folder there is a file called 'data_wc.run' and under Sample_data there exist the following 'dg_01' files:
data.dg_01
data.dg_01.lab
data_test.dg_01
data_test.dg_01.lab
data_test1_spikes.dg_01
data_test1_spikes.dg_01.lab 

I have tried another simulated file and the same warning message is displayed. By the way I'm using Windows 8 and Matlab 2016b which does have the Wavelet toolbox active as well.
I've already given up using Klusta and I really need this to work. Please, any help would be greatly appreciated.
Thanks,
Dymphie

**Comment by IljaPilja** [comment]
Hi,
after trying a few things, I found that there seem to be two slightly different versions of the program within the Web. One seems to be the more up-to-date version containing the Simulated data option within the GUI and the other simply has the load data push-button. The latter however, does create the data_wc.dg_01 and the data_wc.dg_01.lab files that are not found in the newer version. One other problem seems to be the detection of the PC system. I have PCWIN64 however the Simulator file only contains the cluster_linux.exe and as I'm not using Linux I assume this can't be correct. now I could simply use the older version of the program but there might be some important changes that are found in one over the other. Please, if anyone has faced this same problem let me know.

Thanks,
Dymphie

**Comment by ferchaure** [comment]
Hi Dymphie

You have some issue with the versions, you can download the last one from  [here](https://github.com/csn-le/wave_clus/archive/testing.zip)

Then try these steps:
- Remove all the folders with simulations from your Matlab path.
- Remove all the wave_clus folders from your Matlab path and add the new one
- Create another folder outside the one with the wave_clus code, and put the the simulations.
-  Open de GUI and go to "load data",etc.

Let me know how this goes.

**Comment by IljaPilja** [comment]
Hi,
thanks for your help and yes it does work but this seems to be an older version of the program. The newer version has some more compact programing and the error that comes up regarding Error in plot_spikes (line 388) is fixed elegantly. The histogram edgecolors and facecolors match the color of the clustered spike traces. If you say that those are just cosmetic changes and the program is otherwise identical in terms of the clustering algorithm then I'll gladly use the version that you provided. I'll just make those changes myself. By the way, from the following website I obtained this supposed ' newer version.

https://vis.caltech.edu/~rodri/Wave_clus/Wave_clus_home.htm

Thanks for your help.
Dymphie

**Comment by IljaPilja** [comment]
Hi,
the link in the above comment seems to be an older version of the program. I guess I'll just make some of those changes myself. Sorry about missing that piece of information from the mentioned website.
Again thanks for the help.
Dymphie

**Comment by ferchaure** [comment]
> The histogram edgecolors and facecolors match the color of the clustered spike traces.

It was a cosmetic change, yellow and green histograms weren't easy to see. Let me now if you have any issue with the latest version.
