### ISSUE TITLE
'A novel unsupervised spike sorting implementation with variable number of features'

### ISSUE THREAD

**Issue by perczelgy** [csn-le/wave_clus#84]
Hi Fernando!

I've found your article on the improving the feature- and cluster selections (https://ieeexplore.ieee.org/abstract/document/8211631/). I wanted to know if it is implemented and publicly available? We would be very interested in using it as a fully automated spike-sorting method?

Thanks in advance: György

**Comment by ferchaure** [comment]
Hi György, If you can wait a little more we are working in a even better implementation.

**Comment by perczelgy** [comment]
Hi Frenando!
I am definitely interested about that. When do you intend to release it? 
Best, György

**Comment by ferchaure** [comment]
Hi György

The new code is [here](https://github.com/csn-le/wave_clus/tree/master) we are still working on the documentation but the use is the same as before. 

Best, Fer
