### ISSUE TITLE
variable cluster solutions

### ISSUE THREAD

**Issue by checkoutchap** [csn-le/wave_clus#86]
hello, 

apologies if this is a naive question, but --

i am using the wave clus gui to sort a brief microelectrode recording (total length=3 seconds; sampling frequency=24,000 Hz). after loading my data into the gui, the default clustering seems to work fine. however, if i load the same data into the gui again, the 'clustering solution' (i.e., the number of identified clusters, and the number of spikes sorted into a given cluster) appears to change. 

what are the possible reasons for getting different clustering solutions with the same data? if it helps, here are the parameters i have set using the "set parameters" button:

          channels: 1
       segments_length: 5
                    sr: 24000
                  tmax: 'all'
                  tmin: 0
                 w_pre: 20
                w_post: 44
      alignment_window: 10
                stdmin: 3
                stdmax: 20
           detect_fmin: 300
           detect_fmax: 3000
             sort_fmin: 300
             sort_fmax: 3000
                ref_ms: 1.5000
             detection: 'pos'
            int_factor: 5
         interpolation: 'y'
            sort_order: 2
          detect_order: 4
        detection_date: '18-Jul-2018 15:38:25'
            min_inputs: 10
            max_inputs: 0.7500
                scales: 4
              features: 'wav'
        template_sdnum: 3
            template_k: 10
        template_k_min: 10
         template_type: 'center'
         force_feature: 'spk'
                 match: 'n'
               max_spk: 40000
                permut: 'y'
               mintemp: 0
               maxtemp: 0.2510
              tempstep: 0.0100
              SWCycles: 100
           KNearNeighb: 11
              min_clus: 15
              max_clus: 200
            randomseed: 0
            force_auto: 1
             elbow_min: 0.4000
                  c_ov: 0.7000
             temp_plot: 'log'
       max_spikes_plot: 1000
            print2file: 1
    plot_feature_stats: 0

cheers, 

david

**Comment by ferchaure** [comment]
The SPC algorithm is stochastic, you will get different results each time.  Specially with a small number of spikes.

**Comment by checkoutchap** [comment]
i see, thanks! 

can you recommend any ways to address this variability? e.g., performing the clustering many times and taking the most common cluster assignment for each spike? do you have a feel for how many spikes might be needed for the clustering to be more stable?

**Comment by ferchaure** [comment]
The number of spikes required to get more or less the same clustering depends of the noise of the signal, number of real clusters and more. ~5000 spikes maybe. Can you use a longer length?  Usually a few minutes is enough or at least 1 minute.

**Comment by aboharbf** [comment]
Adding here as to note begin a new thread - I am running into issues with variable solutions. for one of my recording days, I can get one of two solutions to clustering (even when I set the randomseed to non-0).

Solution 1, which seems more desirable given the feature space:
![image](https://user-images.githubusercontent.com/25850560/52570940-95c3b280-2de2-11e9-8352-5d30231d63fc.png)
![image](https://user-images.githubusercontent.com/25850560/52570947-9a886680-2de2-11e9-9b52-1d3948c0b706.png)


Solution 2, which happens sometimes, and seems undesirable:
![image](https://user-images.githubusercontent.com/25850560/52570961-a542fb80-2de2-11e9-841d-8bc5a7109730.png)
![image](https://user-images.githubusercontent.com/25850560/52570965-a6742880-2de2-11e9-8118-d95afd06cab0.png)

I understand the SPC is stochastic, but my confusion stems from the fact that the feature spaces it is working with look fundamentally different. They both seems like reasonable solutions given the feature space, but given that the feature space is constructed prior to the SPC step, and should in theory produce the same results no matter what, I am confused. After a bit of digging, the random selection of spikes going into the SPC may be the source, but I wanted to post and see what your thoughts were.

**Comment by ferchaure** [comment]
> After a bit of digging, the random selection of spikes going into the SPC may be the source, but I wanted to post and see what your thoughts were.

Exactly, that is the source of the variability between the plots.

**Comment by aboharbf** [comment]
I figured as much, but given that we are talking about many many spikes, is it surprising that a large random sampling of a very large population can produce such distinct results? I'm surprised that very non-overlapping feature sets ended up being used to cluster and this feature projection plot ends up looking so different.

**Comment by ferchaure** [comment]
Maybe the order if the features is not the same or even some feature could be replaced by other one in a similar lillietest value.
