### ISSUE TITLE
error of using 'reshape' in 'wave_features'

### ISSUE THREAD

**Issue by umiu60135** [csn-le/wave_clus#87]
Hello!

There is a problem when I use wave_clus 3.0. Everytime the function 'wave_features' is used, MATLAB will notice me an error that I must use an integer as the parameter of function 'reshape', as shown in the image. (I'm sorry for the Chinese words in the image, but I don't think it will affect your understanding.) 

I think the reason can be from the calculation of variable 'nc' ( nc = wv_c/nspk), but I still have no idea how to make it work. If you have any idea, could you reply to me? 

Thank you very much!

![image](https://user-images.githubusercontent.com/36126666/43968854-52ebf928-9c96-11e8-89f1-f1183c440559.png)

![image](https://user-images.githubusercontent.com/36126666/43968811-358403bc-9c96-11e8-8bc9-1e3ecb21a81e.png)

Looking forward to hearing from you!

Best,
Zhongpeng

**Comment by ferchaure** [comment]
How long are your spikes? Or which values of par.w_pre and par.w_post are you using?

**Comment by umiu60135** [comment]
Thank you very much!
