### ISSUE TITLE
Sampling rate

### ISSUE THREAD

**Issue by joostmaier** [csn-le/wave_clus#9]
Does anyone have any thoughts on the effect of sampling rate (20 vs 30 kHz) on the ability to sort spike recorded from single channel electrodes (i.e., no tetrode/polytrodes?)

**Comment by ferchaure** [comment]
Lower sampling rate = Spikes with less samples (remember to change the w_pre and w_post parameters, or you will have samples with only noise) and worst alignment. The alignment will add extra variability between templates and spikes. 
Does this change the result of the sorting? That depends of how similar are the templates of the neurons.

If you want my thoughts, I remember some theoretical framework about improving the separation of similar neurons in high frequencies (Yang et al. Improving spike separation using waveform derivatives).

**Comment by ferchaure** [comment]
I just remember this paper:
http://www.ncbi.nlm.nih.gov/pmc/articles/PMC4151286/
I think there is your answer
