### ISSUE TITLE
Wave_Clus GUI

### ISSUE THREAD

**Issue by heetkaku** [csn-le/wave_clus#91]
Hi,
I would like to add a few custom features to wave_clus, for example play the signal as audio. Where exactly should I look to make changes/add buttons to the GUI?

Regards,
Heet Kaku

**Comment by ferchaure** [comment]
Hi Heet Kaku
If you know how to edit the callbacks of the buttons/add new ones, a good example is the function manual_clus_button_Callback (line 723 in wave_clus.m)

**Comment by heetkaku** [comment]
I have a basic idea of it yes, I will give it a try. 

Thank you for your help : Heet Kaku
