### ISSUE TITLE
Why use elliptic filter?

### ISSUE THREAD

**Issue by perczelgy** [csn-le/wave_clus#94]
Hi Fernando,

Is there a specific reason you're using elliptic filter instead of a Butterworth filter? Wouldn't it be better to use a filter (e.g. Butterworth, as you mention in the original article of wave_clus) that returns a smoother signal?

Thank you: György

**Comment by ferchaure** [comment]
When you have more noise in the stop band, a low order Butterworth filter doesn't help much.  After a while using it the team found that an elliptic filter gave better clustering results. I did a few tests, and I checked that results for real data.
