### ISSUE TITLE
What are the required MATLAB toolboxes?  

### ISSUE THREAD

**Issue by surya002** [csn-le/wave_clus#98]
Hello

I am currently learning wave_clus. The following page says wave_clus requires **wavelet toolbox** and **signal processing toolbox**. https://vis.caltech.edu/~rodri/Wave_clus/wave_clus_intro.pdf
But while loading any of the simulated data in the GUI, it throws an error saying the function 'smooth' requires **curve fitting toolbox**. 

So my question is what are the toolboxes required to run wave_clus?

**Comment by ferchaure** [comment]
The intro is right. We fix the issue with the function 'smooth' in the last commit
