### ISSUE TITLE
How to run batch processing 

### ISSUE THREAD

**Issue by QZZ57** [csn-le/wave_clus#99]
The GUI for single channel processing works pretty well. However, I got in a trouble for batch processing:
when I was trying to do batch processing, there were 4 channels I hoped to process simultaneously, so I converted the file names  (channel_9.mat, channel_10.mat, channel_11.mat, channel_12.mat) into ASCII format and saved in a .txt file with the file name ‘polytrode1.txt’. Each ‘channel_X.mat’ file contains a ‘data’ vector and a ‘sr’ variable (same as in single channel processing through the GUI). However, I was keeping getting the error that ‘the file did not get uploaded’ when I called ‘Get_spikes_pol(1)’. I must have made an error, but for now, I couldn’t figure it out. Could you please let me know how to write down the file names properly and run the batch processing function? Greatly appreciate your kind help.

**Comment by ferchaure** [comment]
What do you mean with  'I converted the file names'?
Can I see a screenshot of the error?

**Comment by QZZ57** [comment]
Hi,
If I converted the file names (channel_9, channel_10) into ASCII format (099 104 097 110 110 101 108 095 057 046 109 097 116 013 010 099 104 097 110 110 101 108 095 049 048 046 109 097 116 013 010 013 010 013 010), there was an error when I called function Get_spikes_pol(1):

[cid:image001.png@01D46557.8CEA1C20]


Sent from Mail<https://go.microsoft.com/fwlink/?LinkId=550986> for Windows 10

**Comment by ferchaure** [comment]
You don't have to convert the names like that (probably there is an issue with the documentation), just write them in plain text. Did you see the wiki page? [https://github.com/csn-le/wave_clus/wiki/Polytrodes](https://github.com/csn-le/wave_clus/wiki/Polytrodes)

Let me know if you have better luck following that steps.

**Comment by QZZ57** [comment]
Yes, it’s working. Thanks so much.

Sent from Mail<https://go.microsoft.com/fwlink/?LinkId=550986> for Windows 10
